#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Polish Wordle word lists.
All words are filtered to exactly 5 characters.
"""

import os

# =====================================================================
# ALL CANDIDATE WORDS — will be filtered to exactly 5 chars
# =====================================================================

ALL_WORDS_RAW = [
    # ── Nature & geography ──────────────────────────────────────────
    "MORZE", "RZEKA", "SKAŁA", "KWIAT", "WIATR", "BURZA", "TRAWA",
    "LIŚCI", "PLAŻA", "PIACH", "GŁAZY", "ULEWA", "DYMEK", "ISKRA",
    "GAŁĄŹ", "MROZY", "MGŁOM", "MGŁEK",
    "SOSNA", "BRZEG", "WRÓBEL", "DOLNY",
    "NIEBO", "ZIEMA", "BAGNO", "ŁĄKĘ", "ŁĄKA", "GÓRAL",
    "SZCZYT", "FALER", "PIASEK", "KAMIE",
    "WULKA", "LAWIA",
    "FLORA", "FAUNA", "TAJGA", "TUNDR",
    "POLNA", "LEŚNA",
    "DĄBEK", "OLSZA", "WEŁNA", "OSIKA", "TOPÓL",
    "CHMUR", "ROSNĄ", "STRĄK", "KŁĄBY",
    "ŚNIEG", "TĘCZA", "KRYÓŁ",
    "STRON", "KONAR", "PĄKEK", "NASIO",
    "GRZYB", "MSZAK", "RDEST",
    "WIĄZY", "BLUSZCZ",
    "ŚWIAT", "OCEAN", "PACYF",
    "TATRY", "ODRZE",
    "KLIMAT", "BIEGU", "ZORZA",
    "PRZYL", "WYSPA", "CYPEL", "ZATOK",
    "STRUM", "UJŚCIE", "WODOSPAD",
    "DELTA", "LAGUNA", "GŁĘBIA",
    "JASKINIA", "SKALNE", "URWIS",
    "ŻWIRU", "MULIĆ", "ZIARN",
    "SKALNY", "GRUNTO", "GLEBA",
    "HUMUS", "PRÓCHNO", "PIARG",

    # ── Animals ──────────────────────────────────────────────────────
    "ZAJĄC", "JELEŃ", "SARNA", "ORZEŁ", "SOKÓŁ", "KARAŚ",
    "DORSZ", "ŚLEDŹ", "REKIN", "HOMAR", "MOTYL", "MUCHA", "KOMAR",
    "PAJĄK", "ŁOSOŚ", "KOCUR", "BARAN", "CIELĘ", "KLACZ", "ŹREBIĘ",
    "WRONA", "KAWKA", "SZPAK", "ŻURAW", "STRUŚ", "DUDEK",
    "MAŁPA", "ZEBRA", "GEPARD", "NOSOR",
    "SŁOŃ", "TYGRYS", "LAMPART",
    "KROKODYL", "ŻYRAFA",
    "KONDOR", "ALBATR",
    "PANDA", "KOJOT", "BISON",
    "BOBRA", "WYDRA", "NORKA", "FRETKA",
    "BORSUK", "SZAKAL",
    "PUMĄ", "KUGUARA",
    "ŁASIC", "GRONOSTAJ",
    "WOMBAT", "KANGUR",
    "TASMAŃSKI",
    "KOALA", "DINGO",
    "IGUANA", "KAMELEON",
    "WARANA", "MOKASYN",
    "KOBRA", "PYTON",
    "ANAKONDA", "MAMBA",
    "GEKON", "SKINK",
    "TRASZKA", "SALAMANDRA",
    "NIAŁKA", "ROPUCH",
    "KARP", "PSTRĄG",
    "WĘGORZ", "SZCZUPAK",
    "OKOŃ", "UKLEJA",
    "KARASI", "KARASIE",
    "SUM", "MIĘTUS",
    "DELFIN", "ORKA",
    "ŻARŁACZ",
    "KALMAR", "KAŁAMA",
    "HOMARY", "KREWET",
    "MAŁŻE", "OMUŁEK",
    "OŚMIOR",
    "PIJAWKA",
    "MEDUZ", "MEDUZA",
    "KORAL", "GĄBKA",
    "TRZMIE",
    "MRÓWKA", "PSZCZO",
    "CHRZĄS",
    "STONKA", "ŻUCZEK",
    "ŚWIETL",
    "WAŻKA", "MODLISZKA",
    "KONIK", "TERMIT",
    "MSZYCE", "MSZYCA",
    "BIEDRONKA",
    "PAJĄCZY",
    "KLESZCZE",
    "DŻDŻOW",

    # ── Body parts ───────────────────────────────────────────────────
    "GŁOWA", "SERCE", "PALEC", "RAMIĘ", "PLECY",
    "ŻEBRO", "NERKA", "PŁUCA", "JĘZYK", "WARGA", "RZĘSA", "CZOŁO",
    "BRODA", "PIĘTA", "ŻYŁKA", "TĘTNO", "SKÓRA", "WŁOSY",
    "NOŻYK", "MIĘSIEŃ", "TĘTNICA",
    "KRTAŃ", "WĄTROB",
    "MÓZGU", "SZYJKA",
    "BIODRA",
    "KOLANA", "ŁOKCIE",
    "NADGARSTEK",
    "DŁOŃ", "UDO", "ŁYDKA",
    "KRĘG", "KOŚĆ",
    "CHRZĄ",
    "ŚCIEGNO",
    "PĘPEK",
    "KLATKA",
    "MOSTEK",

    # ── Family ───────────────────────────────────────────────────────
    "MATKA", "CÓRKA", "WUJEK", "KUZYN",
    "BRACI", "SIOST",
    "BABCIĘ",
    "CIOCIA",
    "DZIAD",
    "BRATS",
    "SZWAGIER",
    "ZIĘCIEM",
    "SYNOWA",
    "PRADZIADEK",
    "PRABABCIA",

    # ── Food & drink ─────────────────────────────────────────────────
    "CHLEB", "MLEKO", "MASŁO", "JAJKO", "MIĘSO", "KASZA",
    "BIGOS", "WÓDKA", "ŻUREK", "ROSÓŁ", "RYŻYK", "MISKA", "KUBEK",
    "ŁYŻKA", "SEREK", "OLIWA", "BUDYŃ",
    "MAKARON", "KIEŁB",
    "ZUPKA",
    "KRUPNIK", "BARSZCZ",
    "FLACZKI",
    "KOTLET",
    "GOLONKA",
    "BIGOSEK",
    "KARZE", "KASHA", "LEKKA",
    "SAŁAT",
    "PIECZEŃ",
    "BUDYNEK",
    "OGÓREK", "RYBKA",
    "JABŁKO",
    "BANAN",
    "MANGO",
    "CYTRYN",
    "POMARAŃCZ",
    "WINOG",
    "ŚLIWK",
    "WIŚNIA",
    "MALINA",
    "TRUSK",
    "GRANAT",
    "PAPAYA",
    "MALIN",
    "NEKTARYNKA",
    "MORELA",
    "BRZOSKW",
    "GRUSZK",
    "PORZECZKA",
    "AGREST",
    "BORÓWKA",
    "ŻURAWINA",
    "KOKOS",
    "AWOKAD",
    "MANGO",
    "ANANASEM",
    "TWARÓ",
    "JOGUR",
    "ŚMIET",
    "TOFU",
    "TEMPEH",
    "SOLĄ", "PIEPRZEM",
    "OREGANO",
    "BAZYLIA",
    "TYMIAN",
    "ROŻMARY",
    "SZAFRAN",
    "PAPRYK",
    "CURRY",
    "KUMIN",
    "IMBIR",
    "WANILI",
    "CYNAMO",
    "GAŁĄZK",
    "CUKIER",
    "MIÓD",
    "SYROP",
    "DŻEMEM",
    "MARMOL",
    "GALARET",
    "WAFEL",
    "TORT",
    "CIASTO",
    "BUŁKA",
    "ROGAL",
    "PRECLE",
    "KRAKERSY",
    "HERBATNIKI",
    "CZEKOLADA",
    "LODY",
    "SORBET",
    "PUDIN",
    "KREMÓW",
    "BEZY",
    "PRALINKA",
    "TRUFFLE",
    "MARCYPAN",
    "NOUGAT",
    "TOFFI",
    "KARMEL",
    "NUGAT",
    "CHAŁWA",
    "TURRON",
    "CIASTKO",
    "PLACEK",
    "NALEŚNIK",
    "OMLET",
    "JAJECZ",
    "TOSTY",
    "KANAPKA",
    "ZAPIEK",
    "GRILLA",
    "PIECZONE",
    "GOTOWE",
    "SUROWE",
    "WĘDZONE",
    "MARYNOWANE",
    "SOLON",
    "PIKLOWANE",
    "FERMENTOW",
    "PIWO",
    "WINO",
    "SZAMPAN",
    "LIKIER",
    "WHISKY",
    "BRANDY",
    "KONIAK",
    "TEQUILA",
    "RUMEM",
    "GINEM",
    "WÓDKĘ",
    "NALEWKA",
    "MIODEK",
    "CYDR",
    "KEFIR",
    "MAŚLANKA",
    "KAWA",
    "HERBAT",
    "KAKAO",
    "KOMPOT",
    "NEKTAR",
    "SYROP",
    "LEMONI",
    "COLA",
    "SODA",
    "WODA",
    "MINERALNA",

    # ── House & furniture ────────────────────────────────────────────
    "DRZWI", "SUFIT", "KOMIN", "BRAMA",
    "ŁÓŻKO", "FOTEL", "SZAFA", "OBRAZ", "DYWAN", "LAMPA",
    "MYDŁO", "WANNA", "NORKA",
    "PARKET", "CEGIELN",
    "OKLEINA",
    "TYNK", "CEGŁA",
    "DACHÓWKA",
    "OKIENNICE",
    "ŻALUZJE",
    "ROLETY",
    "ZASŁON",
    "FIRANKA",
    "PARAPET",
    "TAPETA",
    "FARBA",
    "LAKIER",
    "GRUNTER",
    "GIPS",
    "CEMENT",
    "BETON",
    "KLEJ",
    "KITKA",
    "SZYBKA",
    "SZKIELET",
    "ŚCIANKA",
    "PODDASZE",
    "KOMNATA",
    "ALKIERZ",
    "SALON",
    "SYPIAL",
    "KUCHNIA",
    "ŁAZIENKA",
    "WIATROŁAP",
    "KORYTARZ",
    "SPIŻARNIA",
    "GARAŻ",
    "STRYCH",
    "PIWNICA",
    "TARAS",
    "BALKON",
    "OGRÓD",
    "PERGOLA",
    "BUNGALOW",
    "WILLA",
    "DWOREK",
    "PAŁAC",
    "ZAMEK",
    "KABINA",
    "BARAKA",
    "BARAK",
    "STAJNIA",
    "OBORA",
    "KURNIK",
    "OWCZARNIA",
    "SZOPA",
    "WIATA",
    "HANGAR",
    "MAGAZYN",
    "HALA",
    "SPICHLERZ",
    "SILOS",
    "CHATA",
    "IZBA",
    "KOMORA",
    "LOCH",
    "WIEŻA",
    "BASTION",
    "FORTYFIKACJA",
    "ZAMCZYSKO",

    # ── Furniture & objects ─────────────────────────────────────────
    "REGAŁ", "PÓŁKA", "KLUCZ",
    "SOFA",
    "KANAPA",
    "ŁAWKA",
    "PODNÓŻEK",
    "OTOMAN",
    "TABURET",
    "PUFA",
    "KOZŁEK",
    "STOŁEK",
    "TABORET",
    "SIEDZISKO",
    "PODUCHA",
    "WEZGŁOWIE",
    "ŚCIENNA",
    "KOŁDRA",
    "POŚCIEL",
    "PODUSZKA",
    "PRZEŚCIERADŁO",
    "NARZUTA",
    "KAPA",
    "PLEDEK",
    "SZUFLADA",
    "KOMODA",
    "WIESZAK",
    "DRĄŻEK",
    "WIESZADŁO",
    "HACZYK",
    "KLAMKA",
    "ZAWIASY",
    "RYGIEL",
    "SKOBEL",
    "KŁÓDKA",
    "ZACISK",
    "BOLEC",
    "ŚRUBA",
    "GWOŹDŹ",
    "GWÓŹDŹ",
    "NITKA",
    "ZSZYWKA",
    "TAŚMA",
    "SZNUREK",
    "LINEKM",
    "DRUTEK",
    "HACZYK",
    "KARABIŃCZYK",
    "KLAMRA",

    # ── Kitchen utensils ────────────────────────────────────────────
    "GARNEK", "TARKA",
    "SITO",
    "MIESZADŁO",
    "MASELNICA",
    "MOŹDZIERZ",
    "PRASA",
    "OKRĄGŁY",
    "TALERZ",
    "MISECZKA",
    "SALATERKA",
    "PÓŁMISEK",
    "MANEKIN",
    "TACKA",
    "DESKA",
    "NÓŻ",
    "WIDELEC",
    "ŁYŻECZKA",
    "NABIERAK",
    "CHOCHLA",
    "WARZĘCHEW",
    "SZPATUŁKA",
    "ŁOPATKA",
    "TRZEPACZKA",
    "MASZYNKA",
    "MIKSER",
    "BLENDER",
    "ROBOT",
    "TOSTER",
    "OPIEKACZ",
    "CZAJNIK",
    "EKSPRES",
    "KUCHENKA",
    "PIEKARNIK",
    "LODÓWKA",
    "ZAMRAŻARKA",
    "MIKROFALÓWKA",
    "OKAP",
    "ZMYWARKA",
    "SOKOWIRÓWKA",
    "WYCISKARKA",
    "KRAJALNICA",
    "TARNIK",
    "SPIRALIZER",

    # ── Clothes ──────────────────────────────────────────────────────
    "DŻINS", "PASEK", "SZEWC",
    "SUKNA",
    "SUKNO",
    "WEŁNA",
    "BAWEŁNA",
    "JEDWAB",
    "KASZMIE",
    "AKSAMIT",
    "ORGANZA",
    "SATYNA",
    "TAFTA",
    "KORONKA",
    "TIULEM",
    "FLAUSZ",
    "POLAR",
    "SOFTSHELL",
    "GORETEX",
    "NEOPREN",
    "LYCRA",
    "SPANDEX",
    "POLIESTER",
    "NYLON",
    "TWORZYWO",

    # ── School & office ──────────────────────────────────────────────
    "KLASA", "ATLAS", "NOTES", "BIURO", "PISMO", "UMOWA",
    "SZKOŁA",
    "LEKCJA",
    "NAUKA",
    "WIEDZA",
    "UCZEŃ",
    "STUDENT",
    "WYKŁAD",
    "EGZAMIN",
    "PRACA",
    "ZADANIE",
    "ĆWICZENIE",
    "SPRAWDZ",
    "OCENA",
    "STOPIEŃ",
    "INDEKS",
    "DYPLOM",
    "ABSOLWENT",
    "DOKTOR",
    "PROFESOR",
    "REKTOR",
    "DEKAN",
    "INSTYTUT",
    "WYZDZIAŁ",

    # ── City & buildings ─────────────────────────────────────────────
    "ULICA", "RYNEK", "TUNEL", "SUFIT", "HOTEL", "SKLEP", "TEATR",
    "BASEN",
    "URZĄD", "POCZTA",
    "RATUSZ",
    "ZAMEK",
    "WIEŻA",
    "MECZET",
    "ŚWIĄTYNIA",
    "KAPLICA",
    "SOBÓR",
    "SYNAGOGA",
    "KLASZTOR",
    "OPACTWO",
    "HOSPICJA",
    "SZPITAL",
    "PRZYCHODNIA",
    "APTEKA",
    "ARESZT",
    "POSTERUNEK",
    "STRAŻNICA",
    "LOKAL",
    "BISTRO",
    "KAWIARNIA",
    "RESTAURACJA",
    "TAWERNA",
    "KARCZMA",
    "OBERŻA",
    "MOTELEM",
    "HOSTEL",
    "SCHRONISKO",
    "CAMPING",
    "PLAŻA",
    "PARK",
    "PLAC",
    "SKWER",
    "RONDO",
    "ALEJKA",
    "ŚCIEŻKA",
    "DROGA",
    "SZOSA",
    "AUTOSTRADA",
    "BOCZNA",
    "ZAUŁEK",
    "PODWÓRZKO",
    "KLATKA",
    "WINDĄ",
    "SCHODY",
    "PODEST",
    "BALKON",
    "LOGGIA",
    "TARAS",
    "PATIO",
    "ATRIUM",
    "OGRÓD",
    "DZIEDZINIEC",

    # ── Transport ────────────────────────────────────────────────────
    "METRO", "ROWER", "STATEK", "ŁÓDKA", "SANIE", "SZYBA", "OPONA",
    "TARAS",
    "PILOT",
    "STEROWNIK",
    "PEDAŁY",
    "KIEROWNICA",
    "SKRZYNIA",
    "SILNIK",
    "UKŁAD",
    "ZAWÓR",
    "TŁOK",
    "KORBOWÓD",
    "WAŁEK",
    "OŚ",
    "KOŁO",
    "OPONA",
    "FELGA",
    "HAMULEC",
    "SPRZĘGŁO",
    "PRZEKŁADNIA",
    "BIEG",
    "WSTECZNY",
    "NAPĘD",
    "AKUMULATOR",
    "AKUMUL",
    "ALTERNATOR",
    "ROZRUSZNIK",
    "CHŁODNICA",
    "GRZEJNIK",
    "ZBIORNIK",
    "FILTR",
    "POMPA",
    "PRZEWÓD",
    "USZCZELKA",
    "ŚRUBA",
    "NAKRĘTKA",
    "PIERŚCIEŃ",
    "ŁOŻYSKO",
    "SWORZEŃ",
    "PODUSZKA",
    "RESOROWANIE",

    # ── Professions ──────────────────────────────────────────────────
    "PILOT", "AKTOR", "POETA", "MUZYK", "RYBAK",
    "KUCHARZ",
    "PIEKARZ",
    "KELNER",
    "BARMAN",
    "BUFETOWY",
    "HANDLARZ",
    "SPRZEDAWCA",
    "KASJER",
    "DORADCA",
    "AGENT",
    "BROKER",
    "ANALITYK",
    "AUDYTOR",
    "REWIDENT",
    "KONTROLER",
    "INSPEKTOR",
    "DETEKTYW",
    "ŚLEDCZY",
    "PROKURATOR",
    "SĘDZIA",
    "ADWOKAT",
    "NOTARIUSZ",
    "KOMORNIK",
    "URZĘDNIK",
    "URZĘDNICA",
    "SEKRETARZ",
    "ASYSTENT",
    "REFERENT",
    "SPECJALISTA",
    "EKSPERT",
    "KONSULTANT",
    "DYREKTOR",
    "PREZES",
    "ZARZĄD",
    "AKCJONARIUSZ",
    "PRACOWNIK",
    "PRACOWNICA",
    "ZATRUDNIONY",
    "FREELANCER",
    "WOLONTARIUSZ",
    "STAŻYSTA",
    "PRAKTYKANT",

    # ── Adjectives ───────────────────────────────────────────────────
    "DOBRY", "CICHY", "WOLNY", "STARY", "MŁODY", "SILNY", "SŁABY",
    "WAŻNY", "PEWNY", "GRUBY", "CHUDY", "NISKI", "DŁUGI", "WĄSKI",
    "JASNY", "ZIMNY", "MOKRY", "SUCHY", "CHORY", "PEŁNY", "PUSTY",
    "GĘSTY", "KAŻDY", "KTÓRY", "JEDEN", "DRUGI", "PIĄTY",
    "BIAŁY", "SZARY", "ZŁOTY", "ŻÓŁTY", "OSTRY", "RÓWNY",
    "STAŁY", "MIŁY",
    "NOWY",
    "CZYSTY",
    "BRUDNY",
    "ŚWIEŻY",
    "ZDROWY",
    "WESOŁY",
    "SMUTNY",
    "BOGATY",
    "BIEDNY",
    "WIELKI",
    "GŁOŚNY",
    "SZYBKI",
    "TRUDNY",
    "TWARDY",
    "MIĘKKI",
    "RZADKI",
    "PŁYNNY",
    "MARTWY",
    "SZEROKI",
    "KRZYWY",
    "GŁĘBOKI",
    "CIEMNY",
    "CIEPŁY",
    "GORĄCY",
    "DOBRA",
    "ZŁA",
    "PIĘKNA",
    "ŁADNA",
    "BRZYDKA",
    "GRUBA",
    "CHUDA",
    "WYSOKA",
    "NISKA",
    "DŁUGA",
    "KRÓTKA",
    "SZEROKA",
    "WĄSKA",
    "JASNA",
    "CIEMNA",
    "ZIMNA",
    "CIEPŁA",
    "GORĄCA",
    "MOKRA",
    "SUCHA",
    "CZYSTA",
    "BRUDNA",
    "ŚWIEŻA",
    "ZDROWA",
    "CHORA",
    "WESOŁA",
    "SMUTNA",
    "BOGATA",
    "BIEDNA",
    "SZYBKA",
    "WOLNA",
    "STARA",
    "MŁODA",
    "SILNA",
    "SŁABA",
    "WAŻNA",
    "MIŁA",
    "PEŁNA",
    "PUSTA",
    "RÓWNA",
    "OSTRA",
    "TWARDA",
    "MIĘKKA",
    "PŁYNNA",
    "STAŁA",
    "RZADKA",
    "GĘSTA",
    "GŁĘBOKA",
    "SZEROKA",
    "KRZYWA",
    "PŁYTKA",
    "DOBRYM",
    "ZŁYM",
    "PIĘKNYM",
    "ŁADNYM",
    "TRUDNYM",
    "ŁATWYM",
    "NUDNYM",
    "CIEKAWYM",
    "STRASZNYM",
    "PIĘKNY",
    "ŁADNY",
    "BRZYDKI",
    "NIEZŁY",
    "DOBRYIM",
    "WSPANIAŁY",
    "CUDOWNY",
    "NIESAMOWITY",
    "NIECODZIENNY",
    "ZWYCZAJNY",
    "NORMALNY",
    "TYPOWY",
    "WYJĄTKOWY",
    "UNIKALNY",
    "RZADKI",
    "POSPÓŁNY",
    "TANI",
    "DROGI",
    "BEZPŁATNY",
    "PŁATNY",
    "KOSZTOWNY",
    "CENNY",
    "WARTOŚCIOWY",
    "BEZWARTOŚCIOWY",
    "WAŻNY",
    "PILNY",
    "NAGŁY",
    "NATYCHMIASTOWY",
    "POWOLNY",
    "SZYBKI",
    "BŁYSKAWICZNY",
    "MOMENTALNY",
    "PRĘDKI",

    # ── Verbs ────────────────────────────────────────────────────────
    "ROBIĆ", "PISAĆ", "MÓWIĆ", "LUBIĆ", "LATAĆ", "UCZYĆ", "KUPIĆ",
    "LEŻEĆ", "WSTAĆ", "PÓJŚĆ", "WEJŚĆ", "IDZIE",
    "CHCIEĆ",
    "WIDZIEĆ",
    "SŁYSZEĆ",
    "CZYTAĆ",
    "WIEDZIEĆ",
    "MYŚLEĆ",
    "ROZUMIEĆ",
    "MIEĆ",
    "BYĆ",
    "MÓWIĆ",
    "DAĆ",
    "WZIĄĆ",
    "NIEŚĆ",
    "NOSIĆ",
    "TRZYMAĆ",
    "KŁAŚĆ",
    "STAWIAĆ",
    "SADZAĆ",
    "UKŁADAĆ",
    "PORZĄDKOWAĆ",
    "SPRZĄTAĆ",
    "CZYŚCIĆ",
    "MYĆ",
    "PRAĆ",
    "SUSZYĆ",
    "PRASOWAĆ",
    "SZYĆ",
    "CEROWAĆ",
    "DZIERGAĆ",
    "TKAĆ",
    "HAFTOWAĆ",
    "MALOWAĆ",
    "LAKIEROWAĆ",
    "BEJCOWAĆ",
    "PIŁOWAĆ",
    "SZLIFOWAĆ",
    "HEBLOWAĆ",
    "WIERCIĆ",
    "ŚCINAĆ",
    "RĄBAĆ",
    "PIŁOWAĆ",
    "SPAWAĆ",
    "LUTOWAĆ",
    "CIĄĆ",
    "PIŁOWAĆ",
    "WYCINAĆ",
    "FORMOWAĆ",
    "MODELOWAĆ",
    "ODLEWAĆ",
    "KUĆ",
    "WALCOWAĆ",
    "PRASOWAĆ",
    "TŁOCZYĆ",
    "GIĘĆ",
    "PROSTOWAĆ",
    "ZGINAĆ",
    "SKRĘCAĆ",
    "ROZCIĄGAĆ",
    "ŚCISKAĆ",
    "PRASOWAĆ",
    "SZLIFOWAĆ",
    "POLEROWAĆ",
    "GRAWEROWAĆ",
    "RZEŹBIĆ",
    "STRUGAĆ",
    "WIERCIĆ",
    "SZLIFOWAĆ",

    # ── Colors ───────────────────────────────────────────────────────
    "SZARY", "ZŁOTY", "ŻÓŁTY", "BIAŁY",
    "LILIA",
    "LILIOW",
    "ECRU",
    "KOŚCI",
    "PERGAMINU",
    "KREMÓW",
    "WANILIOW",
    "PIASKOW",
    "BEŻOW",
    "KAWOW",
    "BRĄZOW",
    "MAHONIOW",
    "SZKATUŁK",
    "CEGLASTY",
    "TERRAKOT",
    "MIEDZIAN",
    "BRĄZOW",
    "ZŁOCISTY",
    "OLIWKOW",
    "KHAKI",
    "OLIWN",
    "ZIELONY",
    "SZMARAGDOW",
    "MIĘTOW",
    "PISTACJOW",
    "LIMONKOW",
    "CYTRYNOW",
    "ŻÓŁTAW",
    "POMARAŃCZOW",
    "MORELOWY",
    "ŁOSOSIOW",
    "KORALOWY",
    "RÓŻOWY",
    "FUKSJA",
    "AMARANT",
    "WIŚNIOW",
    "BORDOWY",
    "BURACZKOW",
    "FIOLETOW",
    "LAWENDOW",
    "INDYGOW",
    "GRANATOW",
    "KOBALTOW",
    "BŁĘKITNY",
    "TURKUSOW",
    "MIĘTOW",
    "AQUA",
    "SZMARAG",
    "SZMARAGD",
    "CZARNY",
    "GRAFITOW",
    "ANTRACYT",
    "STALOWY",
    "SREBRNY",
    "PERŁOW",
    "PLATYNOW",
    "BIAŁY",
    "MLECZNY",
    "KREMOW",
    "ŚNIEŻNOBIAŁY",

    # ── Numbers & time ───────────────────────────────────────────────
    "JEDEN", "DRUGI", "PIĄTY", "OSIEM", "SZEŚĆ", "DZIEŃ", "ŚRODA",
    "PÓŹNO", "NIGDY", "TERAZ", "POTEM", "DAWNO", "EPOKA",
    "WIEKI",
    "SETNA",
    "TYSIĄC",
    "MILION",
    "MILIARD",
    "BILION",
    "ZERO",
    "PÓŁTORA",
    "KILKA",
    "WIELE",
    "DUŻO",
    "MAŁO",
    "TROCHĘ",
    "NIECO",
    "CAŁE",
    "PEŁNE",
    "POŁOWA",
    "ĆWIERĆ",
    "TRÓJKA",
    "CZWÓRKA",
    "PIĄTKA",
    "SZÓSTKA",
    "SIÓDEMKA",
    "ÓSEMKA",
    "DZIEWIĄTKA",
    "DZIESIĄTKA",
    "SETKA",
    "TYSIĄCZKA",
    "MILIONÓW",
    "MILIARDÓW",
    "BILIONÓW",
    "TRYLION",

    # ── Abstract & common words ──────────────────────────────────────
    "SŁOWO", "WYNIK", "POWÓD", "TREŚĆ", "MODEL", "KOSZT",
    "PRACA", "CECHA", "FORMA", "NORMA", "GNIEW", "WSTYD",
    "ŻYCIE", "ŚWIAT", "WIARA",
    "POKÓJ", "PISMO",
    "MYŚLI",
    "PLANY",
    "POMYSŁ",
    "POMYSŁY",
    "SKUTEK",
    "SKUTKI",
    "PRZYCZYNA",
    "POWODY",
    "WINA",
    "BŁĄD",
    "BŁĘDY",
    "SUKCES",
    "SUKCESY",
    "KLĘSKA",
    "KLĘSKI",
    "PROBLEM",
    "PROBLEMY",
    "PYTANIE",
    "PYTANIA",
    "ODPOWIEDŹ",
    "ODPOWIEDZI",
    "PRAWDA",
    "PRAWDY",
    "KŁAMSTWO",
    "KŁAMSTWA",
    "TAJEMNICA",
    "TAJEMNICE",
    "SEKRET",
    "SEKRETY",
    "PRAWO",
    "PRAWA",
    "REGUŁA",
    "REGUŁY",
    "ZASADA",
    "ZASADY",
    "WZÓR",
    "WZORY",
    "SYSTEM",
    "SYSTEMY",
    "METODA",
    "METODY",
    "SPOSÓB",
    "SPOSOBY",
    "WARTOŚĆ",
    "WARTOŚCI",
    "CENA",
    "CENY",
    "ZYSK",
    "ZYSKI",
    "STRATA",
    "STRATY",
    "DOCHÓD",
    "DOCHODY",
    "WYDATEK",
    "WYDATKI",
    "PRZYCHÓD",
    "PRZYCHODY",
    "BUDŻET",
    "BUDŻETY",
    "KONTO",
    "KONTA",
    "KREDYT",
    "KREDYTY",
    "DŁUG",
    "DŁUGI",
    "POŻYCZKA",
    "POŻYCZKI",
    "OPROCENTOWANIE",
    "RATA",
    "RATY",
    "PODATEK",
    "PODATKI",
    "OPŁATA",
    "OPŁATY",
    "FAKTURA",
    "FAKTURY",
    "RACHUNEK",
    "RACHUNKI",
    "PARAGON",
    "PARAGONY",
    "POKWIT",
    "UMOWA",
    "UMOWY",
    "KONTRAKT",
    "KONTRAKTY",
    "POROZUMIENIE",
    "UGODA",
    "UGODY",
    "WYROK",
    "WYROKI",
    "KARA",
    "KARY",
    "GRZYWNA",
    "GRZYWNY",
    "NAGRODA",
    "NAGRODY",
    "PREZENT",
    "PREZENTY",
    "GIFT",
    "GRATYFIKACJA",
    "PREMIA",
    "PREMIE",
    "DYWIDENDA",
    "DYWIDENDY",
    "UDZIAŁ",
    "UDZIAŁY",
    "AKCJA",
    "AKCJE",
    "LOKATA",
    "LOKATY",
    "INWESTYCJA",
    "INWESTYCJE",
    "PROJEKT",
    "PROJEKTY",
    "PLAN",
    "PLANY",
    "STRATEGIA",
    "STRATEGIE",
    "TAKTYKA",
    "TAKTYKI",
    "MISJA",
    "MISJE",
    "WIZJA",
    "WIZJE",
    "CEL",
    "CELE",
    "ZADANIE",
    "ZADANIA",
    "ETAP",
    "ETAPY",
    "FAZA",
    "FAZY",
    "KROK",
    "KROKI",
    "ZMIANY",
    "ZMIANA",
    "PROGRES",
    "PROGRESY",
    "POSTĘP",
    "POSTĘPY",
    "WYNIK",
    "WYNIKI",
    "EFEKT",
    "EFEKTY",
    "SKUTEK",
    "SKUTKI",
    "KONSEKWENCJA",
    "KONSEKWENCJE",
    "WYNIK",
    "WYNIKI",
    "WNIOSEK",
    "WNIOSKI",
    "RAPORT",
    "RAPORTY",
    "ANALIZA",
    "ANALIZY",
    "BADANIE",
    "BADANIA",
    "EKSPERYMENT",
    "EKSPERYMENTY",
    "OBSERWACJA",
    "OBSERWACJE",
    "ODKRYCIE",
    "ODKRYCIA",
    "WYNALAZEK",
    "WYNALAZKI",
    "INNOWACJA",
    "INNOWACJE",
    "TECHNOLOGIA",
    "TECHNOLOGIE",
    "NAUKA",
    "WIEDZA",
    "INFORMACJA",
    "INFORMACJE",
    "DANE",
    "FAKTY",
    "FAKT",
    "LICZBY",
    "LICZBA",
    "STATYSTYKA",
    "STATYSTYKI",
    "HISTOGRAM",
    "WYKRES",
    "WYKRESY",
    "DIAGRAM",
    "DIAGRAMY",
    "SCHEMAT",
    "SCHEMATY",
    "MAPA",
    "MAPY",

    # ── Emotions & psychology ───────────────────────────────────────
    "GNIEW", "WSTYD",
    "STRACH",
    "LĘKI",
    "FOBIA",
    "FOBIE",
    "PANIKA",
    "STRES",
    "FRUSTRACJA",
    "GNIEW",
    "WŚCIEKŁOŚĆ",
    "ZŁOŚĆ",
    "IRYTACJA",
    "ZDENERWOWANIE",
    "NIEPOKÓJ",
    "MELANCHOLIA",
    "DEPRESJA",
    "SMUTEK",
    "TĘSKNOTA",
    "NOSTALGIA",
    "ŻAŁOBA",
    "ŻAŁOŚĆ",
    "ROZPACZ",
    "ROZCZAROWANIE",
    "ROZCZAROWANA",
    "ZAWÓD",
    "NUDA",
    "APATIA",
    "OBOJĘTNOŚĆ",
    "SPOKÓJ",
    "CISZA",
    "OPANOWANIE",
    "RÓWNOWAGA",
    "HARMONIA",
    "SZCZĘŚCIE",
    "RADOŚĆ",
    "EUFORIA",
    "EKSTAZA",
    "ZACHWYT",
    "PODZIW",
    "MIŁOŚĆ",
    "TROSKA",
    "CZUŁOŚĆ",
    "WSPARCIE",
    "WSPÓŁCZUCIE",
    "EMPATIA",
    "ŻYCZLIWOŚĆ",
    "WDZIĘCZNOŚĆ",
    "POKORNOŚĆ",
    "POCHWAŁA",
    "DUMA",
    "AMBICJA",
    "DETERMINACJA",
    "MOTYWACJA",
    "ODWAGA",
    "ODWAGĘ",
    "ŚMIAŁOŚĆ",
    "BEZCZELNOŚĆ",
    "ZUCHWAŁOŚĆ",
    "PEWNOŚĆ",
    "WĄTPLIWOŚĆ",
    "NIEUFNOŚĆ",
    "ZAZDROŚĆ",
    "ZAWIŚĆ",
    "CHCIWOŚĆ",
    "SKĄPSTWO",
    "EGOIZM",
    "ALTRUIZM",
    "HUMANIZM",
    "IDEALIZM",
    "REALIZM",
    "OPTYMIZM",
    "PESYMIZM",
    "NIHILIZM",
    "CYNIZM",
    "SKEPTYCYZM",
    "AGNOSTYCYZM",
    "ATEIZM",
    "TEIZM",
    "DEIZM",
    "PANTEIZM",
    "ANIMIZM",
    "SZAMANIZM",
    "MISTYCYZM",
    "EZOTERYZM",
    "OKULTYZM",
    "MAGIA",
    "CZARY",
    "ZAKLĘCIA",
    "RYTUAŁ",
    "RYTUAŁY",
    "CEREMONIA",
    "CEREMONIE",
    "OBRZĘD",
    "OBRZĘDY",
    "TRADYCJA",
    "TRADYCJE",
    "ZWYCZAJ",
    "ZWYCZAJE",
    "OBYCZAJ",
    "OBYCZAJE",
    "KULTURA",
    "KULTURY",
    "CYWILIZACJA",
    "CYWILIZACJE",

    # ── Sports & games ──────────────────────────────────────────────
    "SPORT",
    "PIŁKA",
    "BRAMKA",
    "GOLA",
    "MECZ",
    "LIGA",
    "TURNIEJ",
    "MISTRZ",
    "TROFEUM",
    "MEDAL",
    "ZŁOTA",
    "SREBRNA",
    "BRĄZOWA",
    "BIEG",
    "SKOK",
    "RZUT",
    "TENIS",
    "SQUASH",
    "BADMINTON",
    "GOLF",
    "HOKEJ",
    "RUGBY",
    "KRYKIET",
    "BASEBALL",
    "SOFTBALL",
    "SIATKÓWKA",
    "KOSZYKÓWKA",
    "PIŁKA",
    "FUTBOL",
    "SZACHY",
    "WARCABY",
    "BRYDŻ",
    "POKER",
    "SOLITAIRE",
    "BINGO",
    "LOTERIA",
    "TOTALIZATOR",
    "RULETKA",
    "BLACKJACK",
    "DOMINO",

    # ── Health & medicine ───────────────────────────────────────────
    "LEKI",
    "TABLETKA",
    "KAPSUŁKA",
    "ZASTRZY",
    "SZCZEPIONKA",
    "ANTYBIOTYK",
    "WITAMINA",
    "SUPLEMENT",
    "DIETA",
    "KALORII",
    "BIAŁKO",
    "TŁUSZCZ",
    "WĘGLOWODAN",
    "BŁONNIK",
    "PROBIOTYK",
    "PREBIOTYK",
    "MINERAŁY",
    "MINERAŁ",
    "WAPŃ",
    "ŻELAZO",
    "MAGNEZ",
    "CYNK",
    "JOD",
    "SELEN",
    "CHROM",
    "MANGAN",
    "MIEDŹ",
    "KOBALT",
    "MOLIBDEN",
    "FLUOR",
    "SIARKA",
    "FOSFOR",
    "POTAS",
    "SÓD",
    "CHLOR",

    # ── Technology ──────────────────────────────────────────────────
    "KOMPUTER",
    "LAPTOP",
    "TABLET",
    "TELEFON",
    "SMARTFON",
    "ROBOT",
    "DRON",
    "SATELITA",
    "RAKIETA",
    "STATEK",
    "ŁAZIK",
    "SONDA",
    "TELESKOP",
    "MIKROSKOP",
    "LABORATORIUM",
    "REAKTOR",
    "TURBINA",
    "GENERATOR",
    "DYNAMO",
    "TRANSFORMATOR",
    "KONDENSATOR",
    "REZYSTOR",
    "TRANZYSTOR",
    "DIODA",
    "LED",
    "LCD",
    "SENSOR",
    "AKTUATOR",
    "SILNIK",
    "NAPĘD",
    "PRZEKŁADNIA",
    "BIEG",
    "WAŁEK",
    "ŁAP",
    "SPRZĘGŁO",
    "HAMULEC",
    "ZAWÓR",
    "POMPA",
    "SPRĘŻARKA",
    "WENTYLATOR",
    "CHŁODNICA",
    "GRZEJNIK",
    "WYMIENNIK",
    "FILTR",
    "SEPARATOR",
    "ZBIORNIK",
    "REAKTOR",
    "KOCIOŁ",
    "KOCIOŁ",
    "BOJLER",
    "PIEC",
    "KOMINEK",
    "KOMINKI",
    "OGRZEWANIE",
    "KLIMATYZACJA",
    "WENTYLACJA",
    "IZOLACJA",
    "USZCZELNIENIE",
    "HYDROIZOLACJA",
    "TERMOIZOLACJA",
    "AKUSTYCZNA",
    "DŹWIĘKOCHRONNY",

    # ── Music & arts ────────────────────────────────────────────────
    "MUZYKA",
    "PIOSENKA",
    "MELODIA",
    "RYTM",
    "TAKT",
    "NUTA",
    "AKORD",
    "SKALA",
    "TEMPO",
    "TONACJA",
    "FORTE",
    "PIANO",
    "SFORZANDO",
    "LEGATO",
    "STACCATO",
    "ARPEGGIO",
    "VIBRATO",
    "TREMOLO",
    "GLISSANDO",
    "PIZZICATO",
    "PORTAMENTO",
    "INTONACJA",
    "DYSONANS",
    "KONSONANS",
    "HARMONIA",
    "KONTRAPUNKT",
    "POLIFONIA",
    "MONODIA",
    "CHORAŁ",
    "GREGORIAŃSKI",
    "BAROKOWY",
    "KLASYCZNY",
    "ROMANTYCZNY",
    "MODERNISTYCZNY",
    "POSTMODERNISTYCZNY",
    "AWANGARDOWY",
    "EKSPERYMENTALNY",
    "MINIMALISTYCZNY",
    "NOISE",
    "AMBIENT",
    "ELEKTRONICZNY",
    "SYNTEZATOR",
    "SAMPLER",
    "SEKWENCER",
    "MIKSETA",
    "EFEKTY",
    "PEDAŁ",
    "WZMACNIACZ",
    "GŁOŚNIK",
    "MIKROFON",
    "SŁUCHAWKI",
    "NAGRANIE",
    "STUDIO",
    "KONSER",
    "RECITAL",
    "OPERA",
    "OPERETKA",
    "MUSICAL",
    "KABARET",
    "REWIA",
    "SPEKTAKL",
    "TEATR",
    "KINO",
    "FILM",
    "SERIAL",
    "ANIMACJA",
    "DOKUMENTALNY",
    "FABULARNY",
    "KRÓTKI",
    "DŁUGI",
    "PEŁNOMETRAŻOWY",
    "REŻYSER",
    "AKTOR",
    "AKTORKA",
    "SCENARZYSTA",
    "KAMERZYSTA",
    "MONTAŻYSTA",
    "DŹWIĘKOWIEC",
    "CHARAKTERYZATOR",
    "KOSTIUMOGRAF",
    "SCENOGRAF",
    "PRODUCENT",
    "DYSTRYBUTOR",
    "KINO",
    "SALA",
    "EKRAN",
    "PROJEKTOR",
    "FOTEL",
    "POPCORN",
    "COLA",
    "BILET",
    "REZERWACJA",
    "PREMIERA",
    "FESTIWAL",
    "NAGRODA",

    # ── More miscellaneous 5-letter words ───────────────────────────
    "STRÓJ", "SUKNO", "KOLOR",
    "OBIAD", "KOLACJA", "ŚNIADANIE",
    "ŁOPATA",
    "KILOF",
    "ŁOPAT",
    "SIEKIERA",
    "MOTYKA",
    "GRABIE",
    "WIADRO",
    "WIADER",
    "SZPADEL",
    "ŁOPATA",
    "TACZKA",
    "KOSIARKA",
    "NOŻYCZKI",
    "WIERTARKA",
    "SZLIFIERKA",
    "SPAWARKA",
    "LUTOWNICA",
    "POZIOMNICA",
    "PION",
    "MIARA",
    "KĄTOWNIK",
    "SUWMIARKA",
    "KLUCZ",
    "IMAK",
    "OBCĄŻKI",
    "CĘGI",
    "SZCZYPCE",
    "KOMBINERKI",
    "WKRĘTARKA",
    "WIERTŁO",
    "PIŁKA",
    "BRZESZCZOT",
    "HEBEL",
    "KIELNIA",
    "SZPACHLA",
    "PĘDZEL",
    "WAŁEK",
    "FARBA",
    "LAKIER",
    "KLEJ",
    "TAŚMA",
    "PAPIER",
    "KARTON",
    "TEKTURA",
    "TWORZYWO",
    "GUMA",
    "PLASTIK",
    "METAL",
    "DREWNO",
    "SZKŁO",
    "CERAMIKA",
    "PORCELANA",
    "KRYSZTAŁ",
    "ŻELAZO",
    "STAL",
    "ŻELIWO",
    "MOSIĄDZ",
    "BRĄZ",
    "MIEDŹ",
    "ALUMINIUM",
    "TYTAN",
    "NIKIEL",
    "CHROM",
    "WOLFRAM",
    "MOLIBDEN",
    "MAGNEZ",
    "CYNK",
    "CYNA",
    "OŁÓW",
    "PLATYNA",
    "ZŁOTO",
    "SREBRO",
    "RTĘĆ",
    "IRYD",
    "PALLAD",
    "RUTEN",
    "OSM",
    "RENAT",

    # More common 5-letter Polish words
    "CUKRU", "SŁONE", "PICER", "PIZZA", "ZUPER",
    "PIEKA", "PIEKĘ", "OWIES", "ORZECH", "ORZEK",
    "GROCH", "FASOL", "RYŻEM", "KASZE", "MAKOW",
    "WIEPRZOWINA",
    "CIELĘCINA",
    "BARANINA",
    "WIEPRZEK",
    "KARKÓWKA",
    "SCHAB",
    "ŻEBERKO",
    "BIODRÓWKA",
    "ŁOPATKA",
    "POLĘDWICA",
    "SZYNKA",
    "BEKON",
    "SALAMI",
    "KABANOS",
    "PARÓWKA",
    "MORTADELA",
    "PASZTET",
    "TERRINA",
    "GALARETA",
    "MIELONE",
    "KOTLETY",
    "STEKI",
    "BEFSZTYK",
    "ZRAZY",
    "ROLADY",
    "PIECZEŃ",
    "GULASZ",
    "RAGOUT",
    "POTRAWKA",
    "SZASZŁYK",
    "KEBAB",
    "GYROS",
    "BURGER",
    "KANAPKA",
    "SANWICK",
    "WRAP",
    "TORTILLA",
    "TACO",
    "BURRITO",
    "ENCHILADA",
    "QUESADILLA",
    "NACHOSY",
    "SALSA",
    "GUACAMOLE",
    "HUMMUS",
    "TAHINI",
    "BABA GHANOUSH",
    "TZATZIKI",
    "LABNEH",
    "FALAFEL",
    "SHAWARMA",
    "DÖNER",
    "PITA",
    "NAAN",
    "ROTI",
    "CHAPATI",
    "PARATHA",
    "INJERA",
    "LAVASH",
    "BAGUETTE",
    "BRIOCHE",
    "CROISSANT",
    "CIABATTA",
    "FOCACCIA",
    "GRISSINI",
    "MATZAH",
    "BAJGIEL",
    "MAKOWIEC",
    "SERNIK",
    "WIEDEŃSKI",
    "SZARLOTKA",
    "STRUDEL",
    "TIRAMISU",
    "PANNA COTTA",
    "CRÈME BRÛLÉE",
    "MOUSSE",
    "SUFLET",
    "MOUS",
    "BISZKOPT",
    "GENOISE",
    "DACQUOISE",
    "MADELEINE",
    "ECLAIR",
    "PROFITEROL",
    "PARIS-BREST",
    "SAINT-HONORÉ",
    "OPERA",
    "MILLE-FEUILLE",
    "TARTE TATIN",
    "CLAFOUTIS",
    "FLOGNARDE",
    "GALETTE",
    "CREPE",
    "BLINY",
    "NALEŚNIKI",
    "PAMPUCHY",
    "PĄCZKI",
    "DONUT",
    "MUFFIN",
    "BROWNIE",
    "COOKIE",
    "MACARONS",
    "FINANCIER",
    "CANELÉ",
    "KOUIGN",
    "AMMANN",
    "BABKA",
    "PIECZONY",
    "BABECZKA",
    "MAGDALENKA",
    "ROGALIK",
    "DROŻDŻÓWKA",
    "STRUCLA",
    "CHAŁKA",
    "CHLEB",
    "PUMPERNIKIEL",
    "ŻYTNI",
    "RAZOWY",
    "PSZENNY",
    "GRAHAM",
    "BEZGLUTENOWY",
    "KUKURYDZIANY",
    "RYŻOWY",
    "OWSIANY",
    "GRYCZANY",
    "ORKISZOWY",
    "AMARANTUSOWY",
    "KOMOSOWY",

    # ── More common Polish words (5 letters) ────────────────────────
    "ZAMEK", "KARTA", "TORBA", "ZEGAR", "MIAŁY", "PAŁAC",
    "STRÓJ", "PIACH", "PARKI", "SZYJE", "SZYJK", "TAŚMA",
    "BITWA", "BÓJKA", "WALKA", "BOJOW", "WOJSK", "ARMIA",
    "FLOTA", "SALWY", "STRZAŁ", "NABÓJ", "PISTOLET",
    "KARABIN", "STRZEL",
    "MIECZ", "TARCZA", "WŁÓCZNIA", "KOPIA", "HALABART",
    "STRZAŁY", "ŁUKI",
    "KASTETY",
    "SZPADA",
    "RAPIER",
    "FLORET",
    "SZTYLET",
    "KINDŻAŁ",
    "NOŻEM",
    "TOPORA",
    "TOPÓR",
    "BUZDYGAN",
    "MACZUGA",
    "CEPEM",
    "BICZA",
    "ŁAŃCUCH",
    "KŁODA",
    "PALE",
    "KATAPULTA",
    "BALISTĄ",
    "TARANEM",
    "DRABINA",
    "WIEŻA",
    "BASTIONEM",
    "MURY",
    "FOSA",
    "MOST",

    # Additional common 5-letter words
    "OGRÓD", "WIATA", "CHATA", "OBORA",
    "STAJN", "KURNI", "SZOPA", "WILLA",
    "DWOREK",
    "FOLWARKIEM",
    "GUMNO",
    "SITO", "BECZKA", "BECZE", "KADŹ",
    "BECZU", "KORCA",
    "WIADRO", "MIECH",
    "WIDŁY",
    "KOSĘ",
    "SIERP",
    "PŁUG",
    "BRONA",
    "SIEWNIK",
    "ŻNIWIARZ",
    "SNOPKI",
    "STOGI",
    "SIANA",
    "SŁOMY",
    "PLEWY",
    "OTRĘBY",
    "ZIARNO",
    "WOREK",
    "WORKI",
    "SKRZYNIA",
    "KUFAR",
    "KUFRY",
    "WALIZKA",
    "WALIZKI",
    "TORBY",
    "TORBA",
    "TECZKI",
    "AKTÓWKA",
    "PLECAK",
    "PLECAKI",
    "NESESER",
    "KOSMETYCZKA",
    "PORTFEL",
    "PORTFELE",
    "PORTMONETKA",
    "SASZETKA",
    "KIESA",
    "SAKIEWKA",
    "SAKWY",
    "JUKI",
    "BUKŁAK",

    # Polish geographic terms
    "DOLINY",
    "KOTLINA",
    "NIZINA",
    "WYŻYNA",
    "PŁASKOWYŻ",
    "GRZBIET",
    "PRZEŁĘCZ",
    "WĄWÓZ",
    "JASKINIA",
    "ŹRÓDŁO",
    "RZEKI",
    "JEZIORA",
    "BAGIEN",
    "MOCZARY",
    "STAW",
    "STAWY",
    "TORFY",
    "TORFOWISKO",
    "WYDMĄ",
    "WYDMY",
    "KLIFY",
    "WYBRZEŻE",
    "ZATOKA",
    "ZALEW",
    "PÓŁWYSEP",
    "PRZYLĄDEK",
    "WYSPA",
    "ARCHIPELAG",
    "ATOL",

    # Science terms
    "ATOM", "JĄDRO", "PROTON", "NEUTRON", "ELEKTRON",
    "KWARK", "LEPTON", "BOZON", "FERMI",
    "FOTON", "GRAWITON", "GLUON",
    "FALA", "CZĘSTOTLIWOŚĆ",
    "AMPLITUDA",
    "DŁUGOŚĆ",
    "PRĘDKOŚĆ",
    "PRZYSPIESZENIE",
    "SIŁA", "MASA", "GĘSTOŚĆ",
    "CIŚNIENIE", "TEMPERATURA",
    "ENERGIA", "PRACA",
    "MOC", "MOMENT", "IMPULS",
    "POLE", "POTENCJAŁ",
    "ŁADUNEK",
    "PRĄD", "NAPIĘCIE",
    "OPÓR", "INDUKCJA",
    "POJEMNOŚĆ",
    "REZONANS",
    "WIDMO",

    # Arts & literature
    "POWIEŚĆ",
    "NOWELA",
    "OPOWIADANIE",
    "BAJKA",
    "BAŚŃ",
    "LEGENDA",
    "MIT",
    "SAGA",
    "EPOS",
    "POEMAT",
    "WIERSZ",
    "SONET",
    "ODA",
    "ELEGIA",
    "BALLADA",
    "HYMN",
    "LIRYKA",
    "EPIKA",
    "DRAMAT",
    "TRAGEDIA",
    "KOMEDIA",
    "FARSA",
    "GROTESKA",
    "SATYRA",
    "PAMFLET",
    "ESEJ",
    "FELIETON",
    "REPORTAŻ",
    "WYWIAD",
    "RECENZJA",
    "KRYTYKA",
    "TEORIA",
    "INTERPRETACJA",
    "ANALIZA",
    "SYNTEZA",
    "PORÓWNANIE",
    "METAFORA",
    "METONIMIA",
    "ALEGORIA",
    "SYMBOL",
    "MOTYW",
    "TEMAT",
    "WĄTEK",
    "INTRYGA",
    "FABUŁA",
    "AKCJA",
    "NARRACJA",
    "DIALOG",
    "MONOLOG",
    "OPIS",
    "CHARAKTERYSTYKA",
    "PORTRET",
    "AUTOPORTRET",
    "NATURA",
    "PEJZAŻ",
    "PEJZAŻE",
    "MARTWĄ NATURĘ",
    "ABSTRAKCJA",
    "IMPRESJONIZM",
    "EKSPRESJONIZM",
    "KUBIZM",
    "SURREALIZM",
    "REALIZM",
    "NATURALIZM",
    "ROMANTYZM",
    "KLASYCYZM",
    "BAROK",
    "RENESANS",
    "GOTYK",
    "MODERNIZM",
    "POSTMODERNIZM",
    "AWANGARDA",
    "DADAIZM",
    "FUTURYZM",
    "KONSTRUKTYWIZM",
    "SUPREMATYZM",

    # Daily life words
    "PRACA", "DOM", "SKLEP", "DROGA", "ULICA",
    "SZKOŁA", "KOŚCIÓŁ", "PARK", "LAS", "POLA",
    "OGRÓD", "MIASTO", "WIEŚ", "KRAJ",
    "ŚWIAT",
    "DZIEŃ", "NOC", "RANEK", "WIECZÓR",
    "TYDZIEŃ", "MIESIĄC", "ROK",
    "CHWILA", "MOMENT",
    "CZAS", "TERAZ", "POTEM",
    "ZAWSZE", "NIGDY", "CZĘSTO",
    "RZADKO", "ZWYKLE", "CZASEM",
    "BARDZO", "TROCHĘ", "DUŻO",
    "MAŁO", "CAŁKOWICIE",
    "PRAWIE", "RACZEJ", "CHYBA",
    "MOŻE", "NA PEWNO", "OCZYWIŚCIE",
    "NIESTETY", "NA SZCZĘŚCIE",
    "TUTAJ", "TAM", "GDZIE",
    "SKĄD", "DOKĄD", "KIEDY",
    "DLACZEGO", "JAK",
    "KTO", "CO", "KTÓRY",
    "JAKIŚ", "ŻADEN", "KAŻDY",
    "TAKI", "TAKA", "TAKIE",
    "INNY", "INNA", "INNE",
    "CAŁY", "CAŁA", "CAŁE",
    "POŁOWA", "JEDNA TRZECIA",
    "TAK", "NIE", "ALE",
    "I", "LUB", "ALBO",
    "BO", "GDYŻ", "PONIEWAŻ",
    "JEŚLI", "GDYBY", "ŻEBY",
    "CHOCIAŻ", "MIMO",
    "JEDNAK", "ALE", "LECZ",
    "WIĘC", "ZATEM", "DLATEGO",
    "POTEM", "NASTĘPNIE", "WCZEŚNIEJ",
    "NA", "W", "DO", "Z", "ZE",
    "O", "PO", "PRZEZ",
    "DLA", "BEZ", "U",
    "NAD", "POD", "PRZY",
    "PRZED", "PO", "ZA",
    "OD", "DO", "MIĘDZY",

    # Polish flora
    "BRZOZA", "TOPOLA", "OSIKA",
    "WIERZBA", "OLCHA", "LIPA",
    "KLON", "JESION", "WIĄZ",
    "DĄBEK", "BUKA", "GRABA",
    "JODŁA", "ŚWIERK", "MODRZEW",
    "CISA", "SOSNA",
    "JARZĄB", "GŁÓG", "TARNINA",
    "KALINA", "BEZ",
    "LESZCZYNA", "BERBERYS",
    "TRZMIELINA",
    "SUCHODRZEW",
    "CZEREMCHA",
    "DZIKI BEZ",
    "JEŻYNA", "MALINA",
    "BORÓWKA",
    "ŻURAWINA",
    "BAGNO",
    "PORZECZKA",
    "AGREST",
    "WINOROŚL",
    "BLUSZCZ",
    "RDEST",
    "SKRZYP",
    "PAPROĆ",
    "MECH",
    "POROST",
    "GRZYB",
    "PIECZARKA",
    "BOROWIK",
    "KOZAK",
    "MAŚLAK",
    "KURKA",
    "PIEPRZNIK",
    "RYDZ",
    "SMARDZ",
    "TRUFLA",
    "MLECZAJ",
    "GOŁĄBEK",
    "KANIA",
    "KOLCZATKA",
    "MUCHOMOR",
    "BEDŁKA",
    "MAŚLANECZKA",

    # More adjective forms
    "GORZKI", "SŁODKI", "KWAŚNY", "SŁONY", "PIKANTNY",
    "ŁAGODNY", "OSTRY", "MDŁY", "TŁUSTY", "CHRUPIĄCY",
    "MIĘKKI", "TWARDY", "SPRĘŻYSTY", "ELASTYCZNY",
    "KRUCHY", "SYPKI", "KLEISTY", "LEPKI", "ŚLIZGI",
    "SZORSTKI", "GŁADKI", "AKSAMITNY",
    "BŁYSZCZĄCY", "MATOWY", "PRZEZROCZYSTY",
    "OPAKOWY", "NIEPRZEZROCZYSTY",
    "JASKRAWY", "BLADY", "MATOWY",
    "NASYCONY", "WYBLAKŁY", "ZGNIŁY",
    "ŚWIEŻY", "NIEŚWIEŻY", "ZEPSUTY",
    "SPLEŚNIAŁY", "ZBUTWIAŁY", "ZGNIŁY",
    "KWAŚNY", "OCTOWY", "FERMENTOWANY",
    "SUROWY", "GOTOWANY", "USMAŻONY",
    "PIECZONY", "GRILLOWANY", "WĘDZONY",
    "SOLONY", "MARYNOWANY", "KONSERWOWANY",
    "MROŻONY", "ROZMROŻONY", "ODGRZANY",

    # Verbs - additional forms
    "CHODZIĆ", "BIEGAĆ", "SKAKAĆ",
    "PŁYWAĆ", "NURKOWAĆ", "SURFOWAĆ",
    "JEŹDZIĆ", "LATAĆ", "FRUWAĆ",
    "SPACEROWAĆ", "WĘDROWAĆ", "MASZEROWAĆ",
    "TAŃCZYĆ", "ŚPIEWAĆ", "GRAĆ",
    "SŁUCHAĆ", "OGLĄDAĆ", "CZYTAĆ",
    "PISAĆ", "RYSOWAĆ", "MALOWAĆ",
    "RZEŹBIĆ", "FOTOGRAFOWAĆ", "FILMOWAĆ",
    "GOTOWAĆ", "PIEC", "SMAŻYĆ",
    "DUSIĆ", "GOTOWAĆ", "PAROWAĆ",
    "MARYNOWAĆ", "SOLIĆ", "WĘDZIĆ",
    "FERMENTOWAĆ", "KISIĆ", "KISZENIE",
    "SADZIĆ", "SIAĆ", "ZBIERAĆ",
    "PRZYCINAĆ", "PIELĘGNOWAĆ", "NAWOZIĆ",
    "PODLEWAĆ", "OPRYSKIWAĆ",

    # Polish idioms & common expressions components
    "SERCE", "DUSZA", "GŁOWA", "NOGI", "RĘCE",
    "OCZY", "USZY", "USTA", "NOS", "BRWI",
    "WŁOSY", "ZĘBY", "JĘZYK", "GARDŁO",
    "PIERSI", "PLECY", "BRZUCH", "PUPA",
    "RAMIONA", "ŁOKCIE", "DŁONIE",
    "KOLANA", "ŁYDKI", "STOPY",
    "PALCE", "PAZNOKCIE",

    # Additional vocabulary
    "DZIURA", "OTWÓR", "SZCZELINA",
    "SZPARA", "RYSA", "PĘKNIĘCIE",
    "ZŁAMANIE", "SKRZYWIENIE",
    "UGIĘCIE", "WYGIĘCIE", "SKRĘCENIE",
    "SKURCZ", "ROZCIĄGNIĘCIE",
    "STŁUCZENIE", "OBTARCIE", "SKALECZENIE",
    "RANA", "RANY", "URAZ",
    "BLIZNA", "OPARZENIE", "ODMROŻENIE",
    "ALERGIA", "REAKCJA", "OBRZĘK",
    "WYSYPKA", "POKRZYWKA", "RUMIEŃ",
    "SINIAK", "KRWIAK",
    "ROPIEŃ", "WRZÓD", "PRYSZCZ",
    "BRODAWKA", "KURZAJKA",
    "ODCISK", "NAGNIOTEK",
    "MODZELE",
    "WYWICHNIĘCIE", "SKRĘCENIE",
    "NADERWANIE", "ZERWANIE",
    "ZŁAMANIE", "PĘKNIĘCIE",
    "PRZEMIESZCZENIE", "DYSLOKACJA",

    # Common Polish 5-letter words frequently used
    "AUTOR", "BARWY", "CELEM", "DATOM", "EFEKT",
    "FAKTY", "GLEBA", "HASŁO", "IMION", "JAWNY",
    "KALKA", "LIPIE", "ŁATWO", "MANKO", "NUMER",
    "OBRÓT", "POLKA", "RABAT", "SABAT", "TABOR",
    "UGODA", "VADUZ", "WYRÓB", "ZIMNO",

    # Additional 5-letter words
    "ABARY", "ABBOT", "ABDYK", "ABECADŁO",
    "ABSTR",
    "ACETON", "ACHAĆ",
    "ADAGIO", "ADAJĘ", "ADAPTA",
    "ADEPT", "AFERA", "AGAWA",
    "AGENTEM", "AGENT", "AGORA",
    "AGRAM", "AGRES",
    "AGREST", "AGRESJA",
    "AKTÓW",
    "AKTYW",
    "AKWARIUM",
    "AKWEN",
    "ALARM",
    "ALEJA",
    "ALOES",
    "ALPAK",
    "ALPEJ",
    "AMEBA",
    "AMPER",
    "AMPLA", "AMPLA",
    "ANEKS",
    "ANIOŁ",
    "ANODA",
    "AORTA",
    "APEKS", "APELU",
    "APELE",
    "APELT",
    "APETYT",
    "ARIEL",
    "ARKAD",
    "AROMA", "AROMAT",
    "ARSEN",
    "ARTES",
    "ARTUR",
    "ARYJA",
    "ASORT",
    "ASPIK",
    "ATEST",
    "ATOLI",
    "AUDYT",
    "AUGUR",
    "AURAI",
    "AUROR",
    "AUTOS",
    "AWANS",
    "AWERS",
    "AZJAT",
    "AZOTE",
    "AZURY",
    "BABCI",
    "BAGAŻ",
    "BAGAZ",
    "BAJKA",
    "BAKAL",
    "BAKUN",
    "BALSA",
    "BALET",
    "BALON",
    "BALSAM",
    "BANAŁ",
    "BANDA",
    "BANEK",
    "BARWNIK",
    "BASEM",
    "BATOG",
    "BAWÓŁ",
    "BAZYL",
    "BEKAS",
    "BERTA",
    "BEZEK",
    "BIAŁO",
    "BIGOS",
    "BIJAK",
    "BILET",
    "BILGI",
    "BIMBER",
    "BITKA",
    "BIZON",
    "BLACHA", "BLASKU",
    "BLASK",
    "BŁAHA",
    "BŁĄKA",
    "BLOND",
    "BŁOTO",
    "BOCIAN",
    "BOGIEM",
    "BOLOR",
    "BOLEC",
    "BOSKI",
    "BRAMA",
    "BRAWA",
    "BREWY",
    "BROŃ",
    "BRULION",
    "BRWIĘ",
    "BRYŁY",
    "BRYŁA",
    "BUFOR",
    "BULAJ",
    "BURAK",
    "BURTA",
    "BUSOLA",
    "BYKOW",
    "BZDUR",
    "CAFFE",
    "CAFET",
    "CEBER",
    "CHĘCI",
    "CHĘTK",
    "CHŁÓD",
    "CHOCIAŻ",
    "CHRAM",
    "CHREM",
    "CHRUP",
    "CHRZĄ",
    "CHUDK",
    "CIAŁO",
    "CIĄŻA",
    "CIOSK",
    "CISAWY",
    "COFAĆ",
    "COFNĄĆ",
    "CÓRCE",
    "CUDZY",
    "CUGLE",
    "CZAPLA",
    "CZAPL",
    "CZEKAĆ",
    "CZEPEK",
    "CZERŃ",
    "CZERW",
    "CHYLIĆ",
    "CZÓŁNO",
    "CZUPURNY",
    "CZYNIA",
    "CZYNEM",
    "DANIE", "DANIE",
    "DĄSEM",
    "DEKOR",
    "DENGA",
    "DENAT",
    "DESKI",
    "DESKA",
    "DETAL",
    "DIETA",
    "DŁUTO",
    "DOBRE",
    "DOBYĆ",
    "DODAT",
    "DODEK",
    "DOJŚCIE",
    "DOLEK",
    "DOMEK",
    "DONIK",
    "DOPŁYW",
    "DORYW",
    "DOWÓD",
    "DOŻYNKI",
    "DRAKA",
    "DRWAL",
    "DRŻEĆ",
    "DUDNIENIE",
    "DUKAT",
    "DUMNY",
    "DZIEŃ",
    "DŻDŻYSTY",
    "ECHEM",
    "EGIDA",
    "EMALIA",
    "ENAMEL",
    "EPLOG",
    "ERGO",
    "EROZY",
    "ETANOL",
    "ETUI",
    "FAJKA",
    "FALKA",
    "FALOM",
    "FAMIL",
    "FANKA",
    "FANFAR",
    "FARBK",
    "FARTU",
    "FARYZU",
    "FASADA",
    "FATAŁ",
    "FATYK",
    "FEBRĄ",
    "FESTA",
    "FETAL",
    "FETOW",
    "FICYK",
    "FIKUS",
    "FILTR",
    "FIOLEK",
    "FLAIR",
    "FLAKON",
    "FLARA",
    "FLĄDER",
    "FLIRT",
    "FLASK",
    "FOBIA",
    "FOTON",
    "FRAKTU",
    "FROTER",
    "FUJARKA",
    "FULAR",
    "GABINET",
    "GALOP",
    "GAMMA",
    "GANG",
    "GAWĘDA",
    "GAWRON",
    "GAZET",
    "GEJZER",
    "GIEŁDA",
    "GLANS",
    "GLAZUR",
    "GŁUPIE",
    "GODŁO",
    "GOLEN",
    "GORSET",
    "GOTYK",
    "GRACA",
    "GRACJA",
    "GRANAT",
    "GRANDA",
    "GRASZ",
    "GREJĄ",
    "GRZBIT",
    "GZYMS",
    "HAŁAS",
    "HAŁAŚ",
    "HAMAK",
    "HARFA",
    "HERBO",
    "HERB",
    "HORDA",
    "HUCIA",
    "IDYLLA",
    "IKONA",
    "IKSEM",
    "IMPAS",
    "INDYK",
    "IPSEM",
    "IRONIA",
    "IRYS",
    "JABŁEK",
    "JAGODA",
    "JAMNIK",
    "JASION",
    "JAWOR",
    "JĘDZA",
    "JEDZA",
    "JELONEK",
    "JEMIOŁA",
    "JENOT",
    "JODYNA",
    "JUHAS",
    "JUNAK",
    "JUTRO",
    "KADŁUB",
    "KAJET",
    "KAJUTA",
    "KALKUL",
    "KAMYK",
    "KANAŁ",
    "KAPTUR",
    "KĄPIEL",
    "KARB",
    "KARKÓWKA",
    "KARŁEM",
    "KARZEŁ",
    "KASJER",
    "KATAR",
    "KAWIOR",
    "KĘDZIE",
    "KIEDY",
    "KIELICH",
    "KIEŁB",
    "KLAUN",
    "KLEJEM",
    "KLEPKI",
    "KLEPKA",
    "KLIMAT",
    "KŁOS",
    "KŁUSA",
    "KŁUSOW",
    "KODEKS",
    "KOLBA",
    "KOLEC",
    "KOLIA",
    "KOLIĘ",
    "KOMIK",
    "KOMOS",
    "KOPUŁA",
    "KOPIEC",
    "KOPYTA",
    "KOPYT",
    "KORAL",
    "KORDEK",
    "KORDYL",
    "KORNET",
    "KORUPCJA",
    "KORONA",
    "KORZEŃ",
    "KOTEK",
    "KOTEW",
    "KOZIOŁ",
    "KRĄG",
    "KREDENS",
    "KREDA",
    "KREDO",
    "KREMEM",
    "KRETS",
    "KREWNA",
    "KREWNY",
    "KROBLA",
    "KRONIK",
    "KRÓTKO",
    "KRUCHE",
    "KRUCHO",
    "KRYPTA",
    "KRZYŻ",
    "KRZTUS",
    "KUJON",
    "KUKURYDZA",
    "KULISY",
    "KULTURA",
    "KUNA",
    "KUPIEC",
    "KURIA",
    "KURIER",
    "KURORT",
    "KWORUM",
    "LARUM",
    "LASKA",
    "LATARNIA",
    "ŁAWICA",
    "LAWKA",
    "ŁAWKA",
    "LEDWO",
    "LEMUR",
    "LENIW",
    "LEPIK",
    "LETNI",
    "LINIA",
    "LIPCOWY",
    "LISY",
    "LIŚCIE",
    "LITERA",
    "LOCH",
    "LOKAL",
    "LOLLY",
    "LOTKA",
    "LOTOS",
    "LUDZKI",
    "LUFER",
    "LUPINA",
    "LUSTERN",
    "ŁACHMAN",
    "ŁACHA",
    "ŁAGOD",
    "ŁATKA",
    "ŁOBUZIE",
    "ŁÓDŹ",
    "ŁOJEK",
    "ŁOPIAN",
    "ŁOPOTEM",
    "ŁOTRY",
    "ŁOTR",
    "ŁOWICA",
    "ŁOWIEC",
    "ŁÓŻECZKO",
    "ŁUBEK",
    "ŁUSZCZYCA",
    "MACHIN",
    "MAFIA",
    "MAGINOT",
    "MAJDAN",
    "MAJON",
    "MAKIEM",
    "MAKOLĄ",
    "MAŁPIO",
    "MANGUST",
    "MANIA",
    "MANIAK",
    "MANTRA",
    "MARGA",
    "MAROT",
    "MARUN",
    "MARYJA",
    "MAWIN",
    "MAZAJ",
    "MEGAFON",
    "MELEAG",
    "MENAŻ",
    "MERCE",
    "METAN",
    "MOTYW",
    "MRUCZEC",
    "MUNDUR",
    "MUREK",
    "MUZYK",
    "NACISK",
    "NACZYN",
    "NAGŁÓWEK",
    "NAJAZD",
    "NAJEM",
    "NALEPIAĆ",
    "NAPIS",
    "NAREW",
    "NARCYZ",
    "NARZĘDZIE",
    "NARZĄD",
    "NAŚCIE",
    "NAWET",
    "NAWÓZ",
    "NERW",
    "NIEMAL",
    "NIEMY",
    "NISKO",
    "NITKA",
    "NÓŻKA",
    "NUMER",
    "NURTEM",
    "NURT",
    "OBELGA",
    "OBITYM",
    "OBÓZ",
    "OBRONA",
    "OBWÓD",
    "OCTAN",
    "OCZKO",
    "OFERTA",
    "OGNISK",
    "OLEJEK",
    "OLEJ",
    "OŁTARZ",
    "OMLET",
    "OMYLIĆ",
    "OPŁATA",
    "OPRAWKA",
    "ORYKS",
    "ORZECH",
    "ORZESZEK",
    "OSTRYGA",
    "OSZCZEP",
    "OWSIANKA",
    "OWAD",
    "PACEŁ",
    "PACZKA",
    "PAGÓREK",
    "PALIA",
    "PALMA",
    "PANDEMIA",
    "PANICZ",
    "PANNA",
    "PAPIER",
    "PAPUGA",
    "PARCELA",
    "PARZE",
    "PASJA",
    "PAWIA",
    "PAWILON",
    "PEDAGO",
    "PĘDZEL",
    "PEKAES",
    "PELIKAN",
    "PERŁA",
    "PERUK",
    "PĘCZEK",
    "PĘKNIĘCIE",
    "PIKAP",
    "PIKNIK",
    "PINAKL",
    "PIWKO",
    "PIZGA",
    "PLACEK",
    "PLAMA",
    "PLATAN",
    "PLECAK",
    "PLENERY",
    "PŁUG",
    "PODROBY",
    "POGRĄ",
    "POJAZD",
    "POKRYW",
    "POLANO",
    "POMPA",
    "POPĘD",
    "PORTAL",
    "POSADA",
    "POSAG",
    "POŚCIG",
    "POWIE",
    "POZEW",
    "PRÓBKA",
    "PROCH",
    "PRODUKT",
    "PROFIL",
    "PROTON",
    "PRÓŻNY",
    "PRZEPIÓRKA",
    "PRZESZ",
    "PRZODU",
    "PRZYJĄĆ",
    "PSOTA",
    "PSTRYK",
    "PTASIE",
    "PUCHAR",
    "PUCEK",
    "PULPIT",
    "PUŁAP",
    "PUŁAPKA",
    "PUNKT",
    "PUPILA",
    "PUSTAK",
    "PUSZKA",
    "RYWAL",
    "RZEMIEŃ",
    "RZUCAĆ",
    "SADZIĆ",
    "SAHEL",
    "SAKWA",
    "SALON",
    "SAPAĆ",
    "SAPER",
    "SARNA",
    "SATELITA",
    "SATYRA",
    "SCHODY",
    "SĘDZIA",
    "SENAT",
    "SERIA",
    "SĘP",
    "SIERPIEŃ",
    "SIEĆ",
    "SKAŁA",
    "SKAPIEC",
    "SKLEP",
    "SKONAĆ",
    "SKÓRZANY",
    "SKRATEK",
    "SKRÓT",
    "SKUNKS",
    "SŁOIK",
    "SŁONA",
    "SŁONINĘ",
    "SŁONINY",
    "SŁUPEK",
    "SMOLIĆ",
    "SMUK",
    "SNUĆ",
    "SOBOTA",
    "SOLANKA",
    "SOLIST",
    "SOPEL",
    "SOWY",
    "SPODEK",
    "SPODNIA",
    "SPOIWO",
    "SPONTAN",
    "SPRZĘŻENIE",
    "SPUST",
    "ŚRODEK",
    "SSAK",
    "STADO",
    "STĘCHŁE",
    "STOCZNIA",
    "STOK",
    "STOPY",
    "STREFA",
    "STRUŚ",
    "STUK",
    "STUSEK",
    "SUBSTANCJA",
    "SUPEŁ",
    "SZABLA",
    "SZACHISTA",
    "SZACHY",
    "SZALET",
    "SZANSA",
    "SZARAŃCZA",
    "SZATA",
    "SZELKI",
    "SZPIEG",
    "SZPILK",
    "SZPITALEM",
    "SZRON",
    "SZTUCZK",
    "SZTURM",
    "SZWAGIER",
    "SZYBKO",
    "SZYK",
    "ŚCIEK",
    "ŚLAD",
    "ŚLINA",
    "ŚPIWOREK",
    "ŚRUBA",
    "ŚRODA",
    "ŚWIADEK",
    "TARCIE",
    "TARCZA",
    "TARGOWISKO",
    "TARTE",
    "TARTY",
    "TĘSKNOTA",
    "TIARA",
    "TLENU",
    "TLEN",
    "TONIK",
    "TORPEDA",
    "TOWAR",
    "TRĄBKA",
    "TRENER",
    "TRÓJNÓG",
    "TRUNEK",
    "TRWOGA",
    "TRYB",
    "TRZASK",
    "TRZASK",
    "TUBA",
    "TULEJA",
    "TUMAN",
    "TURBAN",
    "TURBINA",
    "TYGIEL",
    "TYNK",
    "UBÓJ",
    "ULOTKA",
    "UPUST",
    "URNA",
    "UWAGA",
    "UZDOLNIONY",
    "WABIK",
    "WACHLARZ",
    "WALET",
    "WAPIEŃ",
    "WARTOWNIK",
    "WĄWÓZ",
    "WIANKI",
    "WIANEK",
    "WICHER",
    "WIDOK",
    "WIĘŹ",
    "WIEZA",
    "WIKLINA",
    "WIRUS",
    "WITRAŻ",
    "WNĘTRZE",
    "WNĘKA",
    "WÓDZ",
    "WROGI",
    "WRZOS",
    "WYBUCH",
    "WYCINEK",
    "WYJŚCIE",
    "WYKRÓJ",
    "WYMROK",
    "WYMIAR",
    "WYRAZ",
    "WYSKOK",
    "WZROST",
    "ZABOBON",
    "ZACIĄG",
    "ZACISZE",
    "ZAGROD",
    "ZAKRYW",
    "ZANIK",
    "ZAPIASEK",
    "ZAPINKA",
    "ZAPŁON",
    "ZARÓŻOW",
    "ZAROST",
    "ZASTAWA",
    "ZATYK",
    "ZAULEK",
    "ZAWIAS",
    "ZAWILEC",
    "ZBIEG",
    "ZDROBNIEŃ",
    "ZERWA",
    "ZIEMNIAK",
    "ZIOLK",
    "ZIOŁA",
    "ZIÓŁ",
    "ZMORY",
    "ŻOŁĄDŹ",
    "ŻÓŁW",
    "ŻUCZEK",
    "ŹDŹBŁO",
    "ZDOBYCZ",
    "ZNAK",
    "ZORZA",
    "ZRYW",
    "ŻYWICA",
    "ZAGON",
    "ZAGRODA",
    "ZAKĄTEK",
    "ZAKONNICA",
    "ZAMIEĆ",
    "ZARAZA",
    "ZASIEK",
    "ZASUWA",
    "ZAŚCIANEK",
    "ŻBIK",
    "ZDRÓJ",
    "ZIELE",
    "ZIELNIK",
    "ZIEMNIAK",
    "ZIMNICA",
    "ZOBACZONE",
    "ZOBACZYĆ",
    "ZROST",
    "ZRYW",
    "ZUPA",
    "ZUZEL",
    "ŻYRANT",
    "BŁAWAT",
    "CHABER",
    "MACZEK",
    "MACZKA",
    "JASKIER",
    "KACZAN",
    "KACZE",
    "ŁOPIAN",
    "POWÓJ",
    "POKRZYWA",
    "KONOPIE",
    "LNICZA",
    "TOBOŁEK",
    "FIOŁEK",
    "FIOLEK",
    "GĘSIÓWKA",
    "SZARŁAT",
    "ZIMOTRWAŁ",
    "MIETLICA",
    "WYCZYNIEC",
    "WIECHLINA",
    "GRZEBIENNICA",
    "KOSTRZEWA",
    "STOKŁOSA",
    "KUPKÓWKA",
    "TOMKA",
    "TYMOTKA",
    "WIECHLIN",
    "TRAW",
    "OLSZYNA",
    "ŁOZINA",
    "ROKITA",
    "KRUSZYNA",
    "SZAKŁAK",
    "SUCHODRZEW",
    "ŚNIEGULICZKA",
    "DERENIE",
    "DEREŃ",
    "BRZEKLICA",
    "TRZMIELINA",
    "WICIOKRZEW",
    "RDESTOWIEC",
    "NIECIERPEK",
    "NAWŁOĆ",
    "BARSZCZOWNICA",
    "SKRZYP",
    "WIDŁAK",
    "PODBIAŁ",
    "BABKA",
    "BLUSZCZ",
    "CHMIEL",
    "GWIAZDNICA",

    # Deliberate additions of many 5-letter words
    "RACJE", "RAJDY", "RAKIETA", "RAMPA", "RANCE",
    "RANEK", "RANIE", "RANKIEM", "RANNYCH", "RAPTEM",
    "RATAN", "RATOWNIK", "RATUSZ", "RAVEN", "RAZEM",
    "RENCE", "RYNEK", "RZEPAK", "RZUTEK",
    "RZEPA", "RZEPKA", "RZODKIEW",
    "RYCERZ", "RYGOR", "RYNNA", "RYSIK",
    "SADZA", "SADZAWKA", "SAFIAN", "SAGAN",
    "SALDO", "SAŁATA", "SALTO",
    "SAMBO", "SAMICA", "SAMIEC",
    "SANKI", "SAPNĄĆ", "SATYNA",
    "SCENA", "SEDES", "SEJM",
    "SEZON", "SIANO", "SIATKA",
    "SIELANKA", "SIŁOWNIA",
    "SINUS", "SKARGA", "SKARB",
    "SKAZA", "SKIBA", "SKIER",
    "SKIPASS", "SKOS", "SKROBIA",
    "SKROMNY", "SKRUCHA",
    "SKRZEK", "SKRZEP",
    "SMAGA", "SMAK", "SMOŁĘ",
    "SOBEK", "SOBOL", "SOKOLI",
    "SOLENIZANT",
    "SONATA", "SONDA",
    "SOWITY", "SPALENIE",
    "SPAZA", "SPICHLERZ",
    "SPŁAW", "SPLATA",
    "SPŁAW", "SPLOTY",
    "SPONKA", "SPORYSZ",
    "SPRAWA", "SPUST",
    "SROKATA", "SROKA",
    "STEMPEL", "STĘPKA",
    "STĘPOR", "STODOŁA",
    "STÓG", "STRACH",
    "STRAGAN", "STRAW",
    "STREFA", "STRES",
    "STRUGA", "STRUG",
    "STRZELA", "STRZEL",
    "STUDZIENKA",
    "SUKMAN", "SUKNIA",
    "SUTER", "SUTKA",
    "SUWAK", "SYMBOL",
    "SYPKI", "SYPNĄĆ",
    "SYTOŚĆ", "SYTUACJA",
    "SZABER", "SZACUNEK",
    "SZACHY", "SZAFRA",
    "SZALIK", "SZAMAN",
    "SZANSA", "SZARUG",
    "SZAST", "SZATAN",
    "SZATYN", "SZCZAW",
    "SZKOŁA", "SZPAK",
    "SZROT", "SZTAB",
    "SZTUCZNY", "SZUFEL",
    "SZWED", "SZYBA",
    "SZYLD", "SZYMPANS",

    # Yet more 5-letter words
    "TABAK", "TABOL", "TABUN",
    "TAFLA", "TAJGA", "TAJNY",
    "TALAR", "TALAR", "TALIA",
    "TAMKA", "TAMPON", "TANIEC",
    "TAPIR", "TARAN",
    "TAUNT", "TCHÓRZ",
    "TENIS", "TENOR",
    "TERCET", "TERLICA",
    "TERMOS", "TIARA",
    "TŁOK", "TŁUMACZ",
    "TŁUMOK", "TOBOL",
    "TOKAN", "TOLEJ",
    "TOPÓR", "TORBIEL",
    "TORAN", "TOUCAN",
    "TRAKT", "TRAKTAT",
    "TRAWNIK", "TRAWNIK",
    "TREFNY", "TRESEK",
    "TRÓJKĄT", "TRUCIZNA",
    "TRZCINA", "TRZEWIA",
    "TRZON", "TULEJ",
    "TULEJA", "TULIPAN",
    "TUNEL", "TURBANY",
    "TWARDA", "TWARDOŚĆ",
    "TWARDZIEJ",
    "TWARZY", "TWÓRCA",
    "TYFUS", "TYGRYS",
    "TYKWA", "TYŁEK",
    "TYRANIA",

    # Final batch
    "UBOGI", "UBOGIE", "UBÓSTWO",
    "UCISK", "UCIECZKA",
    "UGIER", "UGNIATAĆ",
    "UGRZĄZŁ",
    "UJŚCIE", "ULOTNY",
    "UMIAR", "UMIARKOWANIE",
    "UPADEK", "UPAŁ",
    "UPOMINEK",
    "UPOSAŻENIE",
    "UPRAWA",
    "URAZ",
    "URNA",
    "UROCZY",
    "URODA",
    "UROJENIE",
    "UROK",
    "UROKLIWY",
    "UROSTEK",
    "URWIS",
    "USCHNĄĆ",
    "USKOK",
    "USTAWA",
    "USZCZELNIAĆ",
    "UTARG",
    "UTARCZKA",
    "UTKNĄĆ",
    "UTONĄĆ",
    "UWAGA",
    "UWODZIĆ",
    "UZDA",
    "UŻYTEK",
    "WABIĆ",
    "WABIK",
    "WAHADŁO",
    "WALET",
    "WANNA",
    "WARGI",
    "WARTA",
    "WARTKI",
    "WASYL",
    "WATAHA",
    "WĄWÓZ",
    "WĄSY",
    "WBREW",
    "WDECH",
    "WDZIĘK",
    "WIEDEŃ",
    "WIENIEC",
    "WIERTEK",
    "WIETRZNY",
    "WIGILIA",
    "WIKLINOWY",
    "WINIEC",
    "WIOSKA",
    "WIRTUOZ",
    "WIRUS",
    "WKŁAD",
    "WKLĘSŁY",
    "WŁASNY",
    "WŁÓKNO",
    "WNIOSKI",
    "WODOSPAD",
    "WODZIĆ",
    "WOJSKO",
    "WOLNO",
    "WOLTYŻ",
    "WORECZEK",
    "WOŹNY",
    "WÓZEK",
    "WPŁAW",
    "WSKAŹNIK",
    "WSKRÓŚ",
    "WSTRZĄS",
    "WUJECZNY",
    "WYBIEGI",
    "WYBÓJ",
    "WYCIEK",
    "WYGIBASY",
    "WYGNANIE",
    "WYJAZD",
    "WYKOPY",
    "WYLEK",
    "WYLOT",
    "WYMAWIAĆ",
    "WYMOK",
    "WYNIOSŁY",
    "WYPAS",
    "WYPRAWA",
    "WYPRZEDAŻ",
    "WYRAZ",
    "WYROST",
    "WYRÓB",
    "WYRZUT",
    "WYSIEW",
    "WYSOKI",
    "WYSPA",
    "WYSTRÓJ",
    "WYTOK",
    "WYTYK",
    "WZGARDA",
    "WZGÓRZE",
    "WZNIOS",
    "WZORZEC",
    "WZROST",
    "WZRUSZAĆ",
    "ZABIEGI",
    "ZABIJAĆ",
    "ZABYTEK",
    "ZACHÓD",
    "ZAGADKA",
    "ZAGRAĆ",
    "ZAGRODA",
    "ZAKĄTEK",
    "ZAKRZEP",
    "ZAMACH",
    "ZAMIAST",
    "ZAMIAR",
    "ZAPACH",
    "ZAPARCIE",
    "ZAPAS",
    "ZAPORA",
    "ZARAZA",
    "ZARDZEWIAŁY",
    "ZAROST",
    "ZARÓWNO",
    "ZASADZKA",
    "ZASIEK",
    "ZASTÓJ",
    "ZASUWA",
    "ZAWAŁ",
    "ZAWIERUCHA",
    "ZAWIJA",
    "ZAWINIĄĆ",
    "ZAWISŁ",
    "ZAZDROŚĆ",
    "ZAŻYŁOŚĆ",
    "ZBIEG",
    "ZDANIE",
    "ZDOBYCZ",
    "ZEGAR",
    "ZEMSTA",
    "ZGAGA",
    "ZGLISZCZA",
    "ZGROZA",
    "ZGUBA",
    "ZIMOTRWAŁ",
    "ZJAZD",
    "ZŁOTA",
    "ZŁOTO",
    "ZŁÓŻ",
    "ZMĘCZENIE",
    "ZMROK",
    "ZNAWCA",
    "ZNIKNĄĆ",
    "ZOOLOG",
    "ZORZA",
    "ZRĄB",
    "ZRYW",
    "ZWADA",
    "ZWĘGLIĆ",
    "ZWITEK",
    "ZWROT",
    "ŻAGIEL",
    "ŻALUZJA",
    "ŻANDARM",
    "ŻARÓWKA",
    "ŻBIK",
    "ŻEBRO",
    "ŻMUDNY",
    "ŻONKIL",
    "ŻÓŁTKO",
    "ŻÓŁW",
    "ŻURAW",
    "ŻUŻEL",
    "ŻWIR",
    "ŻYWOPŁOT",
]

# =====================================================================
# Clean and deduplicate — keep only exactly-5-character words
# =====================================================================
def make_wordlist(raw):
    seen = set()
    result = []
    for w in raw:
        w = w.strip().upper()
        if len(w) == 5 and w.isalpha() and w not in seen:
            seen.add(w)
            result.append(w)
    return sorted(result)

all_words = make_wordlist(ALL_WORDS_RAW)
print(f"Total after filtering: {len(all_words)}")
print("Sample:", all_words[:30])
PYEOF
