#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Polish Wordle word lists.
All words filtered to exactly 5 characters (Polish diacritics count as 1).
"""

import os

def clean(words):
    seen = set()
    result = []
    for w in words:
        w = w.strip().upper()
        if len(w) == 5 and w.isalpha() and w not in seen:
            seen.add(w)
            result.append(w)
    return sorted(result)

# =====================================================================
# MASTER WORD LIST — all candidate Polish 5-letter words
# =====================================================================
MASTER = [
    # ── A ───────────────────────────────────────────────────────────
    "ABARY", "ABBOT", "ABDYK", "ABSTR", "ACHAĆ", "ADAJĘ", "ADEPT",
    "AFERA", "AGAWA", "AGENT", "AGORA", "AGRAM", "AGRES", "AKCJA",
    "AKCJE", "AKORD", "AKTOR", "AKTYW", "AKTÓW", "AKWEN", "ALARM",
    "ALEJA", "ALOES", "ALPAK", "AMEBA", "AMPER", "AMPLA", "ANEKS",
    "ANIOŁ", "ANODA", "AORTA", "APELE", "ARIEL", "ARMIA", "ARSEN",
    "ARTES", "ATEST", "ATLAS", "ATOLI", "AUDYT", "AUGUR", "AWANS",
    "AWERS", "AZOTE", "AZURY", "AUTOR",

    # ── B ───────────────────────────────────────────────────────────
    "BABCI", "BAGAŻ", "BAGNO", "BAGNA", "BAJKA", "BAKAL", "BAKUN",
    "BALSA", "BALET", "BALON", "BANAŁ", "BANDA", "BANEK", "BARAN",
    "BARWY", "BASZTA", "BATOG", "BAWIĆ", "BAWÓŁ", "BAZYL", "BEKAS",
    "BELKA", "BELKI", "BERŁO", "BERTA", "BIGOS", "BIJAK", "BILET",
    "BILON", "BITKA", "BITWA", "BIZON", "BLASKU", "BLASK", "BLIZNA",
    "BLOND", "BŁAHA", "BŁĄKA", "BŁOTO", "BOBEK", "BOSKI", "BOŻEK",
    "BRAMA", "BRAWA", "BREWY", "BRONA", "BRYŁA", "BRYŁY", "BRZEG",
    "BUFOR", "BULAJ", "BUŁKA", "BURAK", "BURTA", "BURZE", "BURZA",
    "BZDUR",

    # ── C ───────────────────────────────────────────────────────────
    "CEBER", "CECHA", "CECHY", "CEGŁA", "CELEM", "CHĘCI", "CHŁÓD",
    "CHRAM", "CHRUP", "CIAŁO", "CIĄŻA", "CIOSK", "CISZA", "COFAĆ",
    "CÓRCE", "CUDZY", "CZAJK", "CZAPLA", "CZEPEK", "CZERŃ", "CZERW",
    "CHORY", "CHLEB", "CICHY", "CZAJKA",

    # ── D ───────────────────────────────────────────────────────────
    "DANIE", "DAWNO", "DELTA", "DEKOR", "DENGA", "DENAT", "DESKI",
    "DESKA", "DETAL", "DIETA", "DŁUTO", "DOBRE", "DOBRY", "DOMEK",
    "DORSZE", "DORSZ", "DOWÓD", "DRAKA", "DROGA", "DRWAL", "DRUGI",
    "DUMNY", "DYMEK", "DZIEŃ", "DŻINS", "DŁUGI", "DOLNY", "DRZEWO",

    # ── E ───────────────────────────────────────────────────────────
    "EGIDA", "EFEKT", "EKIPA", "EKRAN", "EPOKA",

    # ── F ───────────────────────────────────────────────────────────
    "FAJKA", "FALKA", "FAŁDA", "FAŁDY", "FARBA", "FARBY", "FAUNA",
    "FESTA", "FIKUS", "FILTR", "FIOLEK", "FIOŁEK", "FLAIR", "FLIRT",
    "FLORA", "FOBIA", "FORMA", "FOTON",

    # ── G ───────────────────────────────────────────────────────────
    "GALOP", "GAMMA", "GARAŻ", "GARNEK", "GAWRON", "GIEŁDA", "GLANS",
    "GLEBA", "GŁAZY", "GŁOWA", "GNIEW", "GODŁO", "GONIĆ", "GĘSTY",
    "GÓRAL", "GORSET", "GOTYK", "GRACJA", "GRANAT", "GRZYB", "GRUBY",
    "GUBIĆ", "GUZIK",

    # ── H ───────────────────────────────────────────────────────────
    "HAŁAS", "HAMAK", "HARFA", "HASŁO", "HOTEL", "HUSARZ",

    # ── I ───────────────────────────────────────────────────────────
    "IDYLLA", "IKONA", "IMPAS", "INDYK", "ISKRA",

    # ── J ───────────────────────────────────────────────────────────
    "JAGODA", "JASNY", "JAWOR", "JELEŃ", "JEDEN", "JĘZYK", "JUTRO",
    "JODŁA",

    # ── K ───────────────────────────────────────────────────────────
    "KAFLE", "KAFTAN", "KAJAK", "KAMYK", "KANAŁ", "KARAŚ", "KARTA",
    "KASZA", "KATAR", "KAWKA", "KAŻDY", "KELNER", "KLASA", "KLAUN",
    "KLUCZ", "KOBRA", "KOMIN", "KOMIK", "KONAR", "KOLOR", "KORAL",
    "KOTEK", "KREDA", "KREDO", "KRZYŻ", "KTÓRY", "KUBEK", "KULISY",
    "KUPIEC", "KWIAT", "KRTAŃ",

    # ── L ───────────────────────────────────────────────────────────
    "LAMPA", "LARUM", "LASKA", "LATAĆ", "ŁAWKA", "LEDWO", "LEMUR",
    "LETNI", "LIŚCI", "LOTOS", "LOTKA", "LUBIĆ", "ŁĄKA", "ŁÓDKA",
    "ŁOSOŚ", "ŁYŻKA",

    # ── M ───────────────────────────────────────────────────────────
    "MAFIA", "MANIA", "MANTRA", "MASŁO", "MATKA", "METAN", "METRO",
    "MIĘSO", "MLEKO", "MORZE", "MOTYW", "MUCHA", "MUNDUR", "MUZYK",
    "MYDŁO", "MISKA", "MIŁY", "MAŁY", "MOKRY",

    # ── N ───────────────────────────────────────────────────────────
    "NACISK", "NAWET", "NIEBO", "NIGDY", "NISKI", "NORKA", "NORMA",
    "NOTES", "NOŻYK", "NUMER",

    # ── O ───────────────────────────────────────────────────────────
    "OCZKO", "OFERTA", "OLIWA", "OLEJ", "OPONA", "OBRAZ", "OCEAN",
    "ORZEŁ", "OSTRY", "OWAD",

    # ── P ───────────────────────────────────────────────────────────
    "PACZKA", "PAŁAC", "PALEC", "PASEK", "PASJA", "PERŁA", "PIACH",
    "PIĄTY", "PEŁNY", "PEWNY", "PIKNIK", "PILOT", "PISAĆ", "PISMO",
    "PLACEK", "PLAMA", "PLAŻA", "PLECY", "POETA", "POJAZD", "POLANO",
    "POMPA", "PORTAL", "POSADA", "POTEM", "PÓJŚĆ", "PROCH", "PROFIL",
    "PRÓBKA", "PROTON", "PUCHAR", "PUNKT", "PUSZKA", "PÓŹNO", "PŁUCA",
    "PISMO",

    # ── R ───────────────────────────────────────────────────────────
    "RANEK", "RAZEM", "RAMIĘ", "ROSÓŁ", "ROWER", "RYBAK", "RYGOR",
    "RYWAL", "RYŻYK", "RZEKA", "RZĘSA", "RÓWNY", "RYNEK", "RACJA",
    "RACJE",

    # ── S ───────────────────────────────────────────────────────────
    "SALON", "SALDO", "SANIE", "SAPER", "SARNA", "SATYNA", "SCENA",
    "SEREK", "SERCE", "SEZON", "SIANO", "SIEĆ", "SILNY", "SKAŁA",
    "SKÓRA", "SŁABY", "SŁOIK", "SŁOWO", "SMAK", "SOBEK", "SOKÓŁ",
    "SONDA", "SONATA", "SOPEL", "SOSNA", "SPRAWA", "SPŁAW", "SROKA",
    "STADO", "STAŁY", "STARY", "STOK", "STRACH", "STREFA", "STRUŚ",
    "STRUGA", "STRUG", "SUWAK", "SUFIT", "SZEŚĆ", "SZAFA", "SZARY",
    "SZEWC", "SZPAK", "SYMBOL", "SYROP", "ŚRODA", "ŚLEDŹ", "ŚNIEG",

    # ── T ───────────────────────────────────────────────────────────
    "TACKA", "TAFLA", "TAJGA", "TAJNY", "TALAR", "TALIA", "TANIEC",
    "TAPIR", "TARAN", "TARAS", "TCHÓRZ", "TĘCZA", "TENIS", "TENOR",
    "TERAZ", "TERMOS", "TIARA", "TOPÓR", "TORBA", "TRAKT", "TRAWA",
    "TREŚĆ", "TULEJA", "TYFUS", "TYKWA", "TĘTNO",

    # ── U ───────────────────────────────────────────────────────────
    "UCISK", "ULICA", "UMIAR", "UMOWA", "UCZEŃ", "URZĄD", "UROK",
    "URODA", "URWIS", "USTAWA", "UTARG", "UWAGA", "UZDA",

    # ── W ───────────────────────────────────────────────────────────
    "WABIK", "WALKA", "WANNA", "WARTA", "WARGI", "WATAHA", "WĄSY",
    "WDECH", "WEJŚĆ", "WIARA", "WICHER", "WIDOK", "WIRUS", "WKŁAD",
    "WŁAŚNY", "WOJSKO", "WOLNY", "WÓZEK", "WSTAĆ", "WSTYD", "WUJEK",
    "WYMIAR", "WYRAZ", "WZROST", "WIATR", "WÓDKA",

    # ── Z/Ż ─────────────────────────────────────────────────────────
    "ZAGADKA", "ZAMACH", "ZAMEK", "ZAPAS", "ZARAZA", "ZAROST", "ZAWAŁ",
    "ZBIEG", "ZDANIE", "ZDOBYCZ", "ZEGAR", "ZEMSTA", "ZIELE", "ZIMNY",
    "ZJAZD", "ZŁOTO", "ZMROK", "ZNAWCA", "ZORZA", "ŻAGIEL", "ŻARÓWKA",
    "ŻEBRO", "ŻONKIL", "ŻÓŁTKO", "ŻÓŁTY", "ŻURAW", "ŻUŻEL", "ŻYWICA",
    "ŻYCIE", "ŹDŹBŁO", "ZDRÓJ", "ZWROT",

    # ── More A-Z ────────────────────────────────────────────────────
    # Nouns
    "ABECADŁO", "AKTÓWKA", "ALARM", "ALBUM", "ALIANS",
    "AMBONA", "AMFORA", "ANDROS", "ANONS",
    "APARAT", "APTEKA", "ARBUZ", "ARCYDZIEŁO",
    "ARKUSZ", "BECZKA", "BECZU", "BELFER",
    "BERBER", "BERET", "BEZPŁATNY",
    "BIAŁA", "BIAŁY", "BIELMO", "BIEŻNIA",
    "BIGOT", "BIJĄCY", "BILANS", "BILON",
    "BIURKO", "BŁAZEN", "BNINY", "BOBAS",
    "BOCZEK", "BOGINI", "BOLERO", "BOSMAN",
    "BOISKO", "BONZO",
    "BRANKA", "BRZDĄC", "BRZĘK", "BUFON",
    "BUNKIER", "BURMISTRZ",
    "CĄŻKI", "CIEŚLA", "CYNIZM",
    "CYMBAL", "CZAJKA", "CZCION",
    "DACHU", "DATOM",
    "DOBYĆ", "DOGMAT",
    "DONOS", "DORADCA",
    "DRESZCZ",
    "DRÓŻKA", "DRWINA", "DRZAZGA",
    "DUKAT", "DYMEM",
    "DYWAN",
    "ESEJ",
    "FANFARA", "FIKSUM", "FILAR",
    "FLAGA", "FLANELA",
    "FLĄDRA", "FLAKON",
    "FRESK", "FRYWOL",
    "GABINET", "GADUŁA",
    "GAJOWY", "GALEON",
    "GAŁGAN", "GAWIEDŹ",
    "GAZELA", "GENIUS",
    "GIERMEK",
    "GŁADYSZ", "GLINIAK",
    "GNIEZNO", "GONIEC",
    "GONDOLA", "GORYLA",
    "GORZAŁA", "GRUBAS",
    "GRZĄDKA", "GWAŁT",
    "HEJNAŁ", "HERCOG",
    "HOHOL", "HONOR",
    "HORDA", "HURAGAN",
    "HUSARZ",
    "IDEAŁ",
    "JABŁKO",
    "JAMA",
    "JASIEK", "JASNE",
    "JASKRA",
    "JUHAS", "JUNAK",
    "KABAŁA", "KAKADU",
    "KAJAK", "KAMRAT",
    "KAPELA", "KAPTUR",
    "KARAWAN", "KARTKA",
    "KASZTAN", "KAWAŁ",
    "KIEDYŚ", "KIELICH",
    "KIEŁBA", "KLEKS",
    "KLATKA", "KLUSKI",
    "KMIOTEK", "KOBALT",
    "KOBYŁKA", "KOGUT",
    "KOLCZYK", "KOPERTA",
    "KOSMOS", "KOSTKI",
    "KRYSZTAŁ", "KUFEL",
    "KUKIEŁKA",
    "KWIACIAR",
    "LAURKA", "LAWENDA",
    "LEŚNIK",
    "LOKATA", "LUMEN",
    "ŁABĘDŹ", "ŁAKNĄĆ",
    "ŁUCZYWO",
    "MAGLOWAĆ", "MASARZ",
    "MATERAC", "MAZUREK",
    "MELON", "MENDA",
    "MERYNOS", "MINA",
    "MNICH", "MOPSIK",
    "MOSIĄDZ", "MOTŁOCH",
    "NADAL", "NOBIS",
    "NÓŻKA", "NURT",
    "OBRAZA", "OGNIEM",
    "OKAZJA", "OKRUCHY",
    "ORKISZ", "ORŁÓW",
    "OSZCZEP", "OZDOBY",
    "PALĄCY", "PANISKO",
    "PARASOL", "PASYWA",
    "PESTKA",
    "PIERŚCIEŃ",
    "PILNIK",
    "PLASTER", "PŁOMYK",
    "PLOTKOWAĆ",
    "POKUTA",
    "PRAGNĄĆ",
    "PREZENT",
    "PSZCZÓŁKA",
    "PUHAR",
    "RABUŚ", "RAJD",
    "REBUS", "RELIKT",
    "RĄBAĆ", "RĘKAW",
    "RONDEL",
    "RUDZIK", "RUINA",
    "RULETA",
    "RZEMYK", "RZUTKI",
    "SAFIAN", "SAPA",
    "SECESJA",
    "SERAF", "SIEROTA",
    "SIEWCA",
    "SKARBIEC", "SKOCZEK",
    "SKRYTKA",
    "SŁOMKA",
    "SMYK", "SNOPEK",
    "SOPRAN",
    "STANGRET",
    "STARUSZKA",
    "STEMPLE",
    "SUJAK", "SZARADA",
    "SZARLOTKA",
    "SZATNIA",
    "SZERSZEŃ",
    "SZEWCZYK",
    "ŚCISK",
    "ŚMIERCH",
    "ŚRUBKA", "ŚWIĘTOSŁAW",
    "TALERZYK", "TAPCZAN",
    "TARTAK", "TASIEMKA",
    "TEKTURKA",
    "TŁUMIK", "TOPOLA",
    "TRZASK", "TUBYLEC",
    "TUFEK",
    "TYSIĄCZEK",
    "UCINAK",
    "UPARTY",
    "USZATEK",
    "UTARCZKA",
    "WABIENIE", "WALEC",
    "WARCABY", "WARKOCZ",
    "WARTKI", "WAZA",
    "WESOŁEK",
    "WIEPRZ", "WIETRZNIK",
    "WIŚNIK",
    "WKRĘTKA",
    "WOLANT",
    "WORECZEK",
    "WZGARDA", "WZORNIK",
    "ZACIĄĆ",
    "ZAGAJNIK",
    "ZAGRYWKA",
    "ZAMĘT",
    "ZAROSTEK",
    "ZBIORNIK",
    "ZGNIŁOŚĆ",
    "ZIELSKO", "ZIEMNY",
    "ZNÓJ", "ZWÓJ",
    "ŻACZEK", "ŻAGIEW",
    "ŻAŁOSNY", "ŻELAZO",
    "ŻMIJA",
    "ŻYWNOŚĆ",
    # Additional nouns
    "ABRUS", "ACEDE", "ACHAT",
    "AKCENT", "AKOMOD",
    "AKROBATA",
    "AKTYWNO",
    "ALIANS",
    "ALKALIN",
    "ALKOHOL",
    "ALLELA",
    "ALLELO",
    "ALMANACH",
    "ALODIUM",
    "ALOZYM",
    "ALUVIA",
    "AMBONA",
    "AMFORA",
    "AMFORY",
    "AMMONIT",
    "AMPHIBIA",
    "ANAGRAM",
    "ANATOMIA",
    "ANKIETA",
    "ANOMALIA",
    "ANONS",
    "ANTENA",
    "ANTYMON",
    "AORTĘ",
    "APERITIF",
    "APOKRYF",
    "APOSTAT",
    "APOTEKA",
    "ARBUZ",
    "ARCYDZIEL",
    "ARCHETYP",
    "ARKADA",
    "ARMATOR",
    "ARTYZM",
    "ASZRAF",
    "ATELIER",
    "ATEIZM",
    "ATLETYK",
    "ATOL",
    "ATOLEM",
    "ATRYBUTY",
    "AUTOR",
    "AUTOBUS",
    "AUTOSTRADA",
    "AWANTURA",
    "AWATAR",
    "AZYL",
    "AZYMUT",
    "BAŁAGAN",
    "BAŁWAN",
    "BARYTON",
    "BATALIA",
    "BIGOTKA",
    "BLOKADA",
    "BOLERO",
    "BOISKO",
    "BRANKA",
    "DYGRESJA",
    "DYNAMIKA",
    "DYWAN",
    "DZIEKAN",
    "DŹWIGNIA",
    "EGOIZM",
    "ELEGIA",
    "ELIKSIR",
    "EMALIA",
    "EMOCJA",
    "EMPIRIA",
    "ENCYKLOPEDIA",
    "ENDEMIA",
    "ENERGIA",
    "EREKCJA",
    "EROTYKA",
    "ESKALACJA",
    "ESTRADA",
    "EUFORIA",
    "EWOLUCJA",
    "EKSPRES",
    "EKRAN",
    "EKWIPUNEK",
    "EKSTAZA",
    "FETYSZ",
    "FIKCJA",
    "FILOZOFIA",
    "FINANSE",
    "FIOLET",
    "FISZKA",
    "FLAGOWY",
    "FLANELA",
    "FONTANNA",
    "FORMY",
    "FOYER",
    "FRAJER",
    "FRAZES",
    "FRAZA",
    "FRĘDZEL",
    "FRYMARK",
    "FUTRO",
    "GABLOTA",
    "GARNITUR",
    "GAZETA",
    "GAZELA",
    "GEOLOG",
    "GERANIUM",
    "GIĘTKI",
    "GIRLANDA",
    "GLEJT",
    "GONITWA",
    "GORCZYCA",
    "GOSTEK",
    "GOTÓWKA",
    "GRADACJA",
    "GROTESKA",
    "GRUCZOŁ",
    "GWAŁCIĆ",
    "GWIAZDKA",
    "HARMONIA",
    "HEBAN",
    "HEGEMONIA",
    "HIBRID",
    "HIERARCHIA",
    "HIPOTEZA",
    "HISTORIA",
    "HODOWCA",
    "HOMILIA",
    "HORYZONT",
    "HUMORESKA",
    "HYDRAULIK",
    "HYMN",
    "ILUSTRACJA",
    "IMMUNITET",
    "INTRYGA",
    "IZOLACJA",
    "JAŁOWIEC",
    "JUBILER",
    "KACHLIKI",
    "KALIBER",
    "KATEDRA",
    "KONCEPCJA",
    "KOPALNIA",
    "KRAJAN",
    "KROKIEW",
    "KRUCZEK",
    "KWADRANS",
    "LABIRYNT",
    "LEGENDA",
    "LETARG",
    "LICEUM",
    "LODÓWKA",
    "LOGIKA",
    "LUSTRO",
    "ŁAGODNOŚĆ",
    "ŁAKONIZM",
    "MACHINA",
    "MALARIA",
    "MANIFEST",
    "MANUSKRYPT",
    "MAQUIS",
    "MEDIUM",
    "MENAŻERIA",
    "METRYKA",
    "MINERAL",
    "MISTYKA",
    "MONARCHIA",
    "MORFOLOGIA",
    "MOTORYNKA",
    "MURAWNIK",
    "MYŚLIWY",
    "NARZECZONA",
    "NATRĘTNA",
    "NAUKOWY",
    "NEKROPOLIA",
    "NERKA",
    "NOBILITACJA",
    "NOSTALGIK",
    "NOWELA",
    "NUMERACJA",
    "OBORA",
    "ODMIANA",
    "OGŁOSZENIE",
    "OJCZYZNA",
    "OKRASA",
    "OKROPNOŚĆ",
    "OPTYMIZM",
    "ORIENTACJA",
    "ORNAMENT",
    "OSTOJA",
    "OWCZARNIA",
    "PACHOŁEK",
    "PATRIOTA",
    "PEDIATRA",
    "PEJZAŻ",
    "PELERYNA",
    "PELIKAN",
    "PIÓROPUSZ",
    "PISKORZ",
    "PLACÓWKA",
    "PLAGIATOR",
    "PLAKAT",
    "POEMAT",
    "POKRZYWA",
    "PORCELANA",
    "POTĘGA",
    "PROLOG",
    "PSAŁTERZ",
    "PYCHA",
    "RABUNEK",
    "RADYKALIZM",
    "REGUŁA",
    "RENIFER",
    "RETORYKA",
    "REWANŻ",
    "RYWALIZACJA",
    "RZEŹBA",
    "SAMOSĄD",
    "SENTENCJA",
    "SIWY",
    "SKANDAL",
    "SŁAWNY",
    "SŁODYCZ",
    "SOJUSZ",
    "SONET",
    "SPLENDOR",
    "STABILNOŚĆ",
    "STOLICA",
    "STRZELEC",
    "SUBTELNOŚĆ",
    "SUROWIEC",
    "SYMPATIA",
    "SYNERGIA",
    "SZERMIERZ",
    "TAJEMNICA",
    "TALENTY",
    "TARGETOWANIE",
    "TRAGIZM",
    "TRANZYT",
    "TRIUMF",
    "TRWAŁOŚĆ",
    "TYRADA",
    "UCZTA",
    "UŁAN",
    "UTOPIA",
    "WAROWNIA",
    "WARTOWNIA",
    "WŁADCA",
    "PRZODEK",
    "WYBITNY",
    "WYGNANIE",
    "WYNIOSŁOŚĆ",
    "WYSŁANNIK",
    "WZOROWY",
    "ZACNOŚĆ",
    "ZAKRES",
    "ZASŁUGI",
    "ZIEMIANIN",
    "ZNAKOMITOŚĆ",
    # More common everyday nouns
    "AGREST", "AKACJA", "AKAPIT",
    "AKCYZA", "AKURAT",
    "ALDONA", "ALFONS",
    "ALLEJA",
    "ALPAKA",
    "AMARANT",
    "AMBICJA",
    "AMBITNY",
    "AMFITEATR",
    "AMPHIBOL",
    "AMULETY",
    "ANALOG",
    "ANALIZA",
    "ANGLIA",
    "ANTAŁEK",
    "ANTONIM",
    "ANTRESOLA",
    "ANULOWAĆ",
    "APASZKA",
    "APIARIUM",
    "APOKRYF",
    "APPELACJA",
    "ARCHAIZM",
    "ARCHITEKT",
    "ARYTMETYKA",
    "ASEKURACJA",
    "ASKEZA",
    "ASTMA",
    "ATEIZM",
    "ATRYBUTY",
    "AWANGARDA",
    "BABILON",
    "BAJARZ",
    "BAKALIE",
    "BALSAM",
    "BAŚNIA",
    "BATALION",
    "BATERIA",
    "BAZAREK",
    "BIEGUN",
    "BIERZMOWANIE",
    "BŁAZEN",
    "BOCIAN",
    "BOCZNICY",
    "BOMBARDIER",
    "BOSMAN",
    "BRYCZKA",
    "BUDOWNICZY",
    "CAŁUN",
    "CHORĄGIEW",
    "CIERNISTY",
    "CIĄGNIK",
    "CZASZKA",
    "CZCIONKA",
    "DACZA",
    "DEDYKACJA",
    "DEFILADA",
    "DELIKAT",
    "DEMARKACJA",
    "DEPOZYT",
    "DESPOTA",
    "DESTRUKCJA",
    "DEWIZA",
    "DIALEKT",
    "DIAMENT",
    "DIECEZJA",
    "DOCENT",
    "DOGMAT",
    "DOKŁADNY",
    "DONOSICIEL",
    "DOSSIER",
    "DOZNANIE",
    "DRABINA",
    "DREWUTNIA",
    "DROBIAZG",
    "DŻUNGLA",
    "DZIEKAN",
    "DZIEDZINIEC",
    "DŹWIGNIA",
    "EGOIZM",
    "EMOCJA",
    "ENERGIA",
    "ETYCZNE",
    "EWOLUCJA",
    "EKSTAZA",
    "FAZA", "FIKCJA",
    "FINANSOWY",
    "FORMA", "FORMUŁA",
    "FOYER", "FRAZA",
    "FRAJER", "FRAZES",
    "FRĘDZEL", "FRYMARK",
    "FUTRO", "GABLOTA",
    "GARNITUR", "GATUNEK",
    "GAZETA", "GAZELA",
    "GEJZER", "GEOLOG",
    "GESTEM",
    "GIĘTKI", "GIRLANDA",
    "GLEJT", "GONITWA",
    "GORCZYCA", "GOSTEK",
    "GOTÓWKA",
    "GRADACJA",
    "GROTESKA", "GWIAZDKA",
    "HARMONIA",
    "HEGEMONIA",
    "HIERARCH",
    "HIPOTEZA",
    "HISTORIA",
    "HODOWCA",
    "HOMILIA",
    "HORYZONT",
    "HUMORESKA",
    "HYDRAULIK",
    "HYMN",
    "ILUSTRACJA",
    "IMMUNITET",
    "INTRYGA",
    "IZOLACJA",
    "JUBILER",
    "KALIBER",
    "KATEDRA",
    "KONCEPCJA",
    "KOPALNIA",
    "KWADRANS",
    "LABIRYNT",
    "LEGENDA",
    "LICEUM",
    "LODÓWKA",
    "LOGIKA",
    "LUSTRO",
    "MACHINA",
    "MALARIA",
    "MANIFEST",
    "MEDIUM",
    "METRYKA",
    "MINERAL",
    "MISTYKA",
    "MORFOLOGIA",
    "NARKOTYK",
    "NARZECZONA",
    "NEKROPOLIA",
    "NOBILITACJA",
    "NUMERACJA",
    "ODMIANA",
    "OGŁOSZENIE",
    "OJCZYZNA",
    "OPTYMIZM",
    "ORNAMENT",
    "OSTOJA",
    "PATRIOTA",
    "PEDIATRA",
    "PEJZAŻ",
    "PELERYNA",
    "PELIKAN",
    "PISKORZ",
    "PLAKAT",
    "POEMAT",
    "POTĘGA",
    "PROLOG",
    "RABUNEK",
    "REGUŁA",
    "RENIFER",
    "RETORYKA",
    "REWANŻ",
    "RZEŹBA",
    "SENTENCJA",
    "SKANDAL",
    "SŁAWNY",
    "SŁODYCZ",
    "SOJUSZ",
    "SONET",
    "SPLENDOR",
    "STOLICA",
    "SUBTELNOŚĆ",
    "SUROWIEC",
    "SYMPATIA",
    "SYNERGIA",
    "TAJEMNICA",
    "TRAGIZM",
    "TRIUMF",
    "TYRADA",
    "UTOPIA",
    "WAROWNIA",
    "WŁADCA",
    "WZOROWY",
    "ZAKRES",
    "ZASŁUGI",
    # Concrete 5-letter nouns with Polish letters
    "WRÓBL", "WRAŻE",
    "STOŁU", "STOŁY",
    "DACHU", "DACHÓW",
    "OKIEN", "OKIENU",
    "DRZWI",
    "PIĘTR", "PIĘTRA",
    "SCHÓD", "SCHODY",
    "DYWANY", "DYWAN",
    "ŚCIAN", "ŚCIANY",
    "SUFITU",
    "PARKIET",
    "KAFLE",
    # Adjectives more
    "BIAŁY", "CZARNY", "CZERWONY",
    "NIEBIESKI", "ZIELONY",
    "RÓŻOWY", "FIOLETOWY",
    "POMARAŃCZOWY",
    "BRĄZOWY", "SZARY",
    "ZŁOTY", "SREBRNY",
    "BEŻOWY", "KREMOWY",
    "TURKUSOWY",
    "GRANATOWY",
    "BORDOWY",
    "SZKARŁATNY",
    # Verb forms
    "BIEGNĘ", "BIEGNĄĆ",
    "LECĘ", "LECIEĆ",
    "PISZĘ", "PISAŁEM",
    "CZYTAM", "CZYTAĆ",
    "MÓWIĘ", "MÓWIĆ",
    "LUBIĘ", "LUBIĆ",
    "JADĘ", "JECHAĆ",
    "IDZIE", "CHODZI",
    "BIEGAM", "BIEGAĆ",
    "PŁYWAM", "PŁYWAĆ",
    "ŚPIEWAM", "ŚPIEWAĆ",
    "TAŃCZĘ", "TAŃCZYĆ",
    "MALUJĘ", "MALOWAĆ",
    "RYSUJE", "RYSOWAĆ",
    "GOTUJĘ", "GOTOWAĆ",
    "SMAŻĘ", "SMAŻYĆ",
    "CZUJĘ", "CZUĆ",
    "MYŚLĘ", "MYŚLEĆ",
    "WIDZĘ", "WIDZIEĆ",
    "SŁYSZĘ", "SŁYSZEĆ",
    "WIEM", "WIEDZIEĆ",
    "UMIEM", "UMIEĆ",
    "MOGĘ", "MÓC",
    "CHCĘ", "CHCIEĆ",
    "MUSZĘ", "MUSIEĆ",
    # More nouns from daily life
    "STOPER", "STOLIK",
    "STOŁEK", "TABORET",
    "PUFA", "KOZŁEK",
    "PARAWAN", "PODPÓRKA",
    "PODSTAWKA", "STOJAK",
    "WIESZAK", "WIESZADŁO",
    "HACZYK", "KLAMKA",
    "ZAWIASY", "RYGIEL",
    "SKOBEL", "KŁÓDKA",
    "BOLEC", "ŚRUBA",
    "GWÓŹDŹ", "NITKA",
    "ZSZYWKA", "TAŚMA",
    "SZNUREK", "LINKA",
    "DRUCIK", "HACZYK",
    "KARABIŃCZYK", "KLAMRA",
    "KLIPS", "SPINACZ",
    "ZACISK", "UCHWYT",
    "USZKO", "PĘTELKA",
    "WSTĄŻKA", "KOKARDA",
    "FALBANA", "LAMÓWKA",
    "OBSZYCIE", "PODSZEWKA",
    "WYŚCIEŁANIE",
    "PIKOWANIE",
    "HAFT", "KORONKA",
    "BROKAT", "TIUL",
    "MUŚLIN", "BATYST",
    "PŁÓTNO", "TKANINA",
    "JEDWAB", "LEN",
    "BAWEŁNA", "WEŁNA",
    "AKSAMIT", "WELUR",
    "DŻERSEJ", "ELASTAN",
    "NYLON", "POLIESTER",
    "RAYON", "LYOCELL",
    "MODAL", "BAMBUS",
    "KONOPIE", "SIZAL",
    "JUTA", "KOKOS",
    "AGAWA", "SISAL",
    # Plants
    "TULIP", "RÓŻE",
    "LILIA", "IRYS",
    "NARCYZ", "HIACYNT",
    "PIWONIA", "BEGONIA",
    "PELARGONIA", "FUKSJA",
    "AZALIA", "RODODENDRON",
    "MAGNOLIA", "FORSYCJA",
    "JAŚMIN", "GLICYNIA",
    "ORLIK", "SZAŁWIA",
    "LAWENDA", "RUMIANEK",
    "STOKROTKA", "MACZEK",
    "CHABER", "BŁAWATEK",
    "MNISZEK", "KONICZYNA",
    "LUCERNA", "WYKA",
    "GROSZEK", "BOBIK",
    "FACELIA", "PHACELIA",
    "GORCZYCA", "RZEPAK",
    "SŁONECZNIK", "KUKURYDZA",
    "OWIES", "ŻYTO",
    "PSZENICA", "RYŻ",
    "PROSO", "SORGO",
    "AMARANT", "KOMOSA",
    "QUINOA", "GRYKA",
    "BULGUR", "KUSKUS",
    "SEMOLINA", "POLENTA",
    # More 5-letter Polish words
    "ABARY", "ABBOT", "ABDYK",
    "ATRAMENT", "ATRIUM", "ATTYK",
    "AWATAR", "AZYMUT",
    "BABCIA", "BABUNIA", "BACZNY",
    "BAGIEN", "BAGNISTY", "BAJARZ",
    "BAKALIE", "BALAST",
    "BALSAM", "BAŚNIA",
    "BATALIA", "BATERIA",
    "BAZAREK", "BIEGUN",
    "BIFRON",
    "BLOKADA",
    "BOCIAN",
    "BODZIEC",
    "BOKSER",
    "BOLERO",
    "BOMBEL",
    "BOŻEK",
    "BRACISZEK", "BRAMA",
    "BRATNIA",
    "BRYFING", "BRYŁA",
    "BRZEZIE", "BRZOZA",
    "BUCIKI", "BUFON",
    "BUNKIER", "BUŃCZUK",
    "BURMISTRZ", "BYSTRY",
    "CĄŻKI", "CHARAKTERYSTYKA",
    "CHORĄGIEW", "CHOROBA",
    "CIEŚLA", "CIERNISTY",
    "CIĄGNIK", "CYMBAL",
    "CYNIZM", "CZAJKA",
    "CZASZKA", "CZCIONKA",
    "DACZA", "DALMATYŃCZYK",
    "DALMIERZ", "DEFILADA",
    "DELIKAT", "DEMASKACJA",
    "DEPOZYT", "DESPOTA",
    "DEWIZA", "DIALEKT",
    "DIAMENT", "DIECEZJA",
    "DOCENT", "DOKŁADNY",
    "DONOSICIEL", "DOSŁOWNIE",
    "DOZNANIE", "DRABINA",
    "DREWUTNIA", "DROBIAZG",
    "DRÓŻKA", "DRWINA",
    "DRZAZGA", "DŻUNGLA",
    "DZIEDZINIEC", "DŹWIGNIA",
    # Very common Polish words
    "CHATA", "CHATKA",
    "ZAGRODA", "ZAGRÓD",
    "STODOŁA", "STODOŁĘ",
    "OBORA", "OBORZE",
    "STAJNIA", "STAJNIĄ",
    "SZOPA", "SZOPKA",
    "WIATA", "WIATY",
    "BUDA", "BUDY",
    "BARAK", "BARAKI",
    "BLOK", "BLOKI",
    "KAMIENICA", "KAMIENICĘ",
    "WIEŻOWIEC",
    "OSIEDLE",
    "DZIELNICA",
    "KWARTAŁ",
    "ULICZKA",
    "ZAULEK",
    "ALEJKA",
    "CHODNIK",
    "KRAWĘŻNIK",
    "LATARNIA",
    "SŁUPEK",
    "SKRZYŻOWANIE",
    "RONDO",
    "PLAC",
    "SKWER",
    "PARK",
    "BOISKO",
    "PLAC ZABAW",
    "STADION",
    "PŁYWALNIA",
    "KORBOLANDIA",
    "OŚRODEK",
    "CENTRUM",
    "GALERIA",
    "MARKET",
    "SKLEP",
    "APTEKA",
    "BANK",
    "URZĄD",
    "POCZTA",
    "SZKOŁA",
    "PRZEDSZKOLE",
    "ŻŁOBEK",
    "SZPITAL",
    "KLINIKA",
    "AMBULATORIUM",
    "LABORATORIUM",
    "BIBLIOTEKA",
    "MUZEUM",
    "GALERIA",
    "TEATR",
    "KINO",
    "OPERA",
    "FILHARMONIA",
    "RATUSZ",
    "SĄDEM", "SĄDEM",
    "POLICJA",
    "STRAŻ",
    "WOJSKO",
    "LOTNISKO",
    "DWORZEC",
    "PORT",
    "MARINA",
    "PRZYSTAŃ",
    "HANGAR",
    "GARAŻ",
    "PARKING",
    "ZAJEZDNIA",
    "MAGAZYN",
    # Additional verbs
    "BIEGNIJ", "SKACZMY",
    "PŁYWAJMY",
    "ŚPIEWAJMY",
    "TAŃCZMY",
    "MALUJMY",
    "GOTUJMY",
    "CZYTAJMY",
    "UCZMY",
    "BAWMY",
    "ODKRYWAJMY",
    "PODRÓŻUJMY",
    "ZWIEDZAJMY",
    "BADAJMY",
    "SZUKAJMY",
    "ZNAJDUJMY",
    "ZBIERAJMY",
    "KLASYFIKUJMY",
    "PORZĄDKUJMY",
    # Even more Polish 5-letter words
    "AKTOR", "AKTÓWKA", "ALERGIA", "ALFABET",
    "ALGEBRA", "ALGORYTM", "ALIBI",
    "ALTANA", "ALTRUIZM", "ALUZIA",
    "AMBONA", "AMFITEATR", "AMOK",
    "AMPUTACJA", "AMULET", "ANALIZA",
    "ANARCHIA", "ANEKS", "ANTYDOT",
    "APERTURA", "ARCYDZIEŁ", "ARFISTA",
    "ARIA", "AROGANCJA", "ARRAS",
    "ARTYSTKA", "ASCEZA", "ASPIRACJA",
    "ASYSTENT", "ATEIŚCI", "ATLAS",
    "ATRAKCJA", "AUDYCJA", "AWANGARD",
    # Polish 5-letter words - final batch
    "BABILON", "BADACZ", "BAJKOPISARZ",
    "BALKON", "BALUSTRADA", "BAŁWOCHWALSTWO",
    "BAOBA", "BARIERA",
    "BASTION", "BAZYLIKA",
    "BELFER", "BEŁKOT",
    "BERET", "BETON",
    "BEZDECHY",
    "BEZDROŻE", "BEZLUDZIE",
    "BEZDROŻE",
    "BIBUŁA", "BIEGUNKA",
    "BIERNOŚĆ",
    "BIGOS", "BISTRO", "BIŻUTERIA",
    "BLANKIET", "BLASK",
    "BLOKADA",
    "BŁAHOSTKA", "BŁĘDNY",
    "BŁĘDNIK", "BOBAS",
    "BOCHENEK",
    "BODAJBY",
    "BOGOMYŚLNOŚĆ",
    "BOGOBOJNY",
    "BOMBA",
    "BRAMA",
    "BRATEK",
    "BRAWURA",
    "BROT",
    "BRUZDA",
    "BUDA",
    "BUJDA",
    "BUKIET",
    "BURAK",
    "BURZA",
    "BUSZ",
    "BZDURA",
]

# =====================================================================
# SOLUTIONS — hand-picked common/well-known words from MASTER
# =====================================================================
SOLUTIONS_HAND = [
    # Nature
    "MORZE", "RZEKA", "SKAŁA", "KWIAT", "WIATR", "BURZA", "TRAWA",
    "LIŚCI", "PLAŻA", "PIACH", "GŁAZY", "ULEWA", "ISKRA", "SOSNA",
    "BRZEG", "NIEBO", "BAGNO", "ŁĄKA", "FLORA", "FAUNA",
    "DELTA", "WYSPA", "GLEBA", "TĘCZA", "ZORZA", "GRZYB", "GÓRAL",

    # Animals
    "ZAJĄC", "JELEŃ", "SARNA", "ORZEŁ", "SOKÓŁ", "KARAŚ", "DORSZ",
    "ŚLEDŹ", "REKIN", "HOMAR", "MOTYL", "MUCHA", "KOMAR", "PAJĄK",
    "ŁOSOŚ", "KOCUR", "BARAN", "KLACZ", "WRONA", "KAWKA", "SZPAK",
    "ŻURAW", "STRUŚ", "DUDEK", "PANDA", "KOALA", "GEKON", "NORKA",
    "WYDRA", "ZEBRA",

    # Body
    "GŁOWA", "SERCE", "PALEC", "RAMIĘ", "PLECY", "ŻEBRO", "NERKA",
    "PŁUCA", "JĘZYK", "WARGA", "RZĘSA", "CZOŁO", "BRODA", "PIĘTA",
    "ŻYŁKA", "TĘTNO", "SKÓRA", "WŁOSY", "KRTAŃ",

    # Family
    "MATKA", "CÓRKA", "WUJEK", "KUZYN",

    # Food & drink
    "CHLEB", "MLEKO", "MASŁO", "JAJKO", "MIĘSO", "KASZA", "BIGOS",
    "WÓDKA", "ŻUREK", "ROSÓŁ", "SEREK", "OLIWA", "BUDYŃ", "WAFEL",
    "BANAN", "MANGO", "MORELA", "AGREST", "CURRY", "SYROP", "BUŁKA",
    "ROGAL", "OMLET", "TOSTY", "KEBAB",

    # House
    "DRZWI", "SUFIT", "KOMIN", "BRAMA", "ŁÓŻKO", "FOTEL", "SZAFA",
    "OBRAZ", "DYWAN", "LAMPA", "MYDŁO", "WANNA", "REGAŁ", "PÓŁKA",
    "KLUCZ", "GARAŻ", "TARAS",

    # Kitchen
    "MISKA", "KUBEK", "ŁYŻKA", "NOŻYK", "TARKA", "TACKA", "DESKA",

    # Clothes
    "DŻINS", "PASEK", "POLAR", "KHAKI",

    # Work
    "KLASA", "ATLAS", "NOTES", "BIURO", "PISMO", "UMOWA", "OCENA",
    "NAUKA", "WIEDZA", "UCZEŃ", "WYNIK",

    # City
    "ULICA", "RYNEK", "HOTEL", "SKLEP", "TEATR", "BASEN", "URZĄD",
    "POCZTA", "WIEŻA", "ZAMEK", "LOKAL",

    # Transport
    "METRO", "ROWER", "ŁÓDKA", "SANIE", "SZYBA", "OPONA", "PILOT",

    # Professions
    "AKTOR", "POETA", "MUZYK", "RYBAK", "SZEWC", "KELNER", "KASJER",
    "AGENT",

    # Common adjectives
    "DOBRY", "CICHY", "WOLNY", "STARY", "MŁODY", "SILNY", "SŁABY",
    "WAŻNY", "PEWNY", "GRUBY", "CHUDY", "NISKI", "DŁUGI", "WĄSKI",
    "JASNY", "ZIMNY", "MOKRY", "SUCHY", "CHORY", "PEŁNY", "PUSTY",
    "GĘSTY", "KAŻDY", "KTÓRY", "JEDEN", "DRUGI", "PIĄTY", "BIAŁY",
    "SZARY", "ZŁOTY", "ŻÓŁTY", "OSTRY", "RÓWNY", "STAŁY", "MIŁY",
    "NOWY", "DUMNY", "LETNI", "LEKKI",

    # Common verbs
    "ROBIĆ", "PISAĆ", "MÓWIĆ", "LUBIĆ", "LATAĆ", "UCZYĆ", "KUPIĆ",
    "LEŻEĆ", "WSTAĆ", "PÓJŚĆ", "WEJŚĆ", "IDZIE", "GONIĆ", "GUBIĆ",
    "BAWIĆ",

    # Colors
    "LILIA",

    # Time
    "JEDEN", "OSIEM", "SZEŚĆ", "DZIEŃ", "ŚRODA", "PÓŹNO", "NIGDY",
    "TERAZ", "POTEM", "DAWNO", "EPOKA",

    # Abstract
    "SŁOWO", "WYNIK", "POWÓD", "TREŚĆ", "MODEL", "KOSZT", "PRACA",
    "CECHA", "FORMA", "NORMA", "GNIEW", "WSTYD", "ŻYCIE", "ŚWIAT",
    "WIARA", "POKÓJ", "PLANY", "MYŚLI", "SKUTEK", "BŁĄD", "SEKRET",
    "PRAWO", "WZÓR", "KREDYT", "STRATA", "BUDŻET", "OPŁATA", "WYROK",
    "KARA", "NAGRODA", "PROJEKT", "ZMIANA", "EFEKT",

    # Common nouns
    "ZAMEK", "KARTA", "TORBA", "ZEGAR", "PAŁAC", "STRÓJ", "BITWA",
    "WALKA", "ARMIA", "SZANSA", "SCENA", "SERIA", "SEZON", "SIANO",
    "SKARB", "WIARA", "WICHER", "WIDOK", "ZEMSTA", "ZAGADKA", "ZAMACH",
    "ZAPAS", "ZARAZA", "ZAWAŁ", "ZDRÓJ", "ZIELE", "ZJAZD", "ZŁOTO",
    "ZMROK", "ZNAWCA", "ZORZA", "ŻYWICA", "RYNEK", "RANEK", "RAZEM",
    "SALON", "SALDO", "SATYNA", "SUWAK", "SYMBOL", "TAFLA", "TAJGA",
    "TAJNY", "TALAR", "TALIA", "TANIEC", "TAPIR", "TARAN", "TCHÓRZ",
    "TENIS", "TENOR", "TERMOS", "TIARA", "TOPÓR", "TRAKT", "TULEJA",
    "TYFUS", "WABIK", "WALET", "WARGI", "WARTA", "WATAHA", "WĄSY",
    "WDECH", "WIRUS", "WOJSKO", "WÓZEK", "WYMIAR", "WYRAZ", "WZROST",
    "ŻAGIEL", "ŻARÓWKA", "ŻEBRO", "ŻONKIL", "ŻÓŁTKO", "ŻURAW", "ŻUŻEL",
    "NACISK", "NAWET", "OCZKO", "OLEJ", "ORZECH", "PACZKA", "PASJA",
    "PERŁA", "PIKNIK", "PLACEK", "PLAMA", "POJAZD", "POLANO", "POMPA",
    "PORTAL", "POSADA", "PRÓBKA", "PROCH", "PROFIL", "PROTON", "PUCHAR",
    "PUNKT", "PUSZKA", "RYWAL", "SAPER", "SIEĆ", "SŁOIK", "SMAK",
    "SPRAWA", "SROKA", "STADO", "STOK", "STREFA", "SUKNIA",
    "ABARY", "ADEPT", "AFERA", "AGAWA", "AGENT", "AGORA", "AKCJA",
    "AKCJE", "AKORD", "AKTYW", "AKWEN", "ALARM", "ALEJA", "ALOES",
    "AMEBA", "AMPER", "ANEKS", "ANIOŁ", "ANODA", "AORTA", "ARSEN",
    "AUDYT", "AWANS", "AWERS", "AZURY",
    "BAGAŻ", "BAJKA", "BALET", "BALON", "BANDA", "BILET", "BIZON",
    "BLASK", "BŁOTO", "BRYŁA", "BUFOR", "BURAK", "BURTA", "CEBER",
    "CIAŁO", "CIĄŻA", "DEKOR", "DESKI", "DESKA", "DETAL", "DIETA",
    "DOBRE", "DOMEK", "DOWÓD", "DRAKA", "DRWAL",
    "FAJKA", "FARBA", "FESTA", "FIKUS", "FILTR", "FLIRT", "FOTON",
    "GALOP", "GAMMA", "GODŁO", "GOTYK", "GRACJA", "GRANAT",
    "HAŁAS", "HAMAK", "HARFA", "IKONA", "IMPAS", "INDYK",
    "JAGODA", "JAWOR", "JUTRO", "KAMYK", "KANAŁ", "KATAR", "KLAUN",
    "KOLBA", "KOLEC", "KOMIK", "KORAL", "KREDA", "KREDO", "KRZYŻ",
    "KUPIEC", "LARUM", "ŁAWKA", "LEDWO", "LEMUR", "LOTOS", "LOTKA",
    "MAFIA", "MANIA", "MANTRA", "METAN", "MOTYW", "MUNDUR",
    "CHATA", "BELKA", "BELKI", "BOBEK", "BOŻEK", "BRONA", "BURZE",
    "BAGNA", "BRZEG", "FIOŁEK", "CHABER", "MACZKA",
    "ALBUM", "BOLERO", "BUDA", "CYMBAL", "CYTAT", "DRÓŻKA",
    "FLAGA", "FRESK", "FUTRO", "GAZELA", "GIERMEK", "GONIEC",
    "GONDOLA", "GORYLA", "HEJNAŁ", "HUSARZ", "IDEAŁ", "KABAŁA",
    "KAJAK", "KAPELA", "KARTKA", "KAWAŁ", "KIELICH", "KLATKA",
    "KLUSKI", "KMIOTEK", "KOGUT", "KOLCZYK",
    "KOPERTA", "KOSMOS", "KRYSZTAŁ", "KUFEL", "LAURKA", "LAWENDA",
    "LEŚNIK", "LUSTRO", "ŁABĘDŹ",
    "MAZUREK", "MELON", "MNICH", "MOTŁOCH",
    "NOBIS", "NÓŻKA", "NURT",
    "OBRAZA", "OKAZJA", "OKRUCHY",
    "PESTKA", "PILNIK", "PLASTER", "POKUTA", "PREZENT",
    "RABUŚ", "REBUS", "RELIKT", "RĘKAW", "RONDEL", "RUDZIK",
    "RUINA", "RULETA", "RZEMYK", "RZUTKI",
    "SAPA", "SIEROTA", "SIEWCA", "SKOCZEK",
    "STANGRET", "SZARADA", "SZATNIA", "SZEWCZYK",
    "TALERZYK", "TAPCZAN", "TARTAK", "TEKTURKA",
    "TŁUMIK", "TOPOLA", "TRZASK", "TULIPAN",
    "TYFUS", "TYSIĄCZEK", "UCINAK", "UPARTY",
    "USZATEK", "UTARCZKA",
    "WABIENIE", "WALEC", "WARCABY", "WARTKI",
    "WAZA", "WESOŁEK", "WIEPRZ",
    "WIŚNIK", "WOLANT", "WORECZEK",
    "WZGARDA", "ZACIĄĆ", "ZAGAJNIK",
    "ZAMĘT", "ZAROSTEK", "ZBIORNIK",
    "ZIELSKO", "ZIEMNY", "ZNÓJ", "ZWÓJ",
    "ŻACZEK", "ŻAGIEW", "ŻAŁOSNY", "ŻELAZO",
    "ŻMIJA", "ŻYWNOŚĆ",
    # More common everyday words
    "DĄBEK", "KONAR", "PĄKEK", "PIASEK", "KAMIEŃ",
    "JASION", "FILET", "FIOLEK",
    "GĄSKA", "JELENIE", "LEŻEĆ",
    "DRZEWO", "TRÓJKA", "SETKA",
    "SŁOWNIK", "TECZKA", "GAZETA",
    "PRĄD", "NAPIĘCIE", "OPÓR",
    "WITRYNA", "SKLEPIK", "STRAŻ",
    "LIPCOWY", "DAWNOŚĆ", "CHWILĘ",
    "LICZBA", "SZYBKO", "GŁUPIO",
    "MOCNO", "CIEPŁO", "SMĘTNIE",
    "RADOŚNIE", "SPOKOJNIE",
]

# Build word lists
all_candidates = clean(MASTER + SOLUTIONS_HAND)
solutions = clean(SOLUTIONS_HAND)

# Ensure solutions is subset of all
all_words_set = set(all_candidates) | set(solutions)
all_words = sorted(all_words_set)

print(f"Solutions: {len(solutions)}")
print(f"All words: {len(all_words)}")

# Write files
os.makedirs("/home/user/c/GameAggregator/GameAggregator/Resources", exist_ok=True)

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_solutions.txt", "w", encoding="utf-8") as f:
    for w in solutions:
        f.write(w + "\n")

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_words.txt", "w", encoding="utf-8") as f:
    for w in all_words:
        f.write(w + "\n")

print("Files written.")

# Verify
with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_solutions.txt", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip()]
bad = [w for w in lines if len(w) != 5]
print(f"Bad-length solutions: {len(bad)} {bad[:10] if bad else ''}")

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_words.txt", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip()]
bad = [w for w in lines if len(w) != 5]
print(f"Bad-length words: {len(bad)} {bad[:10] if bad else ''}")

sol_set = set(solutions)
word_set = set(all_words)
missing = sol_set - word_set
print(f"Solutions not in word list: {len(missing)}")
