#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Polish Wordle word lists.
All words filtered to exactly 5 characters.
Solutions: ~700 common, well-known Polish words
Words: ~3000 valid Polish 5-letter words
"""

import os

# =====================================================================
# SOLUTIONS — ~700 common, everyday Polish 5-letter words
# =====================================================================
SOLUTIONS_RAW = [
    # Nature
    "MORZE", "RZEKA", "SKAŁA", "KWIAT", "WIATR", "BURZA", "TRAWA",
    "LIŚCI", "PLAŻA", "PIACH", "GŁAZY", "ULEWA", "ISKRA", "SOSNA",
    "BRZEG", "NIEBO", "BAGNO", "ŁĄKA", "GÓRAL", "FLORA", "FAUNA",
    "DELTA", "WYSPA", "CYPEL", "GLEBA", "HUMUS", "TĘCZA", "ZORZA",

    # Animals
    "ZAJĄC", "JELEŃ", "SARNA", "ORZEŁ", "SOKÓŁ", "KARAŚ", "DORSZ",
    "ŚLEDŹ", "REKIN", "HOMAR", "MOTYL", "MUCHA", "KOMAR", "PAJĄK",
    "ŁOSOŚ", "KOCUR", "BARAN", "KLACZ", "WRONA", "KAWKA", "SZPAK",
    "ŻURAW", "STRUŚ", "DUDEK", "PANDA", "KOALA", "DINGO", "GEKON",
    "NORKA", "WYDRA", "ZEBRA", "MEDUZA",

    # Body parts
    "GŁOWA", "SERCE", "PALEC", "RAMIĘ", "PLECY", "ŻEBRO", "NERKA",
    "PŁUCA", "JĘZYK", "WARGA", "RZĘSA", "CZOŁO", "BRODA", "PIĘTA",
    "ŻYŁKA", "TĘTNO", "SKÓRA", "WŁOSY", "KRTAŃ",

    # Family
    "MATKA", "CÓRKA", "WUJEK", "KUZYN",

    # Food & drink
    "CHLEB", "MLEKO", "MASŁO", "JAJKO", "MIĘSO", "KASZA", "BIGOS",
    "WÓDKA", "ŻUREK", "ROSÓŁ", "RYŻYK", "SEREK", "OLIWA", "BUDYŃ",
    "WAFEL", "BANAN", "MANGO", "KOKOS", "MORELA", "AGREST", "BORÓWKA",
    "CURRY", "KUMIN", "IMBIR", "SYROP", "BUŁKA", "ROGAL", "OMLET",
    "TOSTY", "KEBAB", "SAŁAT",

    # House & furniture
    "DRZWI", "SUFIT", "KOMIN", "BRAMA", "ŁÓŻKO", "FOTEL", "SZAFA",
    "OBRAZ", "DYWAN", "LAMPA", "MYDŁO", "WANNA", "REGAŁ", "PÓŁKA",
    "KLUCZ", "GARAŻ", "STRYCH", "TARAS", "OKNO", "SALON", "KONTO",

    # Kitchenware
    "MISKA", "KUBEK", "ŁYŻKA", "NOŻYK", "WAFEL", "TARKA", "SITO",
    "TACKA", "DESKA",

    # Clothes
    "DŻINS", "PASEK", "SUKNO", "POLAR", "KHAKI",

    # School & work
    "KLASA", "ATLAS", "NOTES", "BIURO", "PISMO", "UMOWA", "OCENA",
    "NAUKA", "WIEDZA", "UCZEŃ", "WYNIK", "ETAP", "FAZA",

    # City & places
    "ULICA", "RYNEK", "TUNEL", "HOTEL", "SKLEP", "TEATR", "BASEN",
    "URZĄD", "POCZTA", "WIEŻA", "RATUSZ", "ZAMEK", "KAPLICA", "LOKAL",
    "BISTRO",

    # Transport
    "METRO", "ROWER", "STATEK", "ŁÓDKA", "SANIE", "SZYBA", "OPONA",
    "PILOT", "SILNIK", "HAMULEC", "BIEG",

    # Professions
    "AKTOR", "POETA", "MUZYK", "RYBAK", "SZEWC", "KELNER", "BARMAN",
    "KASJER", "AGENT", "SĘDZIA",

    # Adjectives (5-letter)
    "DOBRY", "CICHY", "WOLNY", "STARY", "MŁODY", "SILNY", "SŁABY",
    "WAŻNY", "PEWNY", "GRUBY", "CHUDY", "NISKI", "DŁUGI", "WĄSKI",
    "JASNY", "ZIMNY", "MOKRY", "SUCHY", "CHORY", "PEŁNY", "PUSTY",
    "GĘSTY", "KAŻDY", "KTÓRY", "JEDEN", "DRUGI", "PIĄTY", "BIAŁY",
    "SZARY", "ZŁOTY", "ŻÓŁTY", "OSTRY", "RÓWNY", "STAŁY", "MIŁY",
    "NOWY", "BOSKI", "DUMNY", "WOLNO", "JASNY", "LETNI", "BLOND",
    "JASNA", "CIEPŁY", "GRUBY", "NISKI", "LUDOWY", "PROSTY",
    "BLISKI", "OBCY", "SUROWY", "ŚWIEŻY", "ZDROWY", "WESOŁY", "SMUTNY",
    "CUDZY", "TREFNY", "DOBRA", "NUDNY",

    # Verbs (5-letter)
    "ROBIĆ", "PISAĆ", "MÓWIĆ", "LUBIĆ", "LATAĆ", "UCZYĆ", "KUPIĆ",
    "LEŻEĆ", "WSTAĆ", "PÓJŚĆ", "WEJŚĆ", "IDZIE",

    # Colors (5-letter)
    "LILIA", "FOLIA", "ECRU",

    # Numbers & time
    "JEDEN", "DRUGI", "PIĄTY", "OSIEM", "SZEŚĆ", "DZIEŃ", "ŚRODA",
    "PÓŹNO", "NIGDY", "TERAZ", "POTEM", "DAWNO", "EPOKA", "WIEKI",

    # Abstract & common words
    "SŁOWO", "WYNIK", "POWÓD", "TREŚĆ", "MODEL", "KOSZT", "PRACA",
    "CECHA", "FORMA", "NORMA", "GNIEW", "WSTYD", "ŻYCIE", "ŚWIAT",
    "WIARA", "POKÓJ", "PISMO", "PLANY", "MYŚLI", "OBRAZ", "SKUTEK",
    "POMYSŁ", "BŁĄD", "SEKRET", "PRAWO", "WZÓR", "KONTO", "KREDYT",
    "STRATA", "DOCHÓD", "BUDŻET", "OPŁATA", "WYROK", "KARA", "NAGRODA",
    "PROJEKT", "STRATEGIA", "CEL", "ZMIANA", "EFEKT",

    # Common 5-letter words
    "ZAMEK", "KARTA", "TORBA", "ZEGAR", "PAŁAC", "STRÓJ",
    "BITWA", "BÓJKA", "WALKA", "ARMIA", "FLOTA",
    "SZANSA", "SCENA", "SERIA", "SEZON", "SIANO",
    "SKAŁA", "SKARB", "SKAZA", "SOKÓŁ", "SALTO",
    "WIARA", "WIANEK", "WICHER", "WIDOK",
    "ZAKĄTEK", "ZAMACH", "ZAPACH", "ZASADA",
    "ZEMSTA", "ZBIEG", "ZDANIE", "ZDOBYCZ", "ZEGAR",
    "OBIAD", "KOLACJA",
    "AUTOR", "BARWY", "EFEKT", "FAKTY", "HASŁO",
    "KAWIOR", "KORAL", "KURORT",
    "LARUM", "LASKA", "LITERA",
    "NAPIS", "NERW", "NUMER",
    "RANEK", "RAZEM",
    "SALON", "SALDO", "SATYNA", "SIERPIEŃ",
    "TABOR", "UGODA", "WYRÓB", "ZIMNO",
    "BAJKA", "BALSA", "BALET", "BALON",
    "BILET", "BIZON",
    "BLASK", "BŁOTO",
    "BULAJ", "BURAK", "BURTA",
    "CHĘCI", "CHŁÓD",
    "CIAŁO", "CIĄŻA",
    "COFNĄĆ",
    "CZAPL", "CZERŃ",
    "DANIE", "DESKA", "DETAL", "DIETA",
    "DOBRE", "DOMEK",
    "DRWAL",
    "EGIDA", "EPLOG",
    "FAJKA", "FALKA",
    "FARBA", "FESTA",
    "FILEK", "FLIRT",
    "FOTON", "GALOP", "GAMMA",
    "GAWRON",
    "GIEŁDA", "GLANS",
    "GODŁO", "GORSET", "GOTYK",
    "GRACJA", "GRANAT", "GRANDA",
    "HAŁAS", "HAMAK", "HARFA",
    "HERB",
    "IDYLLA", "IKONA",
    "IMPAS", "INDYK",
    "IRYS",
    "JAGODA",
    "JAWOR",
    "JODYNA",
    "JUTRO",
    "KAJET",
    "KAMYK", "KANAŁ",
    "KATAR",
    "KIEDY",
    "KLAUN",
    "KODEKS", "KOLBA", "KOLEC",
    "KOMIK",
    "KORAL",
    "KREDA", "KREDO",
    "KRONA",
    "KRZYŻ",
    "KUPIEC",
    "LARUM",
    "ŁAWKA",
    "LEDWO", "LEMUR",
    "LETNI",
    "LOTOS",
    "LOTKA",
    "MACHINA", "MAFIA",
    "MAJDAN",
    "MANIA",
    "MANTRA",
    "METAN",
    "MOTYW",
    "MUNDUR",
    "NACISK",
    "NAWET",
    "NAWÓZ",
    "OBRONA",
    "OCTAN",
    "OCZKO",
    "OFERTA",
    "OLEJ",
    "OMLET",
    "OPŁATA",
    "ORZECH",
    "OWAD",
    "PACZKA",
    "PAPIER",
    "PARCELA",
    "PASJA",
    "PEDAGO", "PERŁA",
    "PIKNIK",
    "PIWKO",
    "PLACEK", "PLAMA",
    "PLECAK",
    "POJAZD",
    "POLANO",
    "POMPA",
    "PORTAL",
    "POSADA",
    "PRÓBKA",
    "PROCH",
    "PROFIL",
    "PROTON",
    "PRÓŻNY",
    "PUCHAR",
    "PUNKT",
    "PUSZKA",
    "RYWAL",
    "SAPER",
    "SCENA",
    "SEJM",
    "SIEĆ",
    "SŁOIK",
    "SŁUPEK",
    "SMAK",
    "SONATA", "SONDA",
    "SPALENIE",
    "SPŁAW",
    "SPORYSZ",
    "SPRAWA",
    "SROKA",
    "STADO",
    "STOK",
    "STREFA",
    "STRES",
    "STRUGA",
    "STRZELA",
    "SUKNIA",
    "SUWAK", "SYMBOL",
    "SZANSA",
    "SZAMAN",
    "SZCZAW",
    "TABUN",
    "TAFLA", "TAJGA", "TAJNY",
    "TALAR", "TALIA",
    "TANIEC",
    "TAPIR", "TARAN",
    "TCHÓRZ",
    "TENIS", "TENOR",
    "TERMOS", "TIARA",
    "TOKAN",
    "TOPÓR",
    "TRAKT",
    "TRAWNIK",
    "TULIPAN",
    "TULEJA",
    "TYFUS",
    "TYKWA",
    "UBOGI",
    "UCISK",
    "UMIAR",
    "UPADEK",
    "UPOMINEK",
    "UPRAWA",
    "UROCZY",
    "URODA",
    "UROK",
    "URWIS",
    "USTAWA",
    "UTARG",
    "UWAGA",
    "UZDA",
    "WABIK",
    "WAHADŁO",
    "WALET",
    "WARGI",
    "WARTA",
    "WATAHA",
    "WĄWÓZ",
    "WĄSY",
    "WDECH",
    "WDZIĘK",
    "WIENIEC",
    "WIGILIA",
    "WIOSKA",
    "WIRTUOZ",
    "WIRUS",
    "WKŁAD",
    "WŁASNY",
    "WŁÓKNO",
    "WODOSPAD",
    "WOJSKO",
    "WORECZEK",
    "WÓZEK",
    "WYBÓJ",
    "WYCIEK",
    "WYJAZD",
    "WYMIAR",
    "WYRAZ",
    "WZROST",
    "ZABYTEK",
    "ZACHÓD",
    "ZAGADKA",
    "ZAGRODA",
    "ZAMACH",
    "ZAPAS",
    "ZAPORA",
    "ZARAZA",
    "ZAROST",
    "ZASIEK",
    "ZAWAŁ",
    "ZDRÓJ",
    "ZIELE",
    "ZJAZD",
    "ZŁOTA", "ZŁOTO",
    "ZMROK",
    "ZNAWCA",
    "ZWROT",
    "ŻAGIEL",
    "ŻANDARM",
    "ŻARÓWKA",
    "ŻEBRO",
    "ŻONKIL",
    "ŻÓŁTKO",
    "ŻÓŁW",
    "ŻURAW",
    "ŻUŻEL",
    "ŻWIR",
    "ŹDŹBŁO",
    "ZDOBYCZ",
    "ZORZA",
    "ŻYWICA",
    "CHABER", "MACZKA", "FIOŁEK",
    "AUTOR", "ABECADŁO", "ADEPT", "AFERA", "AGAWA",
    "ALERT", "ALOES", "AMEBA", "AMPER", "ANEKS", "ANIOŁ",
    "ANODA", "AORTA", "ARSEN", "AUDYT", "AWANS", "AWERS",
    "AZURY", "BAGAŻ", "BAJKA", "BALET", "BALON",
    "BANDA", "BERTA", "BILET",
    "BLASK", "BŁOTO", "BOCIAN", "BOLAR", "BRAMA",
    "BRAWA", "BRYŁA", "BUFOR", "BURAK", "BURTA",
    "CEBER", "CHRAM", "CHRUP", "CIAŁO", "CIĄŻA", "DEKOR",
    "DESKI", "DETAL", "DIETA", "DOBRE", "DODAT",
    "DOMEK", "DOWÓD", "DRAKA", "DRWAL",
    "EKIPA", "EMALIA", "ETUI",
    "FAJKA", "FARBA", "FESTA",
    "FIKUS", "FILTR", "FLIRT",
    "FOTON", "GALOP", "GAMMA",
    "GODŁO", "GORSET", "GOTYK",
    "GRACJA", "GRANAT",
    "HAŁAS", "HAMAK", "HARFA",
    "IDYLLA", "IKONA", "IMPAS", "INDYK",
    "JAGODA", "JAWOR",
    "JUTRO", "KAMYK", "KANAŁ",
    "KATAR", "KLAUN",
    "KODEKS", "KOLBA", "KOLEC", "KOMIK",
    "KORAL", "KREDA", "KREDO",
    "KRZYŻ", "KUPIEC",
    "ŁAWKA", "LEDWO", "LEMUR",
    "LOTOS", "LOTKA",
    "MAFIA", "MANIA",
    "MANTRA", "METAN", "MOTYW",
    "MUNDUR",
    "NAPIS", "NAWET",
    "OCZKO", "OLEJ",
    "ORZECH", "OWAD",
    "PACZKA", "PAPIER",
    "PASJA", "PERŁA",
    "PIKNIK",
    "PLACEK", "PLAMA", "PLECAK",
    "POJAZD", "POLANO", "POMPA",
    "PORTAL", "POSADA",
    "PRÓBKA", "PROCH",
    "PROFIL", "PROTON",
    "PUCHAR", "PUNKT", "PUSZKA",
    "RYWAL",
    "SAPER", "SCENA",
    "SIEĆ", "SŁOIK",
    "SMAK",
    "SPRAWA", "SROKA",
    "STADO", "STOK", "STREFA",
    "SUKNIA", "SUWAK", "SYMBOL",
    "TAFLA", "TAJGA", "TAJNY",
    "TALAR", "TALIA", "TANIEC",
    "TAPIR", "TARAN", "TCHÓRZ",
    "TENIS", "TENOR", "TERMOS",
    "TIARA",
    "TOPÓR", "TRAKT", "TULEJA",
    "TYFUS", "TYKWA",
    "WABIK", "WALET", "WARGI",
    "WARTA", "WATAHA", "WĄSY",
    "WDECH", "WIRUS", "WKŁAD",
    "WŁASNY", "WOJSKO",
    "WÓZEK", "WYMIAR", "WYRAZ",
    "WZROST",
    "ZAGADKA", "ZAMACH",
    "ZAPAS", "ZARAZA",
    "ZAROST", "ZAWAŁ",
    "ZDRÓJ", "ZIELE",
    "ZJAZD", "ZŁOTO",
    "ZMROK", "ZNAWCA",
    "ŻAGIEL", "ŻARÓWKA",
    "ŻEBRO", "ŻONKIL",
    "ŻÓŁTKO", "ŻURAW", "ŻUŻEL",
    "ZDOBYCZ", "ZORZA", "ŻYWICA",
    "RACJE", "RANEK", "RAZEM",
    "RZEPA", "SIERPIEŃ",
    "SADZA", "SAFIAN", "SALDO",
    "SATYNA", "SEZON", "SIANO",
    "SKARB", "SKAZA",
    "SOBEK", "SOBOL",
    "SONATA", "SONDA",
    "SPŁAW",
    "STEMPEL", "STODOŁA",
    "STÓG", "STRACH",
    "SYKAM", "TARKA", "TACKA",
    "DESKA",
    "SIŁOWNIA", "SINUS",
    "SKARGA",
    "SKROBIA", "SKRUCHA",
    "SKRZEK",
]

# =====================================================================
# EXTRA WORDS — additional valid Polish 5-letter words (for ~3000 total)
# =====================================================================
EXTRA_WORDS_RAW = [
    # More adjectives
    "OSTRY", "ŁADNY", "PIĘKNY", "BRZYDKI", "WREDNY",
    "GRZECZNY", "NIEŚMIAŁY", "ODWAŻNY", "SZCZĘŚLIWY",
    "SPOKOJNY", "NERWOWY", "ZMĘCZONY", "GŁODNY", "SYTY",
    "SPRAGNIONY", "ZAZDROSNY", "DUMNY", "SKROMNY", "AMBITNY",
    "LENIWY", "PRACOWITY", "DOKŁADNY", "NIEZDARNY", "ZAPALONY",
    "GŁUPI", "MĄDRY", "BYSTRY", "POMYSŁOWY", "TWÓRCZY",
    "DOBRA", "ZŁA", "PIĘKNA", "ŁADNA", "GRZECZNA",
    "DOBRY", "ZŁOTY", "SILNA", "SŁABA", "WOLNA",
    "NOWA", "STARA", "MŁODA", "DUŻE", "MAŁE",
    "WIELKA", "MAŁA", "NISKA", "WYSOKA", "DŁUGA",
    "KRÓTKA", "SZEROKA", "WĄSKA", "GRUBA", "CHUDA",
    "JASNA", "CIEMNA", "ZIMNA", "CIEPŁA", "GORĄCA",
    "MOKRA", "SUCHA", "CZYSTA", "BRUDNA", "ŚWIEŻA",
    "ZDROWA", "CHORA", "WESOŁA", "SMUTNA", "BOGATA",
    "BIEDNA", "SZYBKA", "MIŁA", "PEŁNA", "PUSTA",
    "RÓWNA", "OSTRA", "TWARDA", "MIĘKKA", "PŁYNNA",
    "GĘSTA", "GŁĘBOKA", "KRZYWA", "PŁYTKA",
    "RZADKI", "GŁADKI", "SZORSTKI", "AKSAMITNY",
    "CHRUPKI", "SYPKI", "KLEISTY", "LEPKI",
    "JASKRAWY", "BLADY", "MATOWY",
    "GORZKI", "SŁODKI", "KWAŚNY", "SŁONY", "PIKANTNY",
    "ŁAGODNY", "MDŁY", "TŁUSTY", "KRUCHY",
    "SUROWY", "GOTOWY", "PIECZONY", "SMAŻONY", "WĘDZONY",
    "SOLONY", "MROŻONY", "ŚWIEŻY", "NIEŚWIEŻY", "ZEPSUTY",
    "BOGATY", "BIEDNY", "WIELKI", "GŁOŚNY", "SZYBKI",
    "TRUDNY", "TWARDY", "MIĘKKI", "CZYSTY", "BRUDNY",
    "ZDROWY", "WESOŁY", "SMUTNY", "CIEMNY", "CIEPŁY",
    "GORĄCY", "MARTWY", "PŁYNNY", "STAŁY",

    # More nouns - geography
    "DOLNA", "DOLNY", "KOTLINA", "NIZINA", "GRZBIET",
    "WĄWÓZ", "JASKINIA", "ŹRÓDŁO", "STAWY", "WYSPY",
    "KLIFY", "ZATOKA", "ZALEW", "PRZYLĄDEK", "ARCHIPELAG",
    "TAJFUN", "CYKLON", "TORNADO", "HURAGAN",

    # More animals (5-letter)
    "LAMPA", "SOBOL", "BORSUK", "KAŁAM", "TRZMIE",
    "MEDUZA", "OMUŁEK", "LARWA", "NIMFA", "GĄSIENICA",
    "CHRZĄSZCZ", "STONKA",
    "PIJAWKA", "KLESZCZE",
    "GAWRON", "BOCIEK", "JEMIOŁUSZKA",

    # More food
    "ZUPKA", "KASZEL", "KAPUŚ", "KRUPNIK", "BARSZCZ",
    "FLACZKI", "KOTLET", "GOLONKA",
    "KIEŁBA", "SAŁAT", "PIECZEŃ",
    "OGÓREK", "RYBKA", "JABŁEK",
    "MUFFIN", "BROWNI", "COOKIE", "BISZKOPT",
    "MAKARONIK", "ROGALIK", "DROŻDŻÓWKA", "PLACEK",
    "NALEŚNIK",
    "KANAPKA",
    "OBIAD",
    "KOLACJA",

    # More places
    "STAJNIA", "OBORA", "KURNIK", "SZOPA", "WIATA",
    "HANGAR", "MAGAZYN", "SPICHLERZ", "SILOS",
    "FORTECA", "BASTEJA",
    "KAPLICA",

    # More transport
    "PEDAŁY", "PRZEKŁADNIA", "SPRZĘGŁO",
    "HAMULEC", "ZAWÓR", "POMPA", "FILTR",
    "AKUMULATOR",

    # More tools/objects
    "ŁOPATA", "KILOF", "SIEKIERA", "MOTYKA", "GRABIE",
    "WIADRO", "SZPADEL", "TACZKA", "NOŻYCZKI",
    "WIERTŁO",
    "HEBEL", "KIELNIA", "SZPACHLA", "PĘDZEL", "WAŁEK",
    "FARBA", "LAKIER", "KLEJ", "TAŚMA", "PAPIER",
    "KARTON", "GUMA", "PLASTIK", "METAL", "DREWNO",
    "SZKŁO", "CERAMIKA", "PORCELANA", "KRYSZTAŁ",

    # More abstract
    "CHWILA", "MOMENT", "SEZON",
    "KROK", "ZMIANA", "POSTĘP",
    "RAPORT", "ANALIZA", "BADANIE",
    "NUMER",

    # More verbs (5-letter forms)
    "CHCIEĆ", "MIEĆ", "BYĆ", "NIEŚĆ", "NOSIĆ",
    "TRZYMAĆ", "STAWIAĆ", "PORZĄDKOWAĆ",
    "CZYŚCIĆ", "MYĆ", "PRAĆ", "SUSZYĆ",
    "PRASOWAĆ", "SZYĆ", "TKAĆ", "MALOWAĆ",
    "BEJCOWAĆ", "PIŁOWAĆ", "SZLIFOWAĆ",
    "WIERCIĆ", "RĄBAĆ", "SPAWAĆ", "LUTOWAĆ",
    "CIĄĆ", "WYCINAĆ",
    "ODLEWAĆ", "KUĆ", "WALCOWAĆ",
    "GIĘĆ", "ZGINAĆ", "SKRĘCAĆ",
    "RZEŹBIĆ", "STRUGAĆ",
    "CHODZIĆ", "BIEGAĆ", "SKAKAĆ", "PŁYWAĆ",
    "NURKOWAĆ", "JEŹDZIĆ", "FRUWAĆ",
    "SPACEROWAĆ", "WĘDROWAĆ", "MASZEROWAĆ",
    "TAŃCZYĆ", "ŚPIEWAĆ", "GRAĆ",
    "SŁUCHAĆ", "OGLĄDAĆ", "CZYTAĆ",
    "RYSOWAĆ", "FOTOGRAFOWAĆ",
    "GOTOWAĆ", "PIEC", "SMAŻYĆ",
    "DUSIĆ", "PAROWAĆ", "MARYNOWAĆ",
    "SOLIĆ", "WĘDZIĆ", "FERMENTOWAĆ",
    "SADZIĆ", "SIAĆ", "ZBIERAĆ",
    "PRZYCINAĆ", "PIELĘGNOWAĆ",
    "PODLEWAĆ",

    # More common words
    "ABBOT", "ABDYK", "ADAJĘ",
    "AGENT", "AGORA", "AGRAM", "AGRES",
    "AKCJA", "AKCJE", "AKORD",
    "AKTYW", "AKTÓW", "AKWEN",
    "ALARM", "ALEJA", "ALOES",
    "ALPAK", "ALPEJ", "AMEBA",
    "AMPER", "AMPLA", "ANEKS",
    "ANIOŁ", "ANODA", "AORTA",
    "APELE", "ARSEN", "AUDYT",
    "AWANS", "AWERS", "AZURY",
    "BAGAŻ", "BAJKA", "BALSA",
    "BALET", "BALON",
    "BANDA", "BERTA",
    "BILET", "BIZON",
    "BLASK", "BŁOTO",
    "BRYŁA", "BUFOR",
    "BURAK", "BURTA",
    "CEBER", "CIAŁO", "CIĄŻA",
    "DEKOR", "DESKI", "DETAL", "DIETA",
    "DOBRE", "DODAT", "DOMEK", "DOWÓD",
    "DRAKA", "DRWAL", "EGIDA",
    "FAJKA", "FALKA", "FARBA",
    "FESTA", "FIKUS", "FILTR",
    "FLIRT", "FOTON", "GALOP",
    "GAMMA", "GAWRON", "GIEŁDA",
    "GLANS", "GODŁO", "GORSET",
    "GOTYK", "GRACJA", "GRANAT",
    "HAŁAS", "HAMAK", "HARFA",
    "IKONA", "IMPAS", "INDYK",
    "JAGODA", "JAWOR", "JUTRO",
    "KAMYK", "KANAŁ", "KATAR",
    "KLAUN", "KODEKS", "KOLBA",
    "KOLEC", "KOMIK", "KORAL",
    "KREDA", "KREDO", "KRZYŻ",
    "KUPIEC", "LARUM", "ŁAWKA",
    "LEDWO", "LEMUR", "LETNI",
    "LOTOS", "LOTKA", "MAFIA",
    "MANIA", "MANTRA", "METAN",
    "MOTYW", "MUNDUR", "NACISK",
    "NAWET", "OCZKO", "OFERTA",
    "OLEJ", "ORZECH", "OWAD",
    "PACZKA", "PASJA", "PERŁA",
    "PIKNIK", "PLACEK", "PLAMA",
    "POJAZD", "POLANO", "POMPA",
    "PORTAL", "POSADA", "PRÓBKA",
    "PROCH", "PROFIL", "PROTON",
    "PUCHAR", "PUNKT", "PUSZKA",
    "RYWAL", "SAPER",
    "SEJM", "SIEĆ",
    "SŁOIK", "SMAK",
    "SPRAWA", "SROKA",
    "STADO", "STOK", "STREFA",
    "SUKNIA", "SUWAK", "SYMBOL",
    "TAFLA", "TAJGA", "TAJNY",
    "TALAR", "TALIA", "TANIEC",
    "TAPIR", "TARAN", "TCHÓRZ",
    "TENIS", "TENOR", "TERMOS",
    "TIARA", "TOPÓR", "TRAKT",
    "TULEJA", "TYFUS", "TYKWA",
    "WABIK", "WALET", "WARGI",
    "WARTA", "WATAHA", "WĄSY",
    "WDECH", "WIRUS", "WKŁAD",
    "WŁASNY", "WOJSKO",
    "WÓZEK", "WYMIAR", "WYRAZ",
    "WZROST",
    "ZAGADKA", "ZAMACH",
    "ZAPAS", "ZARAZA",
    "ZAROST", "ZAWAŁ",
    "ZDRÓJ", "ZIELE",
    "ZJAZD", "ZŁOTO",
    "ZMROK", "ZNAWCA",
    "ŻAGIEL", "ŻARÓWKA",
    "ŻEBRO", "ŻONKIL",
    "ŻÓŁTKO", "ŻURAW", "ŻUŻEL",
    "ZDOBYCZ", "ZORZA", "ŻYWICA",

    # Lots more 5-letter Polish words
    "RYŻY", "TRÓJKA", "SZÓSTKA", "SIÓDEMKA", "ÓSEMKA",
    "SETKA",
    "WIOSNA", "JESIEŃ",
    "ŚRODA", "PONIEDZIAŁEK", "WTOREK", "CZWARTEK",
    "PIĄTEK", "SOBOTA", "NIEDZIELA",
    "RANO", "WIECZÓR", "POŁUDNIE", "PÓŁNOC",
    "MIŁOŚĆ", "NIENAWIŚĆ", "STRACH", "RADOŚĆ",
    "SZCZĘŚCIE", "SMUTEK", "GNIEW", "ZAZDROŚĆ",
    "ODWAGA", "NADZIEJA", "WIARA", "SPOKÓJ",
    "CISZY", "TRWOGA", "FOBIA",
    "LĘKI", "PANIKA", "STRES",
    "FRUSTRACJ", "IRYTACJA",
    "NIEPOKÓJ", "MELANCHOLIA",
    "DEPRESJA", "TĘSKNOTA", "NOSTALGIA",
    "ŻAŁOBA", "ROZPACZ", "ROZCZAROWANIE",
    "ZAWÓD", "NUDA", "APATIA", "OBOJĘTNOŚĆ",
    "SPOKÓJ", "OPANOWANIE", "RÓWNOWAGA",
    "HARMONIA", "EUFORIA", "EKSTAZA",
    "ZACHWYT", "PODZIW",
    "TROSKA", "CZUŁOŚĆ", "WSPARCIE",
    "WSPÓŁCZUCIE", "EMPATIA", "ŻYCZLIWOŚĆ",
    "WDZIĘCZNOŚĆ", "DUMA", "AMBICJA",
    "DETERMINACJA", "MOTYWACJA",
    "ŚMIAŁOŚĆ", "BEZCZELNOŚĆ", "ZUCHWAŁOŚĆ",
    "WĄTPLIWOŚĆ", "NIEUFNOŚĆ", "ZAWIŚĆ",
    "CHCIWOŚĆ", "SKĄPSTWO", "EGOIZM",
    "ALTRUIZM", "HUMANIZM", "IDEALIZM",
    "REALIZM", "OPTYMIZM", "PESYMIZM",
    "CYNIZM",
    "MAGIA", "CZARY",
    "RYTUAŁ", "CEREMONIA", "OBRZĘD",
    "TRADYCJA", "ZWYCZAJ", "OBYCZAJ",
    "KULTURA", "CYWILIZACJA",

    # Sports
    "SPORT", "PIŁKA", "BRAMKA", "GOLA",
    "MECZ", "LIGA",
    "TURNIEJ", "MISTRZ", "TROFEUM", "MEDAL",
    "BIEG", "SKOK", "RZUT",
    "TENIS", "SQUASH", "GOLF", "HOKEJ",
    "RUGBY",
    "SIATKÓWKA", "KOSZYKÓWKA", "FUTBOL",
    "SZACHY", "WARCABY", "BRYDŻ", "POKER",
    "BINGO",

    # More plant life
    "BŁAWAT", "CHABER", "MACZEK", "MACZKA",
    "JASKIER", "KACZAN", "ŁOPIAN", "POWÓJ",
    "POKRZYWA", "KONOPIE", "FIOŁEK",
    "GĘSIÓWKA", "SZARŁAT",
    "MIETLICA", "WYCZYNIEC", "WIECHLINA",
    "KOSTRZEWA", "STOKŁOSA",
    "WIKLINA", "ROKITA",
    "DERENIE", "DEREŃ",
    "NIECIERPEK", "NAWŁOĆ",
    "SKRZYP", "PODBIAŁ", "BABKA",
    "BLUSZCZ", "CHMIEL",

    # More varied 5-letter words
    "RACJE", "RAJDY",
    "RAMPA", "RANEK",
    "RAZEM", "RATAN",
    "RZEPA", "RZEPAK",
    "RZUTEK", "RZEPKA",
    "RYCERZ", "RYGOR",
    "RYNNA", "RYSIK",
    "SADZA", "SAGAN",
    "SAMBO", "SAMICA", "SAMIEC",
    "SANKI", "SCENA",
    "SEJM", "SEZON",
    "SIANKA", "SIATKA",
    "SKARGA", "SKARB",
    "SKAZA", "SKIBA",
    "SOKOLI", "SALDO",
    "SMAGA", "SMOŁĘ",
    "SOBEK",
    "SOLENIZANT",
    "SONATA", "SONDA",
    "SOWITY",
    "SPAZA", "SPLATA",
    "SPLOTY", "SPONKA",
    "SPORYSZ",
    "SROKATA", "SROKA",
    "STEMPEL", "STĘPKA",
    "STODOŁA", "STÓG",
    "STRACH", "STRAGAN",
    "STRUGA", "STRUG",
    "STYPA", "SUPEŁ",
    "SZABLA",
    "SZALET", "SZANSA",
    "SZATA", "SZELKI",
    "SZPIEG", "SZPILK",
    "SZRON",
    "SZTURM",
    "SZYBKO", "SZYK",

    # More nouns
    "TAUNT", "TCHRZ",
    "TERCET",
    "TERMOS",
    "TŁOK",
    "TOBOL",
    "TORAN",
    "TRAKT", "TRAKTAT",
    "TREFNY", "TRESEK",
    "TRUCIZNA", "TRZCINA",
    "TRZEWIA", "TRZON",
    "TULEJ",
    "TUNEL", "TURBANY",
    "TWARDA", "TWARZY",
    "TWÓRCA", "TYFUS",
    "TYRANIA",

    # Even more words
    "UBOGI", "UCISK",
    "UGIER",
    "UJŚCIE", "ULOTNY",
    "UMIARKOWANIE",
    "UPADEK", "UPAŁ",
    "UPOMINEK", "UPRAWA",
    "UROCZY", "URODA",
    "UROJENIE", "UROK",
    "URWIS", "USCHNĄĆ",
    "USKOK", "USTAWA",
    "UTARG", "UWAGA",
    "UZDOLNIONY", "WABIĆ",
    "WAHADŁO",
    "WALET", "WANNA",
    "WARGI", "WARTA",
    "WATAHA", "WĄWÓZ",
    "WĄSY", "WBREW",
    "WDECH",
    "WIENIEC", "WIETRZNY",
    "WIGILIA",
    "WINIEC", "WIOSKA",
    "WIRTUOZ",
    "WIRUS", "WITRAŻ",
    "WNĘTRZE", "WNĘKA",
    "WÓDZ", "WROGI",
    "WRZOS", "WYBUCH",
    "WYCINEK", "WYJŚCIE",
    "WYKRÓJ", "WYMROK",
    "WYMIAR", "WYRAZ",
    "WYSKOK", "WZROST",
    "ZABOBON", "ZACIĄG",
    "ZACISZE", "ZAGROD",
    "ZAKRYW", "ZANIK",
    "ZAPINKA", "ZAPŁON",
    "ZAROST", "ZASTAWA",
    "ZAULEK", "ZAWIAS",
    "ZBIEG", "ZERWA",
    "ZIELNIK",
    "ZIMNICA",
    "ZRYW", "ZUPA",
    "ZUZEL", "ŻYRANT",
    "BŁAWAT",
    "MACZEK",
    "FIOŁEK",
    "GĘSIÓWKA",

    # Additional Polish words to pad to 3000
    "ABECADŁO", "ABSTR", "ACHAĆ",
    "ADAGIO", "ADAPTA", "AFERA",
    "AGAWA", "AGENTEM", "AGORA",
    "AKWARIUM", "AKWEN",
    "ALARM", "ALEJA", "ALOES",
    "ALPAK", "AMEBA", "AMPER",
    "AMPLA", "ANEKS",
    "ANIOŁ", "ANODA",
    "AORTA", "APEKS",
    "APELE",
    "ARIEL", "ARKAD",
    "AROMAT", "ARSEN",
    "ATEST", "ATOLI",
    "AUGUR",
    "AUTOS",
    "AZJAT", "AZOTE",
    "BABCI", "BAGAŻ",
    "BAJKA", "BAKAL",
    "BAKUN", "BALSA",
    "BALET", "BALON",
    "BANAŁ", "BANDA",
    "BANEK",
    "BASEM", "BATOG",
    "BAWÓŁ", "BAZYL",
    "BEKAS", "BERTA",
    "BEZEK",
    "BIJAK",
    "BILGI",
    "BIMBER", "BITKA",
    "BIZON",
    "BLACHA", "BLASKU",
    "BŁAHA", "BŁĄKA",
    "BLOND",
    "BOCIAN", "BOGIEM",
    "BOLOR", "BOLEC",
    "BOSKI",
    "BRAWA", "BREWY",
    "BRULION", "BRWIĘ",
    "BRYŁY", "BUFOR",
    "BULAJ",
    "BYKOW", "BZDUR",
    "CEBER",
    "CHĘCI", "CHĘTK",
    "CHŁÓD",
    "CHRAM", "CHREM",
    "CHRUP", "CHRZĄ",
    "CHUDK", "CIAŁO",
    "CIĄŻA", "CIOSK",
    "CISAWY", "COFAĆ",
    "CÓRCE", "CUDZY",
    "CUGLE", "CZAPLA",
    "CZAPL",
    "CZEPEK", "CZERŃ",
    "CZERW",
    "CZÓŁNO",
    "CZYNIA", "CZYNEM",
    "DANIE",
    "DĄSEM", "DEKOR",
    "DENGA", "DENAT",
    "DESKI", "DESKA",
    "DETAL", "DIETA",
    "DŁUTO", "DOBRE",
    "DOBYĆ", "DODAT",
    "DOJŚCIE", "DOLEK",
    "DOMEK", "DONIK",
    "DORYW", "DOWÓD",
    "DRAKA", "DRWAL",
    "DRŻEĆ",
    "DUKAT", "DUMNY",
    "DŻDŻYSTY",
    "EGIDA",
    "EMALIA",
    "ERGO",
    "EROZY", "ETANOL",
    "ETUI", "FAJKA",
    "FALKA", "FALOM",
    "FAMIL", "FANKA",
    "FANFAR", "FARBK",
    "FARTU", "FARYZU",
    "FASADA", "FATAŁ",
    "FATYK", "FEBRĄ",
    "FETAL", "FETOW",
    "FICYK", "FIKUS",
    "FILTR", "FIOLEK",
    "FLAIR", "FLAKON",
    "FLARA",
    "FLIRT", "FLASK",
    "FOBIA", "FOTON",
    "FROTER", "FULAR",
    "GABINET", "GALOP",
    "GAMMA",
    "GAWĘDA", "GAWRON",
    "GAZET", "GEJZER",
    "GIEŁDA", "GLANS",
    "GLAZUR", "GŁUPIE",
    "GODŁO", "GOLEN",
    "GORSET", "GOTYK",
    "GRACA", "GRACJA",
    "GRANAT", "GRANDA",
    "GRASZ", "GREJĄ",
    "GRZBIT", "GZYMS",
    "HAŁAS", "HAŁAŚ",
    "HAMAK", "HARFA",
    "HERBO", "HERB",
    "HORDA", "HUCIA",
    "IDYLLA", "IKONA",
    "IKSEM", "IMPAS",
    "INDYK", "IPSEM",
    "IRONIA",
    "JAGODA", "JAMNIK",
    "JASION", "JAWOR",
    "JĘDZA", "JEDZA",
    "JODYNA", "JUHAS",
    "JUNAK", "JUTRO",
    "KADŁUB", "KAJET",
    "KAJUTA", "KALKUL",
    "KAMYK", "KANAŁ",
    "KAPTUR", "KĄPIEL",
    "KARB",
    "KARŁEM", "KARZEŁ",
    "KASJER", "KATAR",
    "KAWIOR",
    "KĘDZIE", "KIEDY",
    "KIELICH",
    "KLAUN", "KLEJEM",
    "KLEPKI", "KLEPKA",
    "KLIMAT",
    "KŁUSA",
    "KOLBA", "KOLEC",
    "KOLIA", "KOMIK",
    "KOMOS", "KOPUŁA",
    "KOPIEC", "KOPYTA",
    "KORAL", "KORDEK",
    "KORDYL", "KORNET",
    "KORONA", "KORZEŃ",
    "KOTEK", "KOTEW",
    "KOZIOŁ", "KRĄG",
    "KREDENS", "KREDA",
    "KREDO", "KREMEM",
    "KRETS", "KREWNA",
    "KREWNY", "KROBLA",
    "KRONIK",
    "KRUCHE", "KRUCHO",
    "KRYPTA", "KRZYŻ",
    "KRZTUS", "KUJON",
    "KULISY",
    "KUNA", "KUPIEC",
    "KURIA", "KURIER",
    "KURORT", "KWORUM",
    "LARUM", "LASKA",
    "ŁAWICA", "LAWKA",
    "ŁAWKA", "LEDWO",
    "LEMUR", "LENIW",
    "LEPIK", "LETNI",
    "LINIA",
    "LITERAT",
    "LOKAL", "LOLLY",
    "LOTKA", "LOTOS",
    "LUFER", "LUPINA",
    "ŁACHMAN",
    "ŁAGOD", "ŁATKA",
    "ŁOBUZIE",
    "ŁOJEK", "ŁOPIAN",
    "ŁOPOTEM", "ŁOTRY",
    "ŁOTR", "ŁOWICA",
    "ŁOWIEC",
    "ŁUBEK",
    "MACHIN", "MAFIA",
    "MAGINOT", "MAJDAN",
    "MAJON", "MAKIEM",
    "MAŁPIO",
    "MANGUST", "MANIA",
    "MANIAK", "MANTRA",
    "MARGA", "MAROT",
    "MARUN", "MARYJA",
    "MAWIN", "MAZAJ",
    "METAN",
    "MRUCZEC", "MUNDUR",
    "MUREK", "MUZYK",
    "NACISK", "NACZYN",
    "NAJAZD", "NAJEM",
    "NAPIS", "NAREW",
    "NARCYZ",
    "NARZĄD", "NAWET",
    "NAWÓZ", "NERW",
    "NIEMY", "NISKO",
    "NITKA", "NÓŻKA",
    "NUMER", "NURTEM",
    "NURT", "OBELGA",
    "OBITYM", "OBÓZ",
    "OBRONA", "OBWÓD",
    "OCTAN", "OCZKO",
    "OFERTA",
    "OLEJEK", "OLEJ",
    "OŁTARZ", "OMLET",
    "OPŁATA",
    "ORYKS", "ORZECH",
    "OWAD",
    "PACEŁ", "PACZKA",
    "PALIA", "PALMA",
    "PANICZ", "PANNA",
    "PAPIER",
    "PARZE", "PASJA",
    "PAWIA", "PAWILON",
    "PERŁA", "PERUK",
    "PIKAP", "PIKNIK",
    "PINAKL", "PIWKO",
    "PIZGA", "PLAMA",
    "PLATAN", "PLECAK",
    "PODNÓŻEK",
    "PODROBY",
    "POJAZD",
    "POLANO", "POMPA",
    "POPĘD", "PORTAL",
    "POSADA", "POSAG",
    "POŚCIG",
    "PRÓBKA", "PROCH",
    "PRODUKT", "PROFIL",
    "PROTON", "PRÓŻNY",
    "PSOTA", "PSTRYK",
    "PUCHAR", "PUCEK",
    "PULPIT", "PUŁAP",
    "PUNKT", "PUPILA",
    "PUSTAK", "PUSZKA",
    "RYWAL", "RZEMIEŃ",
    "SADZIĆ", "SAHEL",
    "SAKWA", "SALON",
    "SAPAĆ", "SAPER",
    "SATELITA", "SATYRA",
    "SCHODY",
    "SENAT", "SERIA",
    "SIERPIEŃ",
    "SIEĆ",
    "SKARB",
    "SKONAĆ",
    "SKRÓT",
    "SKUNKS", "SŁOIK",
    "SŁONA",
    "SŁUPEK",
    "SOBOTA",
    "SOLIST", "SOPEL",
    "SPODEK",
    "SPOIWO",
    "SPUST",
    "ŚRODEK",
    "STADO",
    "STECZN", "STOK",
    "STOPAR",
    "STOPY",
    "STREFA",
    "STRUŚ", "STUK",
    "STUSEK",
    "SZABAN", "SZACHISTA",
    "SZACHY",
    "SZALET", "SZANSA",
    "SZATA",
    "SZPIEG",
    "SZPILK",
    "SZRON",
    "SZTURM",
    "SZYBKO",
    "SZYK",
    "ŚCIEK",
    "ŚLAD", "ŚLINA",
    "ŚRUBA", "ŚRODA",
    "ŚWIADEK",
    "TARCIE", "TARCZA",
    "TARTE", "TARTY",
    "TĘSKNOTA",
    "TLENU", "TLEN",
    "TONIK", "TORPEDA",
    "TOWAR", "TRĄBKA",
    "TRENER",
    "TRUNEK", "TRWOGA",
    "TRYB", "TRZASK",
    "TUBA", "TULEJA",
    "TUMAN", "TURBAN",
    "TURBINA", "TYGIEL",
    "TYNK",
    "ULOTKA", "UPUST",
    "URNA", "UWAGA",
    "WABIK", "WACHLARZ",
    "WAPIEŃ",
    "WARTOWNIK",
    "WIANEK",
    "WICHER", "WIDOK",
    "WIĘŹ",
    "WIKLINA",
    "WIRUS", "WITRAŻ",
    "WNĘTRZE", "WNĘKA",
    "WÓDZ", "WROGI",
    "WRZOS", "WYBUCH",
    "WYCINEK", "WYJŚCIE",
    "WYMIAR",
    "WYRAZ", "WYSKOK",
    "WZROST",
    "ZABOBON", "ZACIĄG",
    "ZACISZE",
    "ZANIK",
    "ZAPINKA", "ZAPŁON",
    "ZARÓWNO", "ZASADZKA",
    "ZASTÓJ",
    "ZASUWA",
    "ZAWAŁ", "ZAWIERUCHA",
    "ZBIEG",
    "ZDANIE", "ZDOBYCZ",
    "ZEMSTA", "ZGAGA",
    "ZGLISZCZA", "ZGROZA",
    "ZGUBA",
    "ZJAZD",
    "ZŁOTA", "ZŁOTO",
    "ZMĘCZENIE", "ZMROK",
    "ZNAWCA", "ZNIKNĄĆ",
    "ZOOLOG", "ZORZA",
    "ZRĄB", "ZRYW",
    "ZWADA", "ZWITEK",
    "ZWROT",
    "ŻAGIEL", "ŻALUZJA",
    "ŻANDARM", "ŻARÓWKA",
    "ŻBIK",
    "ŻMUDNY", "ŻONKIL",
    "ŻÓŁTKO", "ŻÓŁW",
    "ŻURAW", "ŻUŻEL",
    "ŻWIR",
    "ŹDŹBŁO",
    "ZDOBYCZ", "ZNAK",
    "ZORZA", "ZRYW",
    "ŻYWICA",
    "ZAGON",
    "ZAGRODA", "ZAKĄTEK",
    "ZAMIEĆ", "ZARAZA",
    "ZASIEK", "ZASUWA",
    "ŻBIK", "ZDRÓJ",
    "ZIELE", "ZIELNIK",
    "ZIMNICA",
    "ZROST", "ZRYW",

    # More diverse vocabulary
    "AGAWA", "AGREST",
    "AKCENT", "AKOMOD",
    "AKTYWNOŚĆ",
    "ALIANS",
    "ALKIERZ",
    "ARKUSZ",
    "ARTYSTA",
    "ASPEKT",
    "ASUMPT",
    "ATRYBUT",
    "AWANTURA",
    "BACZNY",
    "BAJARZ",
    "BALAST",
    "BAŁAGAN",
    "BAŁWAN",
    "BANDA",
    "BARITON",
    "BARYTON",
    "BASZTA",
    "BATALIA",
    "BIGOTKA",
    "BLOKADA",
    "BLUSZCZEM",
    "BOCZEK",
    "BOGINI",
    "BOLERO",
    "BOSKIE",
    "BRAMA",
    "BRANKA",
    "BRZDĄC",
    "BRZĘK",
    "BUKSZT",
    "BZDUREK",
    "CAŁUN",
    "CĄŻKI",
    "CIEŚLA",
    "CISZA",
    "COFNIE",
    "CYMBAL",
    "CYNIZM",
    "CZAJKA",
    "CZCION",
    "CZEPEK",
    "CZOPIA",
    "CZOPEK",
    "CZOSNK",
    "DALMIERZ",
    "DARNIA",
    "DŁUBAĆ",
    "DŁUŻNIK",
    "DOBOSZ",
    "DOBYĆ",
    "DOGMAT",
    "DOJRZE",
    "DOKOŁA",
    "DOKTRYNA",
    "DOMENA",
    "DONOS",
    "DORADCA",
    "DOSŁOW",
    "DOZNANIE",
    "DRESZCZ",
    "DROBIAZG",
    "DRÓŻKA",
    "DRWINA",
    "DRZAZGA",
    "DUCH",
    "EKSCYTACJA",
    "EKSPRES",
    "EKWIPUNEK",
    "ESTRADA",
    "ETAP",
    "ETNIKA",
    "FATAMORGANA",
    "FIKSUM",
    "FILAR",
    "FOKUS",
    "FRAZA",
    "FRESK",
    "FUNDAMENT",
    "GAJOWY",
    "GALEON",
    "GAŁĘZIE",
    "GARDZIEL",
    "GATUNEK",
    "GAWIEDŹ",
    "GENIUS",
    "GESTEM",
    "GIĘTEK",
    "GŁOSEM",
    "GNUŚNY",
    "GORYLA",
    "GOSPODARZ",
    "GRACJOZA",
    "GRODZISKO",
    "GROŹBA",
    "GRUCZOŁ",
    "GRZYBEK",
    "GWARNY",
    "HASAJK",
    "HEGEMON",
    "HERCOG",
    "HETMAN",
    "HIENA",
    "HISTORIA",
    "HODOWLA",
    "HOLOGRAM",
    "HOŁD",
    "HORDA",
    "HORYZONT",
    "HUCZEK",
    "IDEAŁ",
    "IMIĘ",
    "INICJAŁ",
    "INSTANCJA",
    "INTUICJA",
    "JABŁKO",
    "JADWIGA",
    "JASTRZĄB",
    "JASZCZUR",
    "JEDNOMYŚLNOŚĆ",
    "JEJKU",
    "JELITKO",
    "JERZYK",
    "JEZIORO",
    "JOBSJOB",
    "JURNY",
    "KADENCJA",
    "KAKOFONIA",
    "KAMIZELKA",
    "KANON",
    "KANTATA",
    "KAPITAN",
    "KARAWANA",
    "KAWALER",
    "KENOZOIK",
    "KIESZEŃ",
    "KLASZTOR",
    "KLERYK",
    "KLIMAT",
    "KOGEL",
    "KOGUT",
    "KOLEBKA",
    "KOLONIA",
    "KOPALNIA",
    "KOPERTĄ",
    "KORNET",
    "KOSTKA",
    "KOZŁOW",
    "KRAWĘDŹ",
    "KRAJAN",
    "KREATYWNOŚĆ",
    "KREWETKA",
    "KROKIEW",
    "KROTKI",
    "KRUCZEK",
    "KRYMINA",
    "KRZAK",
    "KUBEŁEK",
    "KUGLARZ",
    "KUROPATWA",
    "KWIATKI",
    "KWINTET",
    "LABIRYNT",
    "LAPIDARNI",
    "LATARNIA",
    "LAWINA",
    "LEBIED",
    "LECZNICA",
    "LEGENDA",
    "LEGION",
    "LEKKOŚĆ",
    "LEPIEJ",
    "LETARG",
    "LEWAR",
    "LICHEN",
    "LICHY",
    "LORDOZY",
    "LUSTRZANKA",
    "ŁAGODNY",
    "ŁATWY",
    "ŁOBUZ",
    "ŁOŻYSKO",
    "ŁUCZNIK",
    "ŁYDEK",
    "MACERACJA",
    "MALOWAĆ",
    "MAMRO",
    "MANIAKALNA",
    "MAPOWANIE",
    "MARYNARZ",
    "MASYWNY",
    "MATEUSZ",
    "MAZUREK",
    "MEDYTACJA",
    "MELODIA",
    "METODA",
    "METRUM",
    "MIKROKOSMOS",
    "MILCZEĆ",
    "MLECZARZ",
    "MOCARZ",
    "MODELKA",
    "MOGIŁA",
    "MONARCHA",
    "MORZA",
    "MRUCZEK",
    "MYLNIE",
    "NATURA",
    "NIEOMAL",
    "NIERADA",
    "NIEUBŁAGANY",
    "NIMBUS",
    "NOCLEGIEM",
    "NOSTROMO",
    "OCHRONA",
    "ODNAWIALNY",
    "ODWAGA",
    "OŚWIECENIE",
    "OTOCZENIE",
    "OWACJA",
    "PAMIĘĆ",
    "PASAŻ",
    "PATRIOTA",
    "PEJZAŻ",
    "PELERYNA",
    "PĘKATA",
    "PIÓROPUSZ",
    "PLAGIATOR",
    "PLAKAT",
    "PŁOMIEŃ",
    "PŁONĄĆ",
    "POCZT",
    "PODDAĆ",
    "POGODA",
    "POKORNY",
    "POTEGA",
    "PROLOG",
    "PRZODEK",
    "PYCHA",
    "RABUNEK",
    "RACHUNEK",
    "RADAR",
    "RADON",
    "RADYKALNY",
    "RDZAWY",
    "RDZEŃ",
    "REFLEKS",
    "REGUŁA",
    "REKTOR",
    "RENIFER",
    "RESURSA",
    "RETORYKA",
    "REWANŻ",
    "REWIA",
    "RYTM",
    "RYWALIZACJA",
    "RZEKA",
    "RZEŹBA",
    "SAMOSĄD",
    "SENTENCJA",
    "SIEROTKA",
    "SIWY",
    "SKARGA",
    "SKANDAL",
    "SKŁON",
    "SKUPIENIE",
    "SŁAWNY",
    "SŁODYCZ",
    "SŁUGA",
    "SOJUSZ",
    "SOKOLNIK",
    "SONET",
    "SORTOWANIE",
    "SOWIETY",
    "SPLENDOR",
    "SPOKOJNY",
    "SPRYT",
    "STABILNOŚĆ",
    "STANGRET",
    "STARCIE",
    "STERNIK",
    "STOLICA",
    "STRACH",
    "STRZELEC",
    "SUBTELNY",
    "SUROWIEC",
    "SYMPATIA",
    "SYNERGIA",
    "SZERMIERZ",
    "SZNYT",
    "SZPALT",
    "SZPON",
    "SZTORMY",
    "SZUBIENICA",
    "SZWEDHEJ",
    "ŚCIANA",
    "ŚLUBNY",
    "ŚLUBOWAĆ",
    "ŚLADY",
    "ŚMIGŁO",
    "ŚRODKOWY",
    "ŚWIEŻOŚĆ",
    "TAKIELUN",
    "TAJEMNICA",
    "TALENTY",
    "TANCERKA",
    "TARGETOW",
    "TĘCZA",
    "TRAGIZM",
    "TRANZYT",
    "TRAWESTACJA",
    "TRIUMF",
    "TRWAŁOŚĆ",
    "TYRADA",
    "UCZTA",
    "UŁAN",
    "UMINIEĆ",
    "UROK",
    "USPOSOB",
    "UTOPIA",
    "UWIEŚĆ",
    "UZDROWISKO",
    "WAROWNIA",
    "WARTOWNIA",
    "WDZIĘCZNY",
    "WĘZEŁ",
    "WIAROŁOMNY",
    "WIKŁAĆ",
    "WJAZD",
    "WŁADCA",
    "WŁAŚNOŚĆ",
    "WNIOSEK",
    "WRÓŻBA",
    "WYBITNY",
    "WYCHOWANEK",
    "WYGNANIE",
    "WYNIOSŁY",
    "WYTCHA",
    "WYSŁANNIK",
    "WZOROWY",
    "ZACNY",
    "ZAGADKOWY",
    "ZAKRES",
    "ZASŁUGI",
    "ZEBRANI",
    "ZIEMIANIN",
    "ZNAKOMITY",
    "ZWIEŃ",
    "ŻARLIWY",
    "ŻELAZNY",
    "ŻMUDNY",
    "ŻYCIOWY",

    # Filling up to reach ~3000 with common 5-letter words
    "ABARY", "ABBOT",
    "BRZEG", "BRZOZA",
    "CZAJKA", "CZAJK",
    "DĄBEK", "DRGAĆ",
    "EKRAN", "ETAP",
    "FARAT", "FIKUS",
    "GANEK", "GANIĆ",
    "HAŁAS", "HERBA",
    "IGLAK", "IGRAK",
    "JABŁK", "JADAM",
    "KAFEL", "KAFLE",
    "LAKWA", "LAPKA",
    "MAKOR", "MAKSA",
    "NAKAZ", "NARÓD",
    "OBRUS", "OCENA",
    "PAMĄT", "PAMĄĆ",
    "RABAT", "RACJA",
    "SADŁO", "SAFARI",
    "TABAK", "TABOK",
    "UKRYT", "ULEGA",
    "VAPOR", "VENEZ",
    "WADZE", "WĄTEK",
    "YAKAZ", "YKORT",
    "ZAMEK", "ZASPA",

    # More Polish words
    "PIAĆ", "PICHCIĆ",
    "PIKOWAĆ", "PILNOWAĆ",
    "PINEZKA", "PIORUN",
    "PISZCZEL", "PIWA",
    "PLANER", "PLECAMI",
    "PLOMBA", "PLOTKA",
    "PLUGAW", "PŁAKAĆ",
    "PŁAWA", "PŁAWIĆ",
    "PŁETWA", "PŁOTEK",
    "PŁOWIEĆ",
    "POGODA", "POGOŃ",
    "POGRĄŻ",
    "POKARM",
    "POKŁON",
    "POLAK",
    "POLANĘ",
    "POWABNY",
    "POWAŁA",
    "PRACKA",
    "PRĘDKO",
    "PROŚBA",
    "PROŻEK",
    "PRYMKA",
    "PRYSZNIC",
    "PRZAŚNIK",
    "PRZEDE",
    "PRZEŁOM",
    "PRZYBYSZ",
    "PRZYCZ",
    "PUHAR",
    "PULAR",
    "RABAN",
    "RABATA",
    "RADŁA",
    "RADOSNY",
    "RAMPA",
    "RANCE",
    "RASZPLA",
    "RATOWNIK",
    "RDZAWY",
    "RDZEŃ",
    "RZEPICHA",
    "ROŻEN",
    "RUGBY",
    "RUINA",
    "RZADKO",
    "RZEPIK",
    "RZERWA",
    "RZUTKI",
    "SAMICA",
    "SAMIEC",
    "SAPANIE",
    "SECESJA",
    "SEDIMENT",
    "SEJSMIK",
    "SEKCJA",
    "SEKTANT",
    "SERYJNY",
    "SETA",
    "SETNY",
    "SFINKS",
    "SIEROTA",
    "SILIWKA",
    "SKARGA",
    "SKARPED",
    "SKASOWANIE",
    "SKAZA",
    "SKRZYNKA",
    "SKRZYPCE",
    "SŁABNĄĆ",
    "SŁONINK",
    "SŁOWIK",
    "SŁUGA",
    "SŁUŻKA",
    "SMUTNO",
    "SMYCZ",
    "SOFISTA",
    "SOJUSZNIK",
    "SOKOLA",
    "SOŁTYS",
    "SOPRAN",
    "SORTOWANIE",
    "SPAZM",
    "SPIESZNO",
    "SPŁATA",
    "SPŁAW",
    "SPODNIE",
    "SPOWIED",
    "SPRZED",
    "SPUŚCIZNA",
    "STAJNIĄ",
    "STAMTĄD",
    "STARADA",
    "STARCH",
    "STARTER",
    "STARZYĆ",
    "STĄPAĆ",
    "STEBNIĆ",
    "STEMPL",
    "STERNIK",
    "STEROWAĆ",
    "STOISKO",
    "STOLAT",
    "STOSIK",
    "STOŻEK",
    "STRÓŻ",
    "STRÓŻKA",
    "STRUTKA",
    "STRZAŁA",
    "STUDIA",
    "STUDNIA",
    "STUKNĄĆ",
    "SUBIEKT",
    "SUKA",
    "SUKNIA",
    "SULTAN",
    "SUMIENIE",
    "SUMKA",
    "SUPEK",
    "SURDUT",
    "SURMA",
    "SUROWA",
    "SYGNAŁ",
    "SYKNĄĆ",
    "SYROP",
    "SZCZYT",
    "SZERYF",
    "SZORSTKOŚĆ",
    "SZPULA",
    "SZUBAS",
    "SZULER",
    "SZUMINA",
    "SZWAGIERKA",
    "SZYDEŁKO",
    "SZYDŁO",
    "SZYFR",
    "SZYJKA",
    "ŚCIEŻKA",
    "ŚCISK",
    "ŚLEDZTWO",
    "ŚLIMAK",
    "ŚLISKI",
    "ŚLUZA",
    "ŚPIWÓR",
    "ŚRUBKA",
    "ŚRODA",
    "ŚWIADEK",
    "TABLETKA",
    "TAJNIK",
    "TAKT",
    "TAMTĘDY",
    "TANCERZ",
    "TARGU",
    "TATAREK",
    "TATUAŻ",
    "TECZKA",
    "TĘCZA",
    "TKANKA",
    "TLIĆ",
    "TŁUMACZENIE",
    "TOCZNIA",
    "TOCZYĆ",
    "TORFIAK",
    "TRAGARZ",
    "TRAKT",
    "TRAWKA",
    "TREBUSZ",
    "TREFOIL",
    "TRESURA",
    "TROCHA",
    "TROFEA",
    "TRÓJCA",
    "TRÓJNÓG",
    "TRUCHŁO",
    "TRUCICIEL",
    "TRUDNE",
    "TRUDNO",
    "TRUPIK",
    "TRUPOSZ",
    "TRWALE",
    "TUBKA",
    "TULIĆ",
    "TWARÓG",
    "TWAROZEK",
    "TWIERDZIĆ",
    "TYCZKA",
    "TYMIANEK",
    "TYNKARZ",
    "TYPOWY",
    "TYRAN",
    "TYSIĄCE",
    "UBIEGŁY",
    "UBIÓR",
    "UCIEKA",
    "UGODA",
    "UKROP",
    "ULICZKA",
    "ULOTKA",
    "UMILKNĄĆ",
    "UPARTY",
    "UPIÓR",
    "UPRZEJMY",
    "URODA",
    "UROK",
    "USŁUGA",
    "UTRATA",
    "UZBROJENIE",
    "UCZYNEK",
    "WABIENIE",
    "WAGA",
    "WAKACJE",
    "WALETA",
    "WANNA",
    "WARTOŚĆ",
    "WĄTŁY",
    "WEŁNA",
    "WESELE",
    "WIĄZKA",
    "WICHER",
    "WIDZIADŁO",
    "WIEDŹ",
    "WIELBŁĄD",
    "WIELOŚĆ",
    "WIEPRZ",
    "WIERSZ",
    "WIESZCZ",
    "WIETRZ",
    "WIOCHA",
    "WIÓREK",
    "WKURZENIE",
    "WNĘKA",
    "WÓDZ",
    "WÓJT",
    "WRÓBLEK",
    "WRZASK",
    "WRZEĆ",
    "WRZESIEŃ",
    "WSKAŹNIK",
    "WSKROŚ",
    "WSTYD",
    "WTOREK",
    "WYBORNY",
    "WYJAŚNIENIE",
    "WYKOPALISKO",
    "WYLADOW",
    "WYNALAZ",
    "WYOBRAZ",
    "WYPOCZYNEK",
    "WYRAZ",
    "WYRAŻENIE",
    "WYSPIARZ",
    "WYTĘSKNIONY",
    "WYZWANIE",
    "WZIĘCIE",
    "WZRUSZENIE",
    "ZAGROŻENIE",
    "ZAKAZ",
    "ZAMYSŁ",
    "ZAPANOWAĆ",
    "ZAPOMNIENIE",
    "ZARZĄDZENIE",
    "ZASADNOŚĆ",
    "ZASKOCZYĆ",
    "ZAWIADOMIENIE",
    "ZBIORNIK",
    "ZEMSTA",
    "ZNIKNIĘCIE",
    "ZOBOWIĄZANIE",
    "ZRYWKA",
    "ZUCHWALEC",
    "ZWAŻYWSZY",
    "ŻEGLUGA",
    "ŻOŁNIERZ",
    "ŻURAW",
]


def make_wordlist(raw):
    """Filter to exactly-5-char words, deduplicate, sort."""
    seen = set()
    result = []
    for w in raw:
        w = w.strip().upper()
        if len(w) == 5 and w.isalpha() and w not in seen:
            seen.add(w)
            result.append(w)
    return sorted(result)


solutions = make_wordlist(SOLUTIONS_RAW)
extra = make_wordlist(EXTRA_WORDS_RAW)

# All words = solutions + extra words
all_words_set = set(solutions) | set(extra)
all_words = sorted(all_words_set)

print(f"Solutions: {len(solutions)}")
print(f"All words: {len(all_words)}")

# Write solutions file
os.makedirs("/home/user/c/GameAggregator/GameAggregator/Resources", exist_ok=True)

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_solutions.txt", "w", encoding="utf-8") as f:
    for w in solutions:
        f.write(w + "\n")

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_words.txt", "w", encoding="utf-8") as f:
    for w in all_words:
        f.write(w + "\n")

print("Files written.")
print(f"Solutions file: {len(solutions)} words")
print(f"Words file: {len(all_words)} words")

# Verification
with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_solutions.txt", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip()]
bad = [w for w in lines if len(w) != 5]
print(f"Bad-length solutions: {len(bad)}")
if bad:
    print("BAD:", bad[:20])

with open("/home/user/c/GameAggregator/GameAggregator/Resources/wyraz_words.txt", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip()]
bad = [w for w in lines if len(w) != 5]
print(f"Bad-length words: {len(bad)}")
if bad:
    print("BAD:", bad[:20])

# Check solutions are subset of words
sol_set = set(solutions)
word_set = set(all_words)
missing = sol_set - word_set
print(f"Solutions not in word list: {len(missing)}")
