import Foundation

// Hardcoded fallback levels used only if gwiazdki_levels.json is missing from bundle.
// The main bundle file (generated by StarBattleGenerator) is the real data source.
enum EmbeddedLevels {
    static let all: [StarBattleLevel] = {
        var levels: [StarBattleLevel] = []
        levels.append(contentsOf: size6Levels())
        levels.append(contentsOf: size7Levels())
        levels.append(contentsOf: size8Levels())
        return levels
    }()

    // MARK: - 6×6 (regions encoded as row-strings of digit chars 0-5)

    private static func make(_ id: Int, _ size: Int, _ rows: [String]) -> StarBattleLevel {
        let flat = rows.flatMap { row in row.compactMap { Int(String($0)) } }
        return StarBattleLevel(id: id, gridSize: size, regions: flat)
    }

    private static func size6Levels() -> [StarBattleLevel] {
        [
            make(1, 6, ["000111","001112","033122","033222","034455","344555"]),
            make(2, 6, ["001122","001122","033445","033445","335445","335555"]),
            make(3, 6, ["000112","003112","033442","335442","355544","355544"]),
            make(4, 6, ["012222","012233","011233","004433","004453","044553"]),
            make(5, 6, ["001122","001122","034412","334412","334455","334455"]),
            make(6, 6, ["000011","022011","022311","224311","244333","445533"]),
            make(7, 6, ["001122","001122","003352","033552","334552","344455"]),
            make(8, 6, ["012222","002233","001233","001433","004453","004553"]),
        ]
    }

    private static func size7Levels() -> [StarBattleLevel] {
        [
            make(18, 7, ["0001122","0011122","0034522","0334552","3344556","3446556","4446666"]),
            make(19, 7, ["0001122","0011222","0034422","0334456","3334456","3355566","3555666"]),
        ]
    }

    private static func size8Levels() -> [StarBattleLevel] {
        [
            make(35, 8, ["00011222","00011222","00341522","03341552","03344556","03344556","07744666","07777666"]),
        ]
    }
}
